### ISSUE TITLE
Apps get restored "ONLY in Work profile", instead of primary profile

### ISSUE THREAD

**Issue by talk2g** [machiav3lli/oandbackupx#10]
Different than the other "shelter" issue since in that apps got installed in both work and primary profile,however in this case the apps get restored in **_only_** work profile

Fix- 1) Restore ur app
2)after installing check whether your work profile has that app or not.
3) if yes, navigate to the backup folder and install that app from the base.apk
4)uninstall app from work profile
Note- after installing base.apk in primary profile, u will automatically get ur data since u restored it earlier (given in step 1 u selected "apk+data")

**Comment by machiav3lli** [comment]
We'll see the users logic. Thanks again.
