### ISSUE TITLE
Cannot backup when incomplete data in  backup folder

### ISSUE THREAD

**Issue by mase76** [machiav3lli/oandbackupx#100]
Hi!
When a backup of an app was frozen or unsuccessful, and I retry this app, the backup process does not start, until I delete the
incomplete content in the app's backup folder. All the content should be deletet first, before the backup starts. I guess the content is just overwritten?

**Comment by machiav3lli** [comment]
It has to do with the fact that uncompleted backups are being handled as none existing backups and so no files are being deleted before trying to create the new backup causing failure in copying.
