### ISSUE TITLE
[Bug] 404/dead changelog link on F-Droid

### ISSUE THREAD

**Issue by AlexanderRitter02** [machiav3lli/oandbackupx#102]
**Description**
The link in F-Droid to the changelog of this app leads to a **404 error**, page is not found.

**Steps To Reproduce**
1. Go to the apps [F-Droid page](https://f-droid.org/en/packages/com.machiav3lli.backup/) 
2. Below description, were there's the Source code link, click on _Changelog_

:x: 404 on Github

**Solution**
Capitalize `changelog` to `CHANGELOG` in the link.

**Comment by machiav3lli** [comment]
PRed and merged in F-Droid data.
