### ISSUE TITLE
Flashable-ZIP feature

### ISSUE THREAD

**Issue by bolbolfolfol** [machiav3lli/oandbackupx#103]
Hi
on the changelog of the oandbackupx you say : Add a Flashable-ZIP feature

i installed the app 2 times but could not find it anywhere
what should i do ?

**Comment by Atrate** [comment]
It's a planned feature.

**Comment by machiav3lli** [comment]
As you can see my friend, it has an unchecked checkbox which in this topic means, it's planned but not there yet.
