### ISSUE TITLE
[Bug] Error on Backup: BackupFailedException: cp: …: No such fil or directory

### ISSUE THREAD

**Issue by baack** [machiav3lli/oandbackupx#105]
**Description**
Backup of Fennec F-Droid (firefox fork from f-droid) fails with message:
`BackupFailedException: cp: /data/user/0/org.mozilla.fennec_fdroid/files/mozilla/profile_name.default/lock: No such file or directory`

**Steps To Reproduce**
1. Install Fennec F-Droid (Firefox fork from f-droid)
2. Run and use Fennec F-Droid
3. Try to backup it in OAndBackupX
4. Get error message

**Expected behavior**
Successful backup of application Fennec F-Droid.

**System Information(please complete the following information):**
 - Device: Android phone
 - Android Version: 8.1
 - ROM: LineageOS (LOS)
 - App's Version: 3.1.0 (latest)

**Comment by dhammel** [comment]
I am getting the same error when trying to backup the latest stable version of official firefox app+data with the latest version of oandbackupx.

**Comment by machiav3lli** [comment]
Duplicate #84
