### ISSUE TITLE
[Bug] Translation license mistakenly AGPLv1+

### ISSUE THREAD

**Issue by comradekingu** [machiav3lli/oandbackupx#107]
OAndBackupX is the only project on Weblate with AGPLv1+ licensing.
I am almost certain that should have been AGPLv3+ as with so many others.

To be extra sure, I think AGPLv2+ should be selected, and then AGPLv3+ :)
https://en.wikipedia.org/wiki/Affero_General_Public_License#Compatibility_with_the_GPL

This can be done in (respectively)

https://hosted.weblate.org/settings/oandbackupx/help/
https://hosted.weblate.org/settings/oandbackupx/store-information/
https://hosted.weblate.org/settings/projects/oandbackupx/strings/

If you want to add me as an admin, you can do so in
https://hosted.weblate.org/access/oandbackupx and I can upload screenshots and make sure the rest is as it should. :)

**Comment by machiav3lli** [comment]
Just fixed it, thanks for the notice. I missed AGPLv3+ while picking the settings for the Weblate project.
