### ISSUE TITLE
[Bug] Restore apk+data does not restore data

### ISSUE THREAD

**Issue by cptMikky** [machiav3lli/oandbackupx#108]
**Description**
On Lineage 17.1 data does not get restored when "APK+DATA" is selected on restore.

No encryption (of the backups, the phone itself **is** encrypted, if that makes a difference), backups are stored on the internal storage.

**Steps To Reproduce**
1. create APK+DATA backup
2. wipe phone data
3. restore app from backup, incl. data
4. `/data/data/<app-name>` only contains `cache` and `code_cache` directories, no data is present

**Expected behavior**
All data in `/data/data/<app-name>`should be in place with correct user:group ownership set.

For some applications manually restoring data from `/<storage>/backup/<app-name>/<app-name>.zip` and setting proper ownership via shell works meaning the data is very likely backed up correctly and the issue is in the restore process only.

**Screenshots**
```
starlte:/  # ls -la /data/data/<freshly-restored-app>                                                                                     
total 32
drwx------   4 u0_a156 u0_a156        4096 2020-09-06 23:20 .
drwxrwx--x 191 system  system        12288 2020-09-06 23:20 ..
drwxrws--x   2 u0_a156 u0_a156_cache  4096 2020-09-06 23:20 cache
drwxrws--x   2 u0_a156 u0_a156_cache  4096 2020-09-06 23:20 code_cache
```

**System Information(please complete the following information):**
 - Device: Samsung S9 (starlte)
 - Android Version: 10
 - ROM: Lineage 17.1, microg flavor, root by magisk
 - App's Version: 3.1.0

**Additional Notes**

Possibly a duplicate of #98 but I don't see any such errors. From UI/UX perspective it appears as if the restore was completely successful.

**Comment by cptMikky** [comment]
Hey, I think I found the problem:
```
 I OAndBackupX.RestoreAppAction: com.<app-name> [LoungeKey]: Restoring data     
 I OAndBackupX.RestoreAppAction: com.<app-name> [LoungeKey]: data archive does not exist: /storage/emulated/0/backup/com.<app-name>/data.tar.gz
 D OAndBackupX.RestoreAppAction: com.<app-name> [LoungeKey]: Uncompressed data was deleted: false
 I OAndBackupX.RestoreAppAction: com.<app-name> [LoungeKey]: Restoring permissions on data
```

_data archive does not exist: **/storage/emulated/0/backup/com.\<app-name\>/data.tar.gz**_ while the data archive is in fact called `com.<app-name>.zip`

**Comment by Tiefkuehlpizze** [comment]
Hi,
thanks for sharing all of this.
Zip isn't used anymore. It seems that you are trying to restore backups from an older version.
The app is still under heavy development and upgrade paths are currently not available. The version number is unfortunately misleading that the app is "finished" or _stable_ while in fact it isn't.

**Comment by cptMikky** [comment]
> you are trying to restore backups from an older version.

Can't really tell, I have my f-droid keep stuff up-to-date but don't always check. The backup happened minutes before the restore.

But even if that was true, it would have had to be `v3.0.0` at most. I suggest keeping versioning logic in line with [Semantic Versioning](https://semver.org/) and possibly tagging backups with API version so that these kind of mistakes are easily identified, possibly opening doors to upgrade paths and/or simple(r) backward compatibility maintenance.

**Comment by cptMikky** [comment]
In case any one is interested, I put together a rudimentary converter from zip to the new tar.gz format: https://gist.github.com/cptMikky/c515a4ead069b61f1231d68d361f882e

Usage:
`oconf.sh [path_to_backup]`

If path is unspecified, CWD is assumed. 

Not tested much so backup your backups before proceeding.

**Comment by cptMikky** [comment]
I fixed the script above to produce valid conversions even if `device_protected_data` (and any other directory ftm) ends up empty (usually because of cache cleanup).

Also added some basic readable output. The script works for me, ymmv.

**Comment by spa232323** [comment]
Hello !

I just wanted to report the fact that version 2.0.0 of OandBackupX worked fine so far, but since the version 3.X.X, even when I make some new backups (with new files in tar.gz), the restore isn't good. 
When I launch the restored apps (from a v3 backup : data + APK), the app starts and instantly crashes. It looks like there is a problem in the restoration process since the v3.

I tried on OandBackupX 3.1.1 and 3.2.0. In none of them the result of the restore is good. In both versions, the app restored starts and crashes instantly.

FYI I am under crDroid 4.7 (Android 8.1.0), but I don't think that really matters.

Hope everything will work just fine in the future because this app rocks otherwise !

Cheers

**Comment by machiav3lli** [comment]
@spa232323 there could be different reasons for the failing restore depending if the data of the app you restore uses symlinks or some other linking. The version 4.0.0 is on the make and shall be fixing those errors for the most part.
