### ISSUE TITLE
Sort and Filter doesnt work, even after toggling in the settings.

### ISSUE THREAD

**Issue by talk2g** [machiav3lli/oandbackupx#11]
i cant seem to make the app remember "sort" as well as "filter".
even after toggling in settings, it doesnt work.
if there something, i m doing wrong?1

**Comment by machiav3lli** [comment]
Oh, I forget binding the new implementation with the old pref. Should be fixed in the next update(in a week or so).

**Comment by talk2g** [comment]
Thx
