### ISSUE TITLE
[Bug] Crash on backup

### ISSUE THREAD

**Issue by Atrate** [machiav3lli/oandbackupx#12]
OS: Android 10

OandbackupX version: 0.9.7-universal

Description: Application crashes when trying to back up app+data (package: Protonmail)

Steps to reproduce: Try to back an app up on fresh install

Log: https://del.dog/nexelemebe

**Comment by machiav3lli** [comment]
It seems like you had no more apps shown on the view list, which caused the crash. Will fix this logic today. Thanks
