### ISSUE TITLE
[Bug] Locked strings in Weblate

### ISSUE THREAD

**Issue by Madis0** [machiav3lli/oandbackupx#123]
**Description**
Some strings are locked in Weblate.

**Steps To Reproduce**
1. Go to https://hosted.weblate.org/translate/oandbackupx/strings/et/?q=state:read-only
2. Attempt to translate the strings

**Expected behavior**
I expected to translate those strings, including "Checking for BusyBox/Toybox…", "Logfile saved at %s" and abbrevations like "USR". Surely the app name should not be translated, but I don't see why others couldn't. Most abbrevations make no sense if they are not translated, except for APK.

**Screenshots**
N/A

**System Information(please complete the following information):**
Irrelevant

Also, I created this issue here as I cannot even comment on those strings in Weblate.

-------------------------------
**Additional Notes**
* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly.
* If you're on the latest github version. Please read all the open Issues if one does match yours, leave a comment there if there's some extra information you can provide.
* If you're not on the latest github version(happens sometimes with F-Droid version), please read all of the open issues and also some of the latest closed issues.

Thanks for reporting

**Comment by machiav3lli** [comment]
It was locked for couple of minutes because of a repo error but nothing longer than 15 minutes. Could you please check it again on your side and close the issue if it works out. Thanks

**Comment by Madis0** [comment]
Still read only.
![Kuvatõmmis 2020-09-23 20-53-35](https://user-images.githubusercontent.com/8611110/94050264-b2a5d180-fdde-11ea-9a2b-9451bf82fa39.png)

**Comment by machiav3lli** [comment]
USR, APK, DAT among others are tags, which we decided shouldn't be translated as it'll be too much complicated to make it happen in some languages(representing a word in 3 chars).

**Comment by Madis0** [comment]
Doesn't weblate allow limiting the characters in a translation?

**Comment by machiav3lli** [comment]
At first I thought you're pointing out to the translations being locked, not that they're read-only. Sorry for misunderstanding

**Comment by machiav3lli** [comment]
The problem isn't only limiting the chars' number. The problem is that such abbreviations aren't translatable or don't make sense in the respective syntax of a language e.g. Chinese, Arabic.

**Comment by Madis0** [comment]
Alright, what about "Checking for BusyBox/Toybox…" and "Logfile saved at %s"?

**Comment by machiav3lli** [comment]
Those strings are part of the logging and so it's prefered to not translate them, as this could cause serious problems reading a log from some device with a language that the debugger don't know.

**Comment by Madis0** [comment]
Got it.
