### ISSUE TITLE
[Bug] SMS/Text Messages disappearing after a restore

### ISSUE THREAD

**Issue by gut5** [machiav3lli/oandbackupx#127]
**Description**
The text/sms messages restored to the Messaging app using OABX 3.2.0 are not being restored correctly, and disappear after you restore and then try to open the Messaging app. Lineage OS 17.1.

**Steps To Reproduce**
1. Restoring backup of Messaging (com.android.messaging)
2. Open Messaging
3. Messages appear briefly then disappear
4. Crash, Nothing happens ....

**Expected behavior**
I expected the messages to remain in the view but they only appear briefly then disappear again.

**Screenshots**
Hard to screenshots as the messages disappear very fast

**System Information(please complete the following information):**
 - Device:  Nexus 6
 - Android Version: 10 (Lineage 17.1) 
 - ROM: LineageOS
 - App's Version: 3.2.0

-------------------------------
**Additional Notes**
* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly.
* If you're on the latest github version. Please read all the open Issues if one does match yours, leave a comment there if there's some extra information you can provide.
* If you're not on the latest github version(happens sometimes with F-Droid version), please read all of the open issues and also some of the latest closed issues.

Thanks for reporting

**Comment by machiav3lli** [comment]
Already got cleared in tje TG group, com.android.messaging isn't the provider for messages. com.android.providers.telephony is the provider for call logs and messages.

**Comment by quantumpacket** [comment]
@machiav3lli Was this fixed? Using the latest F-Droid release (5.1.0) and I'm experiencing the same issue. The moment I open Messaging after a restore all the messages show for a split second then each of them disappears one by one very quickly. Oddly, the only one remaining is a restored draft message.

**Comment by machiav3lli** [comment]
@quantumpacket as already mentioned, messages isn't the app that saves your message. You need to backup the provider mentioned in my earlier response.
