### ISSUE TITLE
[Feature Request] Change backup UI design

### ISSUE THREAD

**Issue by Cyberavater** [machiav3lli/oandbackupx#143]
**Is your feature request related to a problem? Please describe.**
Currently, the backup UI seems old-ish and missing component selection.
**Describe the primer solution**
A clear and concise description of what you want to happen. You can do it also in steps.
It'd be nice backup components were selectable.

**Describe alternative solutions**

**Screenshots**
If you're willing to add demonstrative screenshots, you're welcome to do so.

Current Format;

![Screenshot_20201003-221714099](https://user-images.githubusercontent.com/32187927/94997170-4770b200-05cb-11eb-94c0-b787ef769bef.jpg)

Requested format:

![Screenshot_20201003-221823326](https://user-images.githubusercontent.com/32187927/94997176-5192b080-05cb-11eb-9176-1541144be288.jpg)

OR;

![Screenshot_20201003-221908681](https://user-images.githubusercontent.com/32187927/94997178-535c7400-05cb-11eb-8466-e6418f6675b8.jpg)

**System Information(please complete the following information):**
 - Device: 
 - Android Version: 
 - ROM: (AOSP, MIUI, OOS...)  
 - App's Version: 

-------------------------------
**Additional Notes**
* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please write it there directly.
* If you're on the latest github version. Please read all the open Issues if one does match yours, leave a comment there if there's some extra information you can provide.
* If you're not on the latest github version(happens sometimes with F-Droid version), please read all of the open issues and also some of the latest closed issues.

Hope it was easy to understand with SS, still if there is any confusion feel free to ask away.
Reported from the Latest beta from TG.
 
Thanks for your suggestion

**Comment by Atrate** [comment]
Since OP didn't mention it, first screenshot is from this app: https://github.com/MuntashirAkon/AppManager

**Comment by machiav3lli** [comment]
It's actually already in the TODO list in the code, my work on it will have unfortunately to wait couple of weeks as am having too little free time lately.
