### ISSUE TITLE
[Feature Request] Easter Egg? I can make a PR!

### ISSUE THREAD

**Issue by HiFiiDev** [machiav3lli/oandbackupx#144]
Hi!!

A long time ago I made an app called MLand based off of the aosp source.   Should I try and implement it? Perhaps by tapping something a few times or pressing something for a certain amount of seconds? 

If yes I have a few more ideas.  Thanks for your time

**Comment by machiav3lli** [comment]
Hello thanks for your suggestion, but we're trying to keep it as clean as possible providing the essential functionality only, therefore  I have unfortunately to decline your suggestion. I'll surely come back to this if we decide to add an Easter Egg.
