### ISSUE TITLE
[Feature Request] Bitcoin Donation Address

### ISSUE THREAD

**Issue by kennan-shivraj** [machiav3lli/oandbackupx#147]
**Is your feature request related to a problem? Please describe.**
Can't donate with privacy.

**Describe the primer solution**
Bitcoin Lightning donation possibility (might be difficult). This is not an altcoin.

**Describe alternative solutions**
Regular Bitcoin donation address.

Thanks for the great work. Latest update by Tiefkuehlpizze came just at the right time.

**Comment by machiav3lli** [comment]
Thanks for your interest. At the moment am not opening the project to donation, but I'll surely provide a privacy-friendly way when I choose to open it.
