### ISSUE TITLE
How is Nextcloud backup possible?

### ISSUE THREAD

**Issue by chaptergy** [machiav3lli/oandbackupx#15]
In the readme it says, oandbackupx can be combined with syncthing or nextcloud for remote backups. However how is it actually possible to push those backups to Nextcloud? The backup location is a custom folder picker, so I can't choose Nextcloud via the Storage Access Framework, so there is no way to use Nextcloud? I could only select a data directory of the nextcloud app, however since it doesn't use the framework nextcloud isn't notified of any changes, and my backups won't be uploaded.

Thanks!

**Comment by machiav3lli** [comment]
I think you could add your backup folder(default ./oandbackupx) to your Nextcloud instance and sync as in-place (will be scanned regularly). 

Anyhow, I'll be switching to the SAF as soon as I move to stable and add encryption. Thanks

**Comment by chaptergy** [comment]
Oh wow, I didn't even know Auto-Upload inside the Nextcloud app would upload more than photos and videos, great to know, thanks!
