### ISSUE TITLE
Background persistant / wake-lock blocking

### ISSUE THREAD

**Issue by rodrigoswz** [machiav3lli/oandbackupx#17]
Hi, firstly thank you for resurrecting and improving OAndBackup!

The biggest problem at the moment I am having with the app is that Android kills the backup process, perhaps this can be avoided by making a persistent notification when performing a backup.

And it would also be a good idea to request a battery optimization exception.

My device info:

- Xiaomi Mi 9T
- Android 10 (Pixel Experience+)
- Magisk v20.4 (Stable)
- OAndBackupX v0.9.8-arm64

**Comment by machiav3lli** [comment]
Do you use wake-lock blockers? Is it included in the ROM? If so try whitelist the app. But I'd possibly add the battery optimisatin's exception later.
