### ISSUE TITLE
[IDEA] add option to decide, if the old backup has be deleted before or after the creation of the new backup

### ISSUE THREAD

**Issue by Smojo** [machiav3lli/oandbackupx#173]
When multiple backups are enabled, it would eventually be interesting for some users to add option to decide, if the old backup has be deleted before or after the creation of the new backup.

No question, deleting the older backups afterwards is of course the safe way, but especially for those users who don't have an external sd card, free internal space might be very important.

**Comment by machiav3lli** [comment]
Closed in #174
