### ISSUE TITLE
Exclude cache from backup

### ISSUE THREAD

**Issue by chaptergy** [machiav3lli/oandbackupx#18]
It would be great if there was an option to exclude caches from the backups, since the cache usually does not include necessary / non-reproducible data, but instead tends to make the backups unnecessarily larger.
 This could be implemented by just ignoring the folders called `cache`, since this seems fairly standardized.

The next level would be to also include the ability for a per-app black- or whitelist, however this per-app setting is probably not necessary for most users.

**Comment by machiav3lli** [comment]
Actually I was planing to add it in the next release :)
