### ISSUE TITLE
[Bug] RestoreFailedException

### ISSUE THREAD

**Issue by mhous33** [machiav3lli/oandbackupx#187]
**Description**

OAndBackupX.log output:

RestoreFailedException: Could not restore a file due to a failed root command: mv: bad '/data/user/0/com.machiav3lli.backup/cache/restore_2317834073835778919/shared_prefs': Operation not permitted

**Steps To Reproduce**
1. Compile latest source
2. Backup apk and data
3. Restore the backup
4. Backup restores successfully, yet throws the above error

**Expected behavior**
Restore backup without throwing an error

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**
 - Device: Moto G Power
 - Android Version: 10
 - ROM: (AOSP, MIUI, OOS...)  OEM, OMNI
 - App's Version: 4.0.0

-------------------------------
**Additional Notes**
* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly.
* If you're on the latest github version. Please read all the open Issues if one does match yours, leave a comment there if there's some extra information you can provide.
* If you're not on the latest github version(happens sometimes with F-Droid version), please read all of the open issues and also some of the latest closed issues.

Thanks for reporting

**Comment by machiav3lli** [comment]
Do you know on what app that was?

**Comment by mhous33** [comment]
> Do you know on what app that was?

Okta Verify

**Comment by nicorac** [comment]
I have the same error when restoring FDroid 1.9 and on my Redmi Note 9 Pro (Android 10).

OAndBackupX 4.0.0 installed with FDroid.
