### ISSUE TITLE
backup/restore from cloud support

### ISSUE THREAD

**Issue by soredake** [machiav3lli/oandbackupx#19]

**Comment by machiav3lli** [comment]
That'll change a huge chunk of the code base and so it's planned for a later release (maybe 2.0.0).

**Comment by karlicoss** [comment]
I'm using [syncthing](https://github.com/Catfriend1/syncthing-android) with the current oandbackup, works quite well. 
I'd imagine 'native' cloud support with so many providers and f-droid policies is going to be painful?

**Comment by machiav3lli** [comment]
Yes, it'll have the whole backend code base changed. That's why it'll be the mostly in summer when I'd have time for such a work. Still I's considering adding a shortcut to adding the folder to the Syncthing profile, through an Intent, I'll have to check the Syncthing code first.

**Comment by mat-l** [comment]
Bachup and restore from and to Nextcloud would be awesome 😍

**Comment by machiav3lli** [comment]
See #15 please

**Comment by Mibo5354** [comment]
You could use rclone as a backend for cloud support

**Comment by soredake** [comment]
Sorry, but cloud support is not added, pls reopen.
![Screenshot_20201107-105709_Files](https://user-images.githubusercontent.com/5204968/98437055-10208400-20e8-11eb-9755-c6e6fa7fbef4.png)

**Comment by Tiefkuehlpizze** [comment]
What do you expect from a cloud support? How can it be fulfilled?

**Comment by soredake** [comment]
![Screenshot_20201107-112350986](https://user-images.githubusercontent.com/5204968/98437565-d3ef2280-20eb-11eb-9ddf-cc92ec17a7df.jpg)
I expect something like this, if this is not real then mark this issue as won't fix.

**Comment by machiav3lli** [comment]
If your cloud service provider adds the provider using android's standard StorageProvider API you should be able to use it normally, if you don't have the provider then not. There's no plan to add custom cloud providers.

**Comment by soredake** [comment]
> android's standard StorageProvider API 

This?
![photo_2020-11-07_19-02-06](https://user-images.githubusercontent.com/5204968/98447265-1173a000-212c-11eb-91bf-121e27a83faa.jpg)

**Comment by machiav3lli** [comment]
@soredake rhetorical yes

**Comment by soredake** [comment]
As of latest version, 8.0.3-alpha1 i can't select cloud as backup location, can someone reopen this?

**Comment by machiav3lli** [comment]
@soredake Can you please provide more information, as we didn't change anything that would directly effect SAF. Otherwise are you sure that it's not rcloud/rcx that is missing support on A12+, at least I recall some users in the group reporting, that rcx got roasted in A12+

**Comment by soredake** [comment]
There are still no plans to add direct cloud support in neo backup?

**Comment by machiav3lli** [comment]
@soredake No, we're not going to reinvent the wheel (not like we can), there's already apps specialized in providing such functionality e.g. rcx/rcloud, when they fail to deliver I don't see why we should try to do it ourselves. This project is about providing a backup tool and not a cloud mounting tool.
Otherwise you didn't provide any info, to help to see where the issue is!

**Comment by cipitaua** [comment]
I suggest to use [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite) to sync some folders to the cloud or to sftp/ssh or others.
