### ISSUE TITLE
Can't backup (or restore ?) special backups

### ISSUE THREAD

**Issue by Salamandar** [machiav3lli/oandbackupx#193]
I backuped and restored : 
* accounts
* wifi
* bluetooth

None of the above were really restored. I didn't have any warning or error during backup or restore.

**Comment by Tiefkuehlpizze** [comment]
I'm unsure about accounts. It never worked as well as bluetooth never worked for me.
Wifi should work on the same Android versions. Android 11 changed it again, but after special backups you also need to reboot the device.

So can you please provide the full information about your setup?

**Comment by Salamandar** [comment]
I'm going to try again on LineageOS and tell you about wifi. I'm sure about the issue with accounts and bluetooth but I may have made a mistake about wifi.

**Comment by Salamandar** [comment]
OK, I've had boot loops (it shows the lock screen a second then crashes) with multiple ROMs these days. I finally pinpointed the issue to the restoration of… one of the "special" backups.
I don't know if the issue is with the backup itself of the way it's restored by OABX.

**Comment by machiav3lli** [comment]
Migrating most of the special data is generally not a good idea, more to thatas you can see in the DevDoc.md the support for special backups is still not marked as reached. For those two reasons it's included in the advanced settings and not other where.

**Comment by Salamandar** [comment]
OK, so let's not rely on this.
Uh, it's not in the advanced settings. I didn't have to enable them to do the special backups.

**Comment by machiav3lli** [comment]
Yeah... That slipped through without me knowing of it, got fixed in the later test versions.

**Comment by machiav3lli** [comment]
#252 is a cleaner one

**Comment by Salamandar** [comment]
@machiav3lli good catch.
