### ISSUE TITLE
[Bug] "Start Backup now" button broken, it doesn't do anything

### ISSUE THREAD

**Issue by ioogithub** [machiav3lli/oandbackupx#197]
**Description**
Start Backup Now button is broken, nothing happens when pressed.

**Steps To Reproduce**
1. Open oandbackupx
2. Tap red alarm click button
3. New list is created, tap: "All apps"
4. Tap "Custom list"
5. Tap "Update custom list"
6. Tap any app from the list, tap ok
7. Tap "Start Backup Now" button
8. Confirmation displayed "Start backup now?" Tap "ok"

Nothing happens, no backup is started.

**Expected behavior**
The app should start to backup the items on the list.

**System Information(please complete the following information):**
 - Device: Moto G7Plus
 - Android Version: 10
 - ROM: LineageOS 17  
 - App's Version: 3.2.0

**Comment by ioogithub** [comment]
I thought maybe it was the "Custom list" filter was preventing the button from working. I have tried running test with a  few different options:

Under backup mode:
-New and updated apps
-User Apps

Under sub-mode:
-APK, Data, APK and Data

None of the options make any difference, I believe it is the "Start Backup Now" button itself that is broken.

**Comment by machiav3lli** [comment]
As the notice in new issue example points out, please check if the error exist in the latest release which's right now 4.0.0. Thanks.

**Comment by ioogithub** [comment]
I will check it out. Where can I find the 'notice in new issue example'?

Do you know if the new version has been released to F-Droid yet?

**Comment by darhma** [comment]
@ioogithub new version 4.0 is on f-droid: OAndBackupX (Your open-source tool to backup your apps ... and their data) - https://f-droid.org/packages/com.machiav3lli.backup
