### ISSUE TITLE
[Bug] Cannot restore backups

### ISSUE THREAD

**Issue by Xastu** [machiav3lli/oandbackupx#198]
**Description**
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{b049ba8 15961:com.machiav3lli.backup/u0a401} (pid=15961, uid=10401) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

I honestly haven't the slightest clue why it's affecting me. Am I missing some kind of dependency?
To be clear this was attempting to restore from a backup apk or data, it says it can't find it. In logcat that bunch of text pops up and then another entry says it's found and then the next entry says to display the failed message.

![Screenshot_20201105-010815773](https://user-images.githubusercontent.com/32784779/98204214-9af45980-1f03-11eb-9061-efffe4684c62.jpg)
![Screenshot_20201105-010912775](https://user-images.githubusercontent.com/32784779/98204215-9af45980-1f03-11eb-8850-ee198342f0a0.jpg)

The apk is in there and it does install like it should

**System Information(please complete the following information):**
 - Device: OnePlus 6T
 - Android Version: 10
 - ROM: PixenOS some backups are from an official build with magisk
 - App's Version: whatever the latest is as of posting, I believe 4.0

**Comment by rradar** [comment]
I have reproduced the exact same bug

**Comment by machiav3lli** [comment]
The same as #204 should apply

**Comment by jomo** [comment]
Probably related to #214, which fails with the same error message.

**Comment by machiav3lli** [comment]
Read the closing note in #204
