### ISSUE TITLE
Include Device encrypted storage (/data/user_de/) in backups

### ISSUE THREAD

**Issue by gamax92** [machiav3lli/oandbackupx#2]
Some applications store some data in this path, OAndBackupX should also save that data too
There was a pull request for the upstream code that the original author didn't look at, maybe it could be included in this fork?
https://github.com/jensstein/oandbackup/pull/267

**Comment by machiav3lli** [comment]
This should be relative easy, as the changed files from the commit weren't rewritten fully. I'll do my best as soon I get time for such a change. Thanks
