### ISSUE TITLE
the app crashes after backing up an app in the latest version.

### ISSUE THREAD

**Issue by talk2g** [machiav3lli/oandbackupx#20]
arm64 version

**Comment by machiav3lli** [comment]
Everytime/sometimes and on a specific app/ or sometime this app sometime another one? Could you provide a log? For when this happens

**Comment by talk2g** [comment]
on the first backup it works perfect,
on second, it mostly reloads/refreshes and sometimes "stops working"
on third try 99% of time it "stops working"
happens for any app i backup
can point me to a guide for providing u the desired log?

**Comment by talk2g** [comment]
https://del.dog/tulihyluly
here the app crashes after i backup only 1 app

**Comment by talk2g** [comment]
https://del.dog/fosawitteg
reloads after first backup
crashes after 2nd backup

**Comment by machiav3lli** [comment]
Thanks, but those logs provide only that the restarted, I think I'll have to do some more debugging on my side. Thanks again for reporting.

**Comment by talk2g** [comment]
Happy to help dude, since this is the only foss app for backup.
Keep up the good work

**Comment by machiav3lli** [comment]
So, I've been logging hundreds of backup, restore, delete backup and uninstall app for the last couple of hours and - some how - sadly couldn't reproduce any types of crash. Maybe the crashings has to do with the differences in the logs(as the provided logs imply).

Would you maybe try to renew your backups: delete the old ones through the app while having the apps - with the data you want - installed on the device then redo the backups (apk or both respectively).

This latest version was planned to be the 1.0.0, but I wanted to give it time, roughen some edges and check if there's bugs or if some crashes could happen and if I may catch them(now we know it didn't work). That said, you're encoureged to test all the functionalities of the app.

**Comment by talk2g** [comment]
i m still facing the issue
1) most of the times , the app refreshes after doing a backup.
is this The intended behaviour?
2) About the crashes, maybe it is an isolated event, i will check back on one of my other device and report it back later today.

**Comment by machiav3lli** [comment]
How frequently? 
When the view list is empty then it should refresh the adapter list(not the app as whole) and some other situations.
As said, I spent hours trying to reproduce it but failed. Please consider documenting the crashes(the app, how many apps was to be seen in the list, using filter?, using search?, app had already a backup) or maybe a screenrecord could help me to reproduce it. Thanks again

**Comment by talk2g** [comment]
sure will do.

**Comment by tsiflimagas** [comment]
I get such app restarts and closes with the same error too. I had a big number of apps backed up with oandbackup which I just pasted to oandbackupx folder(or I could have just added an "x" at the end of the old folder's name xD). I'm guessing it's because of this exact reason, that backups weren't made with oandbackupx. I just don't know if this should be considered a bug, a compatibility issue which can be resolved or a misuse.

Btw, it doesn't seem to always happen and not systematically. Seems more like a random thing. And never happened on backup function apparently, only when restoring.

**Comment by talk2g** [comment]
i tested it on my other device and it works perfectly fine there..
Looks like an anomaly on my first device.
I can still document and screenrecord if u want ,but i dont think thats necessary.

worth noting that i get crashes on my MI A1 running android pie with microg
and other one is running android Q (Pixel experience)
which i dont think have anything to do with it.

**Comment by machiav3lli** [comment]
Maybe I should document how compatible the app with old one. For now, the last version that should be fully compatible with oandbackup is the 0.9.3. In 0.9.4 and 0.9.11 there's some backup/restore logic changes. Thanks for you co-operation

**Comment by tsiflimagas** [comment]
So today I made a full restore with the old oandbackup to do a full backup with oandbackupx. When backing up I got a lot of force closes. Here's the log I got https://del.dog/meliserini

**Comment by machiav3lli** [comment]
Yeah, the crash is happening in the app list's adapter. I'll see to it as soon as I can.
