### ISSUE TITLE
[Feature Request] Add back nougat support (Android 7)

### ISSUE THREAD

**Issue by rradar** [machiav3lli/oandbackupx#202]
**Is your feature request related to a problem? Please describe.**
Just found out the hard way that nougat support was dropped somewhere between v3 and v4

**Describe the primer solution**
Add back support for android 7 which still running on around 10% of all the billions androids out there

**Describe alternative solutions**
Id really like to avoid running different versions on different devices as it doesn't allow to restore all backups on all devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/34582688/98444456-b3ce5c00-2109-11eb-8284-a62c3a8af2ae.png)
Source: https://www.appbrain.com/stats/top-android-sdk-versions

**System Information(please complete the following information):**
 - Devices: various
 - Android Version: 7.1
 - ROM: AOSP, Omni, LineageOS

-------------------------------
**Additional Notes**
* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please write it there directly.
* If you're on the latest github version. Please read all the open Issues if one does match yours, leave a comment there if there's some extra information you can provide.
* If you're not on the latest github version(happens sometimes with F-Droid version), please read all of the open issues and also some of the latest closed issues.

Thanks for your suggestion

**Comment by machiav3lli** [comment]
Duplicate #171
