### ISSUE TITLE
data restore failed: data.tar.gz.enc is missing

### ISSUE THREAD

**Issue by SHGuy1** [machiav3lli/oandbackupx#204]
I installed the app through f-droid and made a backup of whatsapp with data backup and encryption enabled.

I can't restore the data and get the following error/exception:
```
RestoreFailedException:
Backup archive at content://com.android.externalstorage.documents/tree/3936-6233%3Aapp_backups/document/3936-6233%3Aapp_backups%2FOABackupX%2Fcom.whatsapp%2F2020-11-08-23-36-21-user_0%2Fdata.tar.gz.enc is missing
```

I've chosen a folder on my sd card as the backup folder if that's important.

The corresponding folder has the following files:
```
base.apk
data.tar.gz.enc
```

Android Version: 10

**Comment by machiav3lli** [comment]
This could mean most usually that the backup props file is corrupted. Try to create a new backup with the same mode and ecyption password then replace the data folders and/or apk.

**Comment by ioogithub** [comment]
Is this path correct?

Backup archive at content://com.android.externalstorage.documents/tree/3936-6233%3Aapp_backups/document/3936-6233%3Aapp_backups%2FOABackupX%2Fcom.whatsapp%2F2020-11-08-23-36-21-user_0%2Fdata.tar.gz.enc is missing

**Comment by machiav3lli** [comment]
@ioogithub You're not telling us that this is the backup directory you're choosing, right?

**Comment by machiav3lli** [comment]
This error is fixed in latest test builds and the repo. It's just that before, the directory to backup .apk and data was saved in the backup props meaning that if this is changed from device to device, the restore isn't possible.
