### ISSUE TITLE
[Bug] INSTALL_FAILED_INSUFFICIENT_STORAGE

### ISSUE THREAD

**Issue by apbucaneg** [machiav3lli/oandbackupx#206]
**Description**
Getting error when restoring Genshin Impact

**Steps To Reproduce**
First time encountering this, I've used OandBackupX before and I've been able to restore apps with no problems

**Screenshots**
![Screenshot_2020-11-10-21-08-18-051_com machiav3lli backup](https://user-images.githubusercontent.com/74248512/98678789-12116e00-239a-11eb-9802-7947aac74a49.jpg)

**System Information(please complete the following information):**
 - Device: Redmi Note 9 Pro Global joyeuse
 - Android Version: 10
 - ROM: MIUI 12
 - App's Version: 4.0.0

**Comment by machiav3lli** [comment]
This is a clear message that there's no sufficiant storage for the files. Why it's different to 3.2.0, it's because the app caches the data to be backedup and though, you'll need double the free storage of your data for doing backups and restores.

**Comment by apbucaneg** [comment]
> This is a clear message that there's no sufficiant storage for the files. Why it's different to 3.2.0, it's because the app caches the data to be backedup and though, you'll need double the free storage of your data for doing backups and restores.

I'm coming from a newly updated phone though, plenty of space

**Comment by machiav3lli** [comment]
Other explanation could be that the app has symlinks/special files that have a cyclic dependency, causing full usage of the storage. Did it take long for it to cause the error message?

**Comment by machiav3lli** [comment]
One of the testers had this problem initially, yesterday he pointed out that he got it fixed with disabling MIUI  Optimizations.

**Comment by apbucaneg** [comment]
Oh, must be a MIUI thing in handling split APKs. Thanks for this!
