### ISSUE TITLE
[Bug] NavBar: more info on Updated-Badge long-tap

### ISSUE THREAD

**Issue by LondoJI** [machiav3lli/oandbackupx#208]
**Description**
OandBackupX's main toolbar is showing a notification in number over apps list icon, which I ignore what is referring to. If I tap that icon, of course app shows apps list. A long tap over it hasn't any effect, farther than give the same result as a simple tap, and giving the message "OandBackupX".

**Steps To Reproduce**
1. ... Open OandBackupX
2. ... A number is shown over apps list icon, but there isn't any info I could get to know what is trying to tell.
3. ... Tap or long tap over that icon, just goes to app list. Not possible to know what is this number trying to advise.

**Expected behavior**
Should be a way to read what these notifications are trying to tell. Probably adding a long tap over apps list icon.

**Screenshots**
![Screenshot_20201110-200508](https://user-images.githubusercontent.com/25232694/98750180-2d3da700-23b5-11eb-9072-ebea1f146807.png)

**System Information(please complete the following information):**
 - Device: Xiaomi Mi A1
 - Android Version: 10
 - ROM: DerpFest 10 (20201012)
 - App's Version: 4.0.0

-------------------------------
**Additional Notes**
* This could lead to a feature request in order to implement long tap behavior over toolbar icons, or even other selectable elements such apps. to get some context menu options, or popup info.
* OandBackupX 4.0.0 (GitHub)

**Comment by machiav3lli** [comment]
The badge stands for the updated apps that are to be seen in the main tab.OAndBackupX stands for the main page.
Maybe I'll let't list the names of the updated apps. Thanks for the notifying.

**Comment by machiav3lli** [comment]
More info has been added to the help sheet on the new version 5.0.0.
