### ISSUE TITLE
"prompt for battery optimization exclusion "doesnt take you to the batter optimization setting

### ISSUE THREAD

**Issue by talk2g** [machiav3lli/oandbackupx#21]
doesnt do anything when i click it.

**Comment by machiav3lli** [comment]
Do you get any toast that the device doesn't support it?
Please provide your Android version and system (MiUI, OneUI ...)

**Comment by talk2g** [comment]
nope, it prompts me to the option by asking for permission.
android-9.0 
system- lineage with microg

**Comment by talk2g** [comment]
EDIT- looks like it automatically grants itself the permission without user input when accepted unlike most of the apps i have seen.
Closing the issue.

**Comment by machiav3lli** [comment]
Yes, It'll do it directly, this way isn't compitable with Golag Play standards, but I'm not planing to add it there anyway.

**Comment by talk2g** [comment]
this is more convinient since the user doesnt have to manually make the change
