### ISSUE TITLE
Kotlin, null strategy

### ISSUE THREAD

**Issue by hg42** [machiav3lli/oandbackupx#210]
If I start a backup, I immediately get an exception because of a `null` value.
In my case, this happened at `suCopyFileToDocument`, `createFile` returned null and the `!!` operator throwed an exception. I guess this code was created by the Java->Kotlin conversion?
I am not sure if Java handled this particular situation differently, may be an `IOException` was thrown instead of returning `null`.

I see `!!` in many places, which throws an exception, if the value is null.

I think, there should be a general decision, how `null` should be handled.
Should we use exceptions or constructs like `?.` or `?:` and some other machinery?

I also think, there should be a general catch (logging an error) for each app in the loop to continue backup or restore in cases when something unexpected happens (like these null values). The notification should be cleared in this case...

Error handling without exceptions would need an additional concept.

What do you think?

**Comment by machiav3lli** [comment]
Joa... you got it right, I was aiming to reduce Nullables as far as I can and then act on produced exceptions. I agree that ?/?: are more concise and reasonable. For now I'm still working on cleaning up the code of deprecated classes and introduce multi threading to refresh.

As soon as I finish this, I'll start working on VMMV and then I can meet a decision. Is it ok if we push this to a later time?

Meanwhile there's this bug which consumed hours of debugging and wasn't solved. It could be great if you can take a shotat it and I'm there, for any deeper grade of details.
```kotlin
for (file in appBackupDir.listFiles()) {
                    // TODO FIX: Randomly failing to read properties files of the updated app on refresh
                    //  but never on start!! Already. One thing to be noticed is that on some random
                    //  times those calls run on different threads even though they shouldn't and this
                    //  never happens on first launch
                    if (file.isPropertyFile) try {
                        backupHistory.add(BackupItem(context, file))
```

**Comment by hg42** [comment]
> Is it ok if we push this to a later time?

sure I only wanted to discuss the strategy and may be what you are doing on your side, before I do things that don't fit.

Will have a look at the bug tomorrow...
is there an issue for that?

hmm, I guess, because I get a crash on each backup, I cannot test such things...
I assume, you can already do backups, so perhaps you can push some of your code (especially fixing null) for me?

**Comment by hg42** [comment]
just a notice, I uninstalled OABX and cleared the backup directory and after granting all rights the backup runs...
so not sure which one and why...next time I do this in two steps...

and it just crashed at webview...
I now have `OABackupX` and `OABackupX (1)`, the latter is empty...

and I forgot to change my usual settings...will continue tomorrow....(too much beer :-) )

**Comment by machiav3lli** [comment]
@hg42 no problem. It can take the time it needs. We're in no hurry.
