### ISSUE TITLE
Cannot restore on LineageOS 17.1 (Android 10)

### ISSUE THREAD

**Issue by Chris56** [machiav3lli/oandbackupx#212]
LineageOS 17.1
F-Droid version of oandbackupx 4.0.0

On 
/sdcard/OABackupX/
there is a backup at.bitfire.davdroid, which oandbackupx finds.
When you want to restore (both data and apk, which both exist), then

logcat:
11-11 06:34:16.904 13743 14973 I OAndBackupX.RestoreAppAction: Restoring up: at.bitfire.davdroid [DAVx⁵]
11-11 06:34:16.905 13743 14973 I OAndBackupX.RestoreAppAction: [at.bitfire.davdroid] Restoring from /tree/primary%3AOABX/document/primary%3AOABX%2FOABackupX%2Fat.bitfire.davdroid%2F2020-11-11-06-12-20-user_0
11-11 06:34:16.916  2659  6880 E InputDispatcher: Window handle Window{a11019e u0 com.machiav3lli.backup/com.machiav3lli.backup.activities.MainActivityX} has no registered input channel
11-11 06:34:16.921  2686  2686 W android.bg: type=1400 audit(0.0:1280): avc: denied { read } for name="13743-0" dev="debugfs" ino=83401 scontext=u:r:system_server:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=0
11-11 06:34:16.930 13999 14967 E DatabaseUtils: Writing exception to parcel
11-11 06:34:16.930 13999 14967 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3AOABX/document/primary%3AOABX%2FOABackupX%2Fat.bitfire.davdroid%2F2020-11-11-06-12-20-user_0 from pid=13743, uid=10137 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at com.android.externalstorage.ExternalStorageProvider.enforceReadPermissionInner(ExternalStorageProvider.java:134)
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
11-11 06:34:16.930 13999 14967 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
11-11 06:34:16.931 13743 14973 W OAndBackupX.DocumentContractApi: Failed query: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3AOABX/document/primary%3AOABX%2FOABackupX%2Fat.bitfire.davdroid%2F2020-11-11-06-12-20-user_0 from pid=13743, uid=10137 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
11-11 06:34:16.931 13743 14973 D OAndBackupX.RestoreAppAction: [at.bitfire.davdroid] Found base.apk in backup archive
11-11 06:34:16.921  2686  2686 W android.bg: type=1300 audit(0.0:1280): arch=40000028 syscall=322 per=8 success=no exit=-13 a0=ffffff9c a1=b896157c a2=20000 a3=0 items=0 ppid=2422 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 ses=4294967295 tty=(none) exe="/system/bin/app_process32" subj=u:r:system_server:s0 key=(null)
11-11 06:34:16.921  2334  2334 W auditd  : type=1327 audit(0.0:1280): proctitle="system_server"
11-11 06:34:16.921  2334  2334 W auditd  : type=1320 audit(0.0:1280): 
11-11 06:34:16.935 13743 14973 I OAndBackupX.BackupRestoreHelper: at.bitfire.davdroid: Restore succeeded: false

and the restore fails.

I guess the
"requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs" (see above)
will be the problem ...

Also on the same ROM: backup to the exteranal sd card fails (even though the data gets created). I guess that will be the same problem with the file access. Note: permission for access had been granted before.

Cheers,
Chris

**Comment by Chris56** [comment]
Probably the same as #198.
The files aren't corrupt. The do exist and you have the access permissions.
Probably the file access method must be different (see above)

**Comment by machiav3lli** [comment]
It's actually more connected to #214 .
One thing to check: do you have play store or your ROM is updated in the last 2/3 months?

**Comment by machiav3lli** [comment]
Could you please check the just-released 5.0.0 and report back, thanks.
