### ISSUE TITLE
[Bug] App data restore causes a force close of restored app upon launch.

### ISSUE THREAD

**Issue by dhammel** [machiav3lli/oandbackupx#213]
Im using a google pixel 4 android 11 aosp october update. Magisk 21.0 beta. Root granted. OAndBackupX Version 4.0.0 official fdroid repo. I have tried all options availible in app when performing a backup (such as including and excluding cache).

Whenever i restore an app (apk+data) (occurred to any app i've tried, such as SAI (Split apk Installer gotten originally from fdroid.)), the apk installs just fine but when launching app, it force closes. Only fixed by clearing app data, which as I wanted to restore app data as well, this obviously isnt a solution for me. App data restores just fine with TitaniumBackup.

Ive tried to get logs, but just displays a msg saying Theres nothing to show.

**Comment by machiav3lli** [comment]
There's some app's that use android's keystore, keeping their "secrets" there and those can't be really extracted, as they're worthless on other setups(other ROM, other Device, other setup time... you get where I'm going). Another prominente example is Signal.

**Comment by Soundtoxin** [comment]
I had this problem with Element and had to clear its data, but all my other apps seemed to restore fine, including Conversations, which has OMEMO keys.

**Comment by dhammel** [comment]
Well this occurs for any restored app, including ones not using keystore such as SAI as mentioned. I know a lot about the keystore but even apps like AEGIS (2fa management app) that uses it can be restored with TitaniumBackup, however you would need to re-register the Biometic aspect of it. TitaniumBackup restore signals app data resorts in same issue, but thats the only app which ive ever encountered this issue for with other backup apps.

The main issue is that app data restore of ANY app causes restored app to force close upon launch, regardless of keystore usage.

**Comment by machiav3lli** [comment]
@dhammel are the systems you've done your backups on and tried to restore differ?

Even if those differ (e.g. A10>A11) most testers and users reported fully working . Could you please give more context on the build up of your system and backup/restore process.

**Comment by dhammel** [comment]
I was really only testing to ensure that oandbackupx works before switchjng from TitaniumBackup. So i backed up some apps woth TitaniumBackup, uninstalled them locally and tried restore with oandbackupx, same device, same os version. Unforunately, I dont have another device to test on. I could try though an AVD, but I assume thats working otherwise you'd probably be able to reproduce it.

**Comment by machiav3lli** [comment]
So, I got it. The problems lies in the SELinux permissions as those are not managed correctly. For now, changing SELinux to permissive should be enough to fix the situation. A fix, will mostly come in one of the coming minor releases.

**Comment by CrawX** [comment]
I'm facing the same issue and can confirm that disabling selinux (using https://github.com/evdenis/selinux_permissive) seems to work. Is there a branch or something with the selinux fix that I can try? Will it also work with backups taken with 5.0?

Cheers

**Comment by machiav3lli** [comment]
@CrawX nope, there's no fix for it as of now. But hopefully in the future.
