### ISSUE TITLE
[Bug] Backup folder location permission does not persist

### ISSUE THREAD

**Issue by jomo** [machiav3lli/oandbackupx#214]
**Description**
Whenever I open OandBackupX after a reboot, I need to select the backup folder again. I chose a folder on the internal storage and confirm `Allow access to '$folderName'`. The Backup folder is then set to `content://com.android.externalstorage.documents/tree/primary/%3AfolderName/document/primary%3AfolderName`.

Apparently the app loses the access permission for the folder after a reboot:

```logcat
W OAndBackupX.DocumentContractApi: Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{…} (pid=…, uid=…) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
```

Is this happening because [`takePersistableUriPermission(Uri, int)`](https://developer.android.com/reference/android/content/ContentResolver#takePersistableUriPermission%28android.net.Uri%2C%2520int%29) is not called on the `ACTION_OPEN_DOCUMENT_TREE` intent?

From the documentation:

>Take a persistable URI permission grant that has been offered. Once taken, the permission grant will be remembered across device reboots.

I assume that means *not* taking the permission grant means it will *not* be remembered across device reboots.

**Steps To Reproduce**
1. Select backup folder
1. reboot
1. Open the app
1. You need to select the backup folder again

**Expected behavior**
OandBackupX should persist its backup folder permission

**System Information(please complete the following information):**
 - Android Version: 10
 - ROM: LineageOS 17.1
 - App's Version: 4.0.0

**Comment by jomo** [comment]
Oh, it's probably also a good idea to warn about permission issues in a notification. Otherwise such errors could go unnoticed for a long time.

A quick glance at the code suggests that permission errors are silently ignored (there is no `else` block):

https://github.com/machiav3lli/oandbackupx/blob/1fb0df278b1186072e739e3d05bb234be297237c/app/src/main/java/com/machiav3lli/backup/schedules/HandleScheduledBackups.kt#L95-L96

**Comment by machiav3lli** [comment]
On the main topic. The app already follows android's latest development guidelines to get the access permission, but the system seems to handle it since release of A11(and update of StorageManager Apex) otherwise.

But yeah, it could be that  <code>takePersistableUriPermission(Uri, int)</code> is the missed part. I'll try it as soon as I come to it on the TODO list.

**Comment by ioogithub** [comment]
I just noticed that part of the path stored under "Backup folder" in settings is duplicated. If you select it again it will be fixed but every time you close the app and start it again, the path becomes duplicated. Perhaps this is why it crashes?

**Comment by machiav3lli** [comment]
@ioogithub how duplicated?

**Comment by jomo** [comment]
When you take a look at the backup folder location in settings immediately after setting it, it's set to

`content://com.android.externalstorage.documents/tree/primary/%3AfolderName`

When you then leave the settings and open them again, it's set to

`content://com.android.externalstorage.documents/tree/primary/%3AfolderName/document/primary%3AfolderName`

**Comment by ioogithub** [comment]
Yes this is what I see too, the path is messed up, part of it is duplicated. After it is selected initially it is correct, after you leave the settings screen part of the path is duplicated. Could this be the bug that is causing it to lose it's backup location and also to crash after you select it again?

**Comment by machiav3lli** [comment]
@jomo the messed up address you see is more or less a bloated placeholder.
Latest test build fixes the persistant storage permission.
@ioogithub The address has probably nothing to do with your crashes. You still didn't provide any logs.

**Comment by machiav3lli** [comment]
@jomo the messed up address you see is more or less a bloated placeholder.
Latest test build fixes the persistant storage permission.
@ioogithub The address has probably nothing to do with your crashes. You still didn't provide any logs.

**Comment by ioogithub** [comment]
> @ioogithub The address has probably nothing to do with your crashes. You still didn't provide any logs.

I would like to provide logs but inside the app it always says: 

There's nothing to show in the log.

Are you storing the logs externally somehwere, if so where can I find them?

**Comment by machiav3lli** [comment]
@ioogithub Already told you on the other thread that I've already wrote you in the telegram group three options to create the log needed. This is the third time I repeat this and you show no remorse.

**Comment by ioogithub** [comment]
I am a new to telegram. I think I may have missed your instructions about how to take a log.

Sorry for my lack of remorse, I am not at the expert or developer level. I really liked the original oandbackup and used it successfully. I am glad someone has taken over the project but I am just a user who is trying to use your app to take a backup of my files.

> Latest test build fixes the persistant storage permission.
I look forward to trying the new version.

**Comment by machiav3lli** [comment]
@ioogithub sorry, I didn't mean it to be seen as offensive. You were just writing about having the "same" crashes all over the place (in the issues) but didn't respond to this single point which I wanted you to act upon. Lastly I didn't mesn you as a person but your actions when I spoke about remorse. I repeat my sorry if it was offensive and hope you accept it.

To build a better app we need to work togeather and for that, it's essential that we stay in direct communication and try to solve each raised issue alone and not mix'em togeather.

**Comment by jomo** [comment]
> Latest test build fixes the persistant storage permission.

Thanks for the quick fix @machiav3lli! Happy to test this once a new build is out.

---

PS: I found the [small, actual fix](https://github.com/machiav3lli/oandbackupx/commit/eb9a252bf7164d92b1fc8dcae9a0af6f1e796d39#diff-b5f31f944e5585842dbd2dd40eba921605aadc96fd44ed43ec9373ceee242083R166) a bit hard to find in the huge (and otherwise unrelated) "Clean up & Adopt Kotlin style" commit (eb9a252bf7164d92b1fc8dcae9a0af6f1e796d39). I assume you were half-way through changing the Kotlin style when you added this? If you run into something similar in the future, you could make use of `git add -p`, which allows you to add some lines of a file for a commit and leave other lines uncommitted for later, to keep your commit history clean :)

**Comment by machiav3lli** [comment]
@jomo yeah thanks. In fact I done that as I didn't have that much of time to do clean commits, so sorry for this complicatation.

**Comment by dvzrv** [comment]
@machiav3lli would it be possible to release this fix in a new version? :) 

I'm currently unable to restore any backups :-/
Thanks! :)

**Comment by machiav3lli** [comment]
@dvzrv A stable release isn't ready, so you can use the latest test build from our group.
