### ISSUE TITLE
[Bug] No notification or any indication after "Start Backup Now" is pressed

### ISSUE THREAD

**Issue by ioogithub** [machiav3lli/oandbackupx#216]
**Description**
Oandbackupx is not showing any backup status notifications after  the "Start Backup Now" button is pressed. To the user it appears that the button failed because there is no notification on the screen and no system notification.

**Steps To Reproduce**
1. Create a schedule backup task
2. Tap "Start Backup Now"
3. It appears that nothing is happening (this button did not work in version 3.2.0) but that is not what is happening now.
4. Access the folder backup location in a file manager.
5. You can see that new backups are present here.

The problem is that oandbackup is running but it didn't register a notification or any message on the screen so you can't see that it is actually running or what the status of the back up jobs are.

**Expected behavior**
Once the Start backup now button is pressed, the user should see a notification regarding the backup progress- either a message on the screen "Backing up" or a message in the system notification tray "Backing up x app" etc. Some sort of indication that the app is working.

System Information(please complete the following information):
    Device: Moto G7Plus
    Android Version: 10
    ROM: LineageOS 17
    App's Version: 4.0.0 (f-droid)

**Comment by machiav3lli** [comment]
There's a notification to handle the communication of the result. The scheduled backups run in the background not in the foreground of the app, meaning a communication with app's UI isn't possible.

**Comment by Atrate** [comment]
@machiav3lli At least in 4.0.0 the notification is non-persistent meaning it can easily be swiped away accidentally. Is it possible for that to be changed into a persistent one?
