### ISSUE TITLE
[Bug] Empty backup folders not deleted after "Delete all backups button" operation

### ISSUE THREAD

**Issue by ioogithub** [machiav3lli/oandbackupx#217]
**Description**
If an app is backed up then the "Delete all backups" button is pressed. Oandbackupx does delete the apk file and associated files but it does not delete the folder, leaving empty folders. After a while the backup location will be messy.

**Steps To Reproduce**
1. Backup an app
2. Tap on the all and select "Delete all backups"
3. Open a file manager, observe that the backup files were deleted but the empty folder was left behind.

**Expected behavior**
Empty folders should be deleted if there are not backup files left to keep the filesystem clean.

**System Information(please complete the following information):**

    Device: Moto G7Plus
    Android Version: 10
    ROM: LineageOS 17
    App's Version: 4.0.0 (f-droid)

**Comment by machiav3lli** [comment]
This is already present since days in the code and in tonight's 4.0.1-alpha1.
