### ISSUE TITLE
Bromite (Chromium fork) breaks when restoring data from oandbackup

### ISSUE THREAD

**Issue by gut5** [machiav3lli/oandbackupx#22]
Using oandbackupx 0.9.11-arm, it restores the data in Bromite 81.0.4044.127 but then the browser doesn't browse anymore. I can't open any site.

I should mention the data backup was made with oandbackup 0.3.5. 

(already reported this issue for oandbackup so apologies for the crosspost, but it also affects 
oandbackupx)

**Comment by machiav3lli** [comment]
Try the OAndBackupX 0.9.3 version to restore your old backup, if everything works fine update to latest and do new backups. As in the version 0.9.4 I changed some of the backup/restore logic to support protected data. Thanks for reporting.
