### ISSUE TITLE
[Bug] (minor annoyance) menu returns to main screen after action is completed from search result

### ISSUE THREAD

**Issue by garbb** [machiav3lli/oandbackupx#225]
**Description**
The menu returns to the main list of apps after completing an action on an app that is selected from search results. If completing an action on an app that has been selected from the app list without searching, it stays on the app's menu and does not return to the main app list.

**Steps To Reproduce**
1. Launch app to display main menu with list of apps.
2. touch in search box at top
3. type name of app to search for, ex "twitch"
4. list of apps that match search text appear below search box
5. touch an app in list of search results, ex "Twitch"
6. menu for selected app appears with options to backup, restore, delete backups that exist, etc..
7. touch button to perform an action (backup app, delete a backup, or restore an existing backup)
8. selected action (backup, restore, or delete) completes
9. display now changes back to menu for selected app with options (mentioned in step 6.)
10. after approximately 2 seconds, the screen returns to the main menu list of apps with the search box focused but cleared of all text

**Expected behavior**
After the selected action in step 8 (backup, restore, or delete) completes, I would expect/desire the screen to stay at the menu for the selected app (in example Twitch) instead of returning to the main list of apps with the search box/results cleared.

**System Information(please complete the following information):**
 - Device: Google Pixel 3
 - Android Version: 9
 - ROM: Stock
 - App's Version: 4.0.0

Other notes:
It appears that if the app is currently displaying search results and I switch to another app and then back to oandbackupx, then it will also clear the search results after about 2 seconds, I would expect the state of the app to be the same as how it was when it was switched away from.

**Comment by machiav3lli** [comment]
There was a crash caused by mixing onresume with not-aware-of-lifecycle activity and the solution was this hack. In the latest test version the activity is now lifecycle aware and this can be fixed.
