### ISSUE TITLE
[Feature Request] ability to create comment/note for backups

### ISSUE THREAD

**Issue by garbb** [machiav3lli/oandbackupx#226]
One feature of titanium backup that I used was the ability to set a note or comment for each backup. This helps in cases of testing different versions/mods of various apps. Not sure if others would find this feature helpful but I know I would.

Thanks

**System Information(please complete the following information):**
 - Device: Google Pixel 3
 - Android Version: 9
 - ROM: Stock
 - App's Version: 4.0.0

**Comment by machiav3lli** [comment]
Added for each app in 9bcd33697fa91afba0aa7d82d5c18eeb0dc87cad
