### ISSUE TITLE
[Feature Request] ability to restore only app data

### ISSUE THREAD

**Issue by garbb** [machiav3lli/oandbackupx#227]
Requesting the ability to only restore app data in addition to being able to restore apk only and apk+data. This can be useful for testing different data with different settings/account logins etc...

**System Information(please complete the following information):**
 - Device: Google Pixel 3
 - Android Version: 9
 - ROM: Stock
 - App's Version: 4.0.0

**Comment by machiav3lli** [comment]
Can you please elaborate more. The restore of data while having the app installed is already possible

**Comment by garbb** [comment]
Wow, i don't know how i missed that option...
Sorry...
Closing this...
