### ISSUE TITLE
[Bug] Restored App (Element) keeps crashing on start

### ISSUE THREAD

**Issue by NGantzhorn** [machiav3lli/oandbackupx#247]
**Description**
I cannot open Element (https://f-droid.org/packages/im.vector.app/) after it is restored (backup from same device).
After (successful) restore app wont open and crash instantly.

**Steps To Reproduce**
1. Install Element (former Riot.im)
2. log in to account (not sure if necessary)
3. Backup Element (data/apk, protected data & internal data)
4. uninstall and delete app data
5. Restore and start 

**Expected behavior**
App running with existing account

**Screenshots**
Logs are empty (cause of successful restore, I guess) and no screenshots to be taken.

**System Information(please complete the following information):**
 - Device: Moto G4 play (harpia
 - Android Version: 10.1
 - ROM: Lineage OS (microG), 17.1 
 - App's Version: 4.0.0 (from fdroid)

P.S.: 
Haven't read text of all issues, but no title seemed to fit. In addition I searched for some terms and didn't find anything related.

**Comment by machiav3lli** [comment]
Element like Signal, uses Android's KeyStore for credintals and so, it isn't possible to successfully restore. 

This category of apps has been discussed here on the issues before and there's already an entry in the known issues file. Will add the name later and point that out in the bug template. Thanks for your cooperation.

**Comment by NGantzhorn** [comment]
Okay, thank you.

Is there any method to know if a certain app uses Android's KeyStore, or do I just have to know it? If it is only Signal and Element, I can backup them separately, but if it is like much more that's not really handy.

**Comment by machiav3lli** [comment]
Usually it's used and checked by apps that use a certain way of locslly secure log in. There's a pattern on this... Signal, Element, SchildiChat.. But also banking (tan)apps  use it. So it depends on how secure an app should be for it to be used.

**Comment by darhma** [comment]
@NGantzhorn you can use AM Pre-release (a full-featured package manager and viewer) - https://f-droid.org/packages/io.github.muntashirakon.AppManager to see if an app uses keystore (generally the apps that requires to login)
