### ISSUE TITLE
[Bug] Failing to restore on Android 11 with release 4.0.0

### ISSUE THREAD

**Issue by sunilvaltix** [machiav3lli/oandbackupx#249]
**Description**
While trying to restore, it says:

Errors occurred

RestoreFailedException: Could not create external data directory at /storage/emulated/0/Android/data/com.hibernum.brucelee.enterthegame

**Steps To Reproduce**
1. Backup bruce lee on Android 11 on Pixel3XL
2. Uninstall
3. Try to Restore on the same phone
4. Restore fails

**Expected behavior**
Restore should work like it does on Android 10.

**Screenshots*

**System Information(please complete the following information):**
 - Device: Pixel3XL
 - Android Version: 11 
 - ROM: Stock  
 - App's Version: 4.0.0

**Comment by fabianski7** [comment]
I am also having problems restoring backups in android 11. The restoration is done without any errors displayed, but the data is not recognized.
I used a myandroidtools to check the databases where the app saves the information and they are all there without any problems. But when I open the app it runs as if it has no data

Luckily I had a backup made with the titanium backup and the restoration with it happened without problems.

**Comment by machiav3lli** [comment]
Please check the just-released 5.0.0 and report back, thanks.

**Comment by fabianski7** [comment]
> Please check the just-released 5.0.0 and report back, thanks.

Hello, thanks for informing. But the problem still continues.
Some apps are normally opened after reinstalling the backup, but the saved data is not restored.
Others do not open, they close immediately after opening them. Only after cleaning the data it works again.

**Comment by machiav3lli** [comment]
Ah, ok. So it's a #213 duplicate.
