### ISSUE TITLE
[Bug] Attempts to sort by data size leads to a crash.

### ISSUE THREAD

**Issue by abvgeej** [machiav3lli/oandbackupx#256]
**Description**
Attempts to sort by data size leads to a crash.

**Steps To Reproduce**
1. Enable sorting by data size
2. Wait a few seconds
3. Crash
4. Open OAndBackupX, return to step 2 until satisfied

**Expected behavior**
A list sorted by data size

**System Information:**
 - Device: Redmi Note 8T
 - Android Version:  10
 - ROM: Paranoid Android Q4
 - App's Version: 4.0.0

**Comment by machiav3lli** [comment]
This is actually already fixed in the code. But will have to wait for a stable release. If you'dlike you can use the test builds from our channels.

**Comment by machiav3lli** [comment]
Just release 5.0.0
