### ISSUE TITLE
[Bug] Restoring magisk system-less apps (e.g. via Nanodroid) crashes system & corrupts filesystem

### ISSUE THREAD

**Issue by Viveur** [machiav3lli/oandbackupx#258]
**Steps To Reproduce**

1. Make a backup of an app (such as Aurora Store) that has been installed by Nanodroid as a system(less?) app. Note: This bug might only arise when Nanodroid is installed via Magisk. Currently unconfirmed.
2. Attempt to restore app causes the device to hang* Long holding power will restart. Device then enters bootloop and eventually loads TWRP

Example app backup that causes this behaviour attached:
[com.aurora.store.zip](https://github.com/machiav3lli/oandbackupx/files/5721200/com.aurora.store.zip)

**Expected behavior**
Restore works or a message is shown explaining that restoring is unsupported for certain apps 

* Note: This really screws up the filesystem. Sometimes wiping the system, cache, dalvik and data partition and reinstalling Lineage 17.1 would get things up and running again, while at other times after I still noticed odd issues after doing this - such as Android File Transfer refusing to work (only eventually resolved by doing a complete format of the filesystem).

----------------------------

Android 10 (Lineage 17.1 )
OandBackup v5 Beta 1 (& v4)

Ps. Feel free to update issue title if a better description can be thought of.

**Comment by didierm** [comment]
Not sure whether my comment is relevant (coincidence/causality), but I experienced **exactly** the same symptoms (locked up UI, entirely botched filesystem, including persist.img (!), and bootloop), needing to reinstall everything.
Device : Xiaomi Redmi K20 / Mi9T
OS : LineageOS 17.1
OABX : 4.1.0-alpha2

This has been a week ago, so details are vague ; I initially attributed this to fooling around with Insular (= FOSS Island without the Google bits), but I remember being busy restoring with OABX too.
This concerned a non-systemless app, so I am only providing an additional (and probably worthless) datapoint, which may or (probably) may not be related to OABX.
