### ISSUE TITLE
[Bug] data restore RestoreFailedException

### ISSUE THREAD

**Issue by mtlmaks** [machiav3lli/oandbackupx#260]
**Description**
I reset my phone and I want to restore my apps and data that I backed up with OAndBackupX 4.0.0. Restoring the apks works fine but when I want to restore the associated data I get the following error:

RestoreFailedException: Could not read the input file or write an output file due to IOException: java.io.IOException: Input is not in the .gz format

When I look at what looks like the backed up data archive/file, the filename reads data.tar.gz.enc. Could it be that the backup has been done with encryption (hence the .enc extension)? I don't really remember if I set up the encryption in the app on my old system, but in that case shouldn't oandbackupx ask for the password? Anyhow, I was stupid enough to trust the app and not making a backup test before and now I am stuck and I really need that data...

**Steps To Reproduce**

1. restore a backed up apk and its associated data
2. get this error:
RestoreFailedException: Could not read the input file or write an output file due to IOException: java.io.IOException: Input is not in the .gz format

**System Information(please complete the following information):**

- Device: Moto G7
- Android Version: 10
- ROM: LineageOS 17.1 with MicroG
- App's Version: 4.0.0

**Comment by machiav3lli** [comment]
To put it short: it seems the backup is encrypted, which means you need the password if you'd like to access the backup, there's no easy way around it.

**Comment by mtlmaks** [comment]
Hi, thanks for the quick response. :) Well, that's what I thought, but where/how do I put the password when I want to restore the data? It doesn't present me any promt or anything, just throws the error...

**Comment by mtlmaks** [comment]
Nevermind, I figured out that you have to set the password in the settings first, also for restoring. Not the most intuitive, but it's all good now. :)
