### ISSUE TITLE
[Bug] base.apk is missing in backup 

### ISSUE THREAD

**Issue by alantay11** [machiav3lli/oandbackupx#261]
[OAndBackupX.log](https://github.com/machiav3lli/oandbackupx/files/5739256/OAndBackupX.log)

![Screenshot_Solid_Explorer_20201224-183549](https://user-images.githubusercontent.com/40111853/103083327-15457e00-4617-11eb-82f9-75349cf60aea.png)

Apk and data tar are present but I can never restore it. I was previously able to restore the apk only but after trying again it can't restore anything at all. The files are all there though.

**Comment by AnkS4** [comment]
I am facing the same issue.

The issue seems to occur when restoring from "only **APK** backup".

**Comment by machiav3lli** [comment]
Redundant #239 and already mentined in the known issues. Please read before opening issues in the future.
