### ISSUE TITLE
[Bug] [FATAL] OABX toybox invocation completely wipes phone

### ISSUE THREAD

**Issue by didierm** [machiav3lli/oandbackupx#262]
**Description**
This may be due to a malware payload in "toybox", but OABX-4.1.0-alpha2 (downloaded from the Telegram group) just destroyed my phone (including persist.img) for the second time in two weeks.

**Steps To Reproduce**

1. install OABX-4.1.0-alpha2
2. restore OABX-4.0 backups
3. profit
4. restore some more OABX-4.0 backups
5. OABX wipes the entire phone, requiring a vendor factory reinstall (including restoring the persist.img, oh joy)

**Expected behavior**
OABX should not destroy my phone, at least not without any warning.

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: Xiaomi Mi9T
- Android Version: 10
- ROM: LineageOS 17.1 , microG release
- App's Version: 4.1.0-alpha2

-----------------------------

**Additional Notes**

This happened to me _exactly_ a week ago (around the same time, if I remember well).
At that time, I was not running a logcat, and hence was completely stumbled what would have been the cause.

Luckily, today a logcat was running.

Excerpt of the last few lines : 
```
12-30 14:15:37.301 18856 13333 D OpenGLRenderer: endAllActiveAnimators on 0x75d616ff00 (RippleDrawable) with handle 0x757d6b9ee0
12-30 14:15:37.301 18856 25660 I OAndBackupX.MainActivityX: wakelock acquired
12-30 14:15:37.306 18856 25660 I OAndBackupX.RestoreAppAction: Restoring up: com.amaze.filemanager [Amaze]
12-30 14:15:37.306 18856 25660 I OAndBackupX.RestoreAppAction: [com.amaze.filemanager] Restoring app's data
12-30 14:15:37.306 18856 25660 D OAndBackupX.RestoreAppAction: [com.amaze.filemanager] Extracting data.tar.gz
12-30 14:15:37.318  1316 26159 E InputDispatcher: Window handle Window{1b8e269 u0 com.machiav3lli.backup.neo/com.machiav3lli.backup.activities.MainActivityX} has no registered input channel
12-30 14:15:37.325   762  2765 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
12-30 14:15:37.330   762  2765 D audio_hw_primary: select_devices for use case (low-latency-playback)
12-30 14:15:37.331   762  2765 D audio_hw_extn: audio_extn_fm_set_parameters: Enter
12-30 14:15:37.332   762  2765 D audio_hw_hfp: hfp_set_parameters: enter
12-30 14:15:37.362   758   758 D Zygote  : Forked child process 25661
12-30 14:15:14.064  1316  3280 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
12-30 14:15:37.364  1316  1396 I ActivityManager: Start proc 25661:com.android.externalstorage/u0a74 for content provider {com.android.externalstorage/com.android.externalstorage.ExternalStorageProvider}
12-30 14:15:37.377 25661 25661 E externalstorag: Not starting debugger since process cannot load the jdwp agent.
12-30 14:15:37.426 25661 25661 D ExternalStorage: After updating volumes, found 2 active roots
12-30 14:15:37.437 25661 25681 I externalstorag: Starting a blocking GC Alloc
12-30 14:15:37.438 25661 25681 I externalstorag: Starting a blocking GC Alloc
12-30 14:15:37.440 25661 25677 I externalstorag: Waiting for a blocking GC Alloc
12-30 14:15:37.450 25661 25681 I externalstorag: Alloc young concurrent copying GC freed 35222(18MB) AllocSpace objects, 0(0B) LOS objects, 98% free, 996KB/96MB, paused 182us total 12.691ms
12-30 14:15:37.451 25661 25677 I externalstorag: WaitForGcToComplete blocked Alloc on AddRemoveAppImageSpace for 11.073ms
12-30 14:15:37.451 25661 25677 I externalstorag: Starting a blocking GC Alloc
12-30 14:15:37.621 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/ (filesize: 0)
12-30 14:15:37.622 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/explorer.db (filesize: 32768)
12-30 14:15:37.623 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/explorer.db-shm (filesize: 32768)
12-30 14:15:37.624 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/explorer.db-wal (filesize: 412032)
12-30 14:15:37.627 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/utilities.db (filesize: 65536)
12-30 14:15:37.628 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/utilities.db-shm (filesize: 32768)
12-30 14:15:37.629 18856 25660 D OAndBackupX.TarUtils: Uncompressing databases/utilities.db-wal (filesize: 243112)
12-30 14:15:37.631 18856 25660 D OAndBackupX.TarUtils: Uncompressing shared_prefs/ (filesize: 0)
12-30 14:15:37.632 18856 25660 D OAndBackupX.TarUtils: Uncompressing shared_prefs/com.amaze.filemanager_preferences.xml (filesize: 1364)
12-30 14:15:37.633 18856 25660 D OAndBackupX.ShellHandler: Running Command: toybox ls "/"
12-30 14:15:37.642 18856 25660 D OAndBackupX.ShellHandler: Command(s) '[Ljava.lang.String;@66ab4cd' ended with 0
12-30 14:15:37.642 18856 25660 D OAndBackupX.RestoreAppAction: Removing existing files in
12-30 14:15:37.643 18856 25660 D OAndBackupX.ShellHandler: Running Command: toybox rm -rf "/acct" "/apex" "/bin" "/bugreports" "/charger" "/config" "/d" "/data" "/debug_ramdisk" "/default.prop" "/dev" "/etc" "/init" "/init.environ.rc" "/init.rc" "/init.recovery.qcom.rc" "/init.usb.configfs.rc" "/init.usb.rc" "/init.zygote32.rc" "/init.zygote64_32.rc" "/lost+found" "/metadata" "/mnt" "/odm" "/oem" "/proc" "/product" "/product_services" "/res" "/sbin" "/sdcard" "/storage" "/sys" "/system" "/ueventd.rc" "/vendor"
```

During restore of the "Amaze" (open source file manager) app data,
toybox **COMPLETELY WIPES THE PHONE**, including as a bonus gift, a persist.img damaged beyond repair.

_This may have nothing to do with OABX and may be due to a hostile toybox (Magisk 21.2 installed, with 3 well known open source modules) ; I will investigate this further. Nevertheless, a comment would be appreciated._

**Comment by didierm** [comment]
Note : I referred to the abovementioned incident of last week here : https://github.com/machiav3lli/oandbackupx/issues/258#issuecomment-751376712

**Comment by Atrate** [comment]
@machiav3lli Catastrophic error in RestoreAppAction.kt

https://github.com/machiav3lli/oandbackupx/blob/7cced7823a11894cddbc48a434313e0a6c7cae25/app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt#L112

If `removeTargets` is null or "/", this will cause OABX to call `rm -rf` on all files in `/`. The alpha needs to be taken down ASAP and the bug fixed.

**Comment by didierm** [comment]
@Atrate Thanks for the quick reply.

1. For the record : which conditions lead to `targetDirectory` being null or "/" ? As said, I was restoring the data part of Amaze (and had previously restored a data part from another app too, without ill effects)
2. More importantly : do you have knowledge of **identical catastrophic conditions in the current 5.x beta(s) ?** /sigh/ I will need to look into converting v4 -> v5 backups too, I guess.

_(nevertheless, thank you @machiav3lli for kicking new life in OAB : I have already been able to correctly restore data into a Work profile (cfr. https://gitlab.com/secure-system/Insular), something which Titanium Backup is not able to.)_

**Comment by Atrate** [comment]
@didierm 
From a cursory look over the source, it would seem that `targetDirectory` may have a wrong value assigned if `app.getDataPath()` returns a wrong value. This could be some exception when OABX parses the `*.properties` file, especially when there's a difference between versions.

**Comment by machiav3lli** [comment]
Thank @didierm  and @Atrate for the extensive reporting. I believe this have mostly with the transformation from Java to Kotlin to do (nullability and null checks) combined with the differences of .properties files. I'll add a check to avoid such catastrophies in the upcoming beta.

**Comment by machiav3lli** [comment]
@didierm a functional conversion of 4.0.0 to 5.0.0 isn't passable, it's better to create new backups using latest 5.0.0-beta out of your current(restored) apps.

**Comment by didierm** [comment]
> @didierm a functional conversion of 4.0.0 to 5.0.0 isn't passable, it's better to create new backups using latest 5.0.0-beta out of your current(restored) apps.

This is not really feasible, as I am restoring (from an OABX 4.0.0 backup) to a clean install, and hence have no current apps.
Am I correct that in this case, OABX 4.0.0 is my only option, if I do not want to risk a complete wipe again ?

Or is there a possibility to apply the check to 4.1.0-alpha2 too, and release an alpha3, maintaining compatibility with the 4.0.0 backups  ?

**Comment by machiav3lli** [comment]
@didierm sadly 4.0.0 is for now the only reasonable solution if you don't want to edit all the .properties files. 

You seem to be on TG group, you can write me there, so I can send you an example of .properties file made by latest 5.0.0 for you to orientate on with your edits and if you'd like to automate them.

**Comment by didierm** [comment]
> @didierm sadly 4.0.0 is for now the only reasonable solution if you don't want to edit all the .properties files.
> 
> You seem to be on TG group, you can write me there, so I can send you an example of .properties file made by latest 5.0.0 for you to orientate on with your edits and if you'd like to automate them.

(not really within the scope of this issue, but maybe appropriate nevertheless)
@machiav3lli I went ahead, and compared the .properties json files of an original v4 backup and a new v5 backup (restored with TitaniumBackup). Notwithstanding a removed **backupLocation**, I could not discern any notable differences.
I do not currently apply encryption, have no schedules (yet) and keep only 1 revision : I was perfectly able to restore v4 backups with v5.0.0-beta3, even into other profiles.

Nevertheless, I am currently very hesitant to use the (otherwise very featureful and well designed) app, due to the fatal bug being described in this issue.
