### ISSUE TITLE
[Bug] Restores issues from version 4.0 to 5.0

### ISSUE THREAD

**Issue by b16r05** [machiav3lli/oandbackupx#271]
**Description**
Restore issues 

**Steps To Reproduce**

1. Make backup with version 4.0
2. Try to restore apk+data with version 5.0
3. Apk is restored but Data is not restored

**Expected behavior**
Both apk + data should be restored as stated in FAQ

**Screenshots**
n/a

**System Information(please complete the following information):**

- Device: Nexus 10 (manta) [old, I know]
- Android Version: 10
- ROM: LOS UNofficial
- App's Version: 4.0/5.0

-----------------------------

**Additional Notes**

* Using version 4.0/5.0

* If you're on the latest github version:
  
  * Read [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md).
  * Read open Issues.

* Using version 4.0/5.0.

Thanks for reporting.

*** *** ***

I must say that the app I am trying to restore is marked with "**Device Protected Data**" [**Yellow shield**]. I am not sure what special things I need to do: 

Create and use /data/user_de/? 
Restore from/to /data/user_de? 
chmod 777 the backup folder? 
Manually set the path (this hack worked going from 4.0 to 4.0, but not with Device Protected Data/Yellow shield). If so, to what?

**Comment by machiav3lli** [comment]
It's mentioned in the changelog that 5.0.0 and 4.0.0 are fully incompatible for couple of reasons: most importantly the encryption setup has changed.

**Comment by b16r05** [comment]
Okay, thank you. And what does "Device Protected Data/Yellow" shield... this mean?

**Comment by machiav3lli** [comment]
It's another type of data, which is fully protected with the device-based encryption. When you see it on a backup, it means that the backup includes this type of data.

**Comment by b16r05** [comment]
@machiav3lli 

Okay, but I am not using device-based encryption (or am I?). My device was never encrypted. The extra folder, because of the shield, is very small and hardly has any data in it. 

Anyway, in this case, the app had a backup mechanism in settings, I was unaware of, to backup/restore data. At this point, I have lost data and simply started over. 

I am concerned for any app that doesn't have an in-built backup/restore mechanism and somehow the app decides to use this "other" [shield] type of data... and after backup, what if data can't be restored.
