### ISSUE TITLE
[Bug] v2rayNG cant backup

### ISSUE THREAD

**Issue by vvyoko** [machiav3lli/oandbackupx#272]
**Description**
apk link
https://play.google.com/store/apps/details?id=com.v2ray.ang

**Steps To Reproduce**

Tap on Data or APK or Both when backing up v2rayNG.
apk or both give tip
`a: Coudld not backup apk`

data give tip
`a: java.lang.NullPointerException occurred on data backup: java.lang.NullPointerException
`

**Screenshots**
![2021-1-5-15 24-1609831478](https://user-images.githubusercontent.com/2145741/103618304-ae0ac080-4f6a-11eb-9f8a-037ba734208e.png)

**System Information(please complete the following information):**

- Device: 
- Android Version: 8.0
- ROM: LOS
- App's Version: 5.0.0

backup apk or btoh log:
`{"logDate":"2021-01-05T15:20:57.753","deviceName":"sagit","sdkVersion":"REL","cpuArch":"arm64-v8a","logText":"a: t.c occurred on data backup: t.c: It does not make sense to backup sockets"}
`

backup date log:
`{"logDate":"2021-01-05T15:32:28.043","deviceName":"sagit","sdkVersion":"REL","cpuArch":"arm64-v8a","logText":"a: java.lang.NullPointerException occurred on data backup: java.lang.NullPointerException"}`

**Comment by machiav3lli** [comment]
It's already reported and will get fixed in a coming minor release.

**Comment by tsiflimagas** [comment]
This is probably fixed in version 5.0.1.

**Comment by vvyoko** [comment]
it fixed
