### ISSUE TITLE
[Feature Request] some feature need

### ISSUE THREAD

**Issue by vvyoko** [machiav3lli/oandbackupx#273]
1, Sort by add `last update time`

like the Titanium Backup
when apk update or new install 
it will sort first
I know special filters has new and `updated apps`
because it just work for backup,
when I need restore, I need change it to all.
so I need change between it and all frequently

2, setting export

There is a problem with the backup app : backup itself
at now oandbackupx is simple,but it have something need to backup
like
scheduing tasks
scheduing blacklist

2.1, scheduing tasks name diy

I use it as a custom filter to batch backup some app.
but now there is no sign for identification
just need a name diy to fix it.

3, when searching dont refresh list
I dont konw why to refresh list when end a task.
Obviously there is an `x` to the right of the search term to refresh the list

My English it not good 
i use google translate to type it.
hope you can understand.
                                                                                                                    
 have a good day~

**Comment by machiav3lli** [comment]
1. Ok
2. This is already in the long term plan
2.1. This would be implemented in future releases.
3. Redundant to another issue
No problem with english, we're mostly no native speakers. But for the future please seperate your suggestions into different issues. Not all in one.
