### ISSUE TITLE
[Bug] Restore fails on new device (data.tar.gz not found)

### ISSUE THREAD

**Issue by charlydelta** [machiav3lli/oandbackupx#277]
**Description**

I used my Galaxy S4 for a long time now, but due to it breaking apart more and more each day I recently bought a Fairphone 3+ and installed Lineageos 17.1 on it. Both devices are degoogled, so I heavily rely on F-Droid. I installed OAndBackupX on both of them on the same day via F-Droid. 

On my S4, I created backups on my SD card (successfully), copied them on my PC, and after setting up my FP3+ transferred the backups, and eventually tried to restore them there. 

I get the following errors when trying to restore:

```
RestoreFailedException: Backup archive data.tar.gz is missing. Cannot restoreRestoreFailedException: Backup archive data.tar.gz is missing. Cannot restore
```

However there is a file called `data.tar.gz` in the corresponding folders of the apps:

```
 usr@machine: ~/tmp/fp3p_linageos/data/oandbackup$ find . -iname "*"
.
./OABackupX
./OABackupX/org.quantumbadger.redreader
./OABackupX/org.quantumbadger.redreader/2021-01-05-20-48-45-user_0.properties
./OABackupX/org.quantumbadger.redreader/2021-01-05-20-48-45-user_0
./OABackupX/org.quantumbadger.redreader/2021-01-05-20-48-45-user_0/data.tar.gz
./OABackupX/com.bijoysingh.quicknote
./OABackupX/com.bijoysingh.quicknote/2021-01-05-20-48-29-user_0
./OABackupX/com.bijoysingh.quicknote/2021-01-05-20-48-29-user_0/data.tar.gz
./OABackupX/com.bijoysingh.quicknote/2021-01-05-20-48-29-user_0.properties
./OABackupX/de.danoeh.antennapod
./OABackupX/de.danoeh.antennapod/2021-01-05-22-21-16-user_0
./OABackupX/de.danoeh.antennapod/2021-01-05-22-21-16-user_0/data.tar.gz
./OABackupX/de.danoeh.antennapod/2021-01-05-22-21-16-user_0.properties
./OABackupX/com.machiav3lli.backup-4.0.0.apk
```

**Expected behavior**
I expect that the restore functions correctly.

**Screenshots**

There really isn't anything to see, I get an error message exactly as in the log file posted above. For all apps I tried, it never worked.

**System Information(please complete the following information):**

**Backup device**

- Device: Galaxy S4 
- Android Version: 9
- ROM: LineageOS
- App's Version:  Version 4.0.0 (4000) suggested Added on 2020-11-03 (F-Droid)

**Restore device**

- Device: Fairphone 3+ 
- Android Version: 10
- ROM: LineageOS
- App's Version:  Version 4.0.0 (4000) suggested Added on 2020-11-03 (F-Droid)

-------

Please let me know if there is more I can provide to help resolve this.

**Comment by machiav3lli** [comment]
Redundant and already mentioned in known issues (ISSUES.md) either wait for FDroid to build 5.0.0 or update through IzzyOnDroid or from here(the same). And please read the changelog.
