### ISSUE TITLE
[Bug] Syncthing backup fails

### ISSUE THREAD

**Issue by iexos** [machiav3lli/oandbackupx#281]
**Description**
Backup of syncthing fails with error message.

**Steps To Reproduce**

1. Select Syncthing app
2. Backup -> Both
3. An error occurs, see screenshot (why can i not copy the log?)

**Expected behavior**
Successful backup of Syncthing.

**Screenshots**
![Screenshot_20210109-092917_OAndBackupX](https://user-images.githubusercontent.com/15062278/104087120-bfe7ae80-525d-11eb-85a5-3b4e8bc50c9e.png)

**System Information**

- Device: Fairphone 3
- Android Version: 9
- ROM: LineageOS 16.0-20201210-microG-FP3 
- App's Version: 5.0.0 F-Droid

**Comment by machiav3lli** [comment]
Is the stop-cont activated in advanced settings? If not activate it or try doing the backup while the sync is off.
Syncthing is running in the background, which results the data changing while the backup is running and fails the check.

**Comment by iexos** [comment]
Thank you, that setting fixes it :)
I didn't use this setting, as I didn't understand what it does. Stopping an app during the backup is quite obvious and I am happy to do it, personally I would make it the default. Can I rely that apps like Syncthing will continue after the backup finishes? Syncthing transfers my backups, without oabx would be quite pointless.

**Comment by machiav3lli** [comment]
The option pauses the process and after the backup is done a continue signal is sent. This should cover all streamlined processes. But as some processes could have their own logic working with those signals, it's left default off.
I use the same flow (OABX+SyncThing) without STOP-CONT. Just bind syncthing to the system's auto sync tile and deactivate it before backup.

**Comment by iexos** [comment]
Thank you, I will keep it on until I encounter errors resulting from that setting. A backup which is not fully automated would be of much less valuable to me (even though #199 is preventing this atm)
