### ISSUE TITLE
Error while backing up system apps & Softbrick

### ISSUE THREAD

**Issue by KrischnaGabriel** [machiav3lli/oandbackupx#285]
I ran into two problems:
The first one is the softbrick where you might can held
and the second one; repetitive errors while backing up system apps.

**Softbrick; manual restoration of system apps ?**

I screwed up and accidentally uninstalled system apps that were required for the phone to boot. fastboot and twrp-recovery still work tho. just didn't took a full system backup beforehand cuz for playing around with apps i have your software to restore them. 
Question is, 
where does OAndBackupX stores the backed up apps&files (they're not in the internal memory /sdcard/ ) and
how can i manually restore system apps when i cant boot into the OS?

i did found the currently installed apps in  /data/data, /data/app and /system/app but dont know where the backups are stored for a manual installation.
I could also flash the stock rom, again, but cuz i cant find the backed up apps (and their data) all of my data would be lost as well.

**-----------------------------**

**Description**
I took a backup of all apps (including system apps) and then oandbackupx gave out errors (java.io.IOException).

**Steps To Reproduce**
1. root a Xiaomi Redmi Note 9 Pro  (the Guide i used: https://www.getdroidtips.com/twrp-recovery-redmi-note-9-pro/#Download-TWRP-Recovery)
note: to root it i went into twrp-recovery > Advanced > Install Root   which will root it with supersu
2. after rooting, install OAndBackupX from F-droid (https://f-droid.org/en/packages/com.machiav3lli.backup/)
3. try to backup all apps
4. while backing up, java.io.IOException errors occur

**Expected behavior**
No error messages. A successful backup of all apps.

**System Information:**
- Device: Xiaomi Redmi Note 9 Pro
- Android Version: 10.0
- ROM: latest stock rom; joyeuse_eea_global_images_V12.0.1.0.QJZEUXM_20201110.0000.00_10.0_eea (https://xiaomifirmwareupdater.com/miui/joyeuse/)
- App's Version: latest; 5.0.0

**Screenshots & logs**
Note: i took, both multiple logs(over the adb interface) and screenshots directly while and afterwards it happened.

[13;35;56_14.01.2021_logcat.txt](https://github.com/machiav3lli/oandbackupx/files/5820956/13.35.56_14.01.2021_logcat.txt)
[0&bckx 13;31;38_14.01.2021_logcat.txt](https://github.com/machiav3lli/oandbackupx/files/5820937/0.bckx.13.31.38_14.01.2021_logcat.txt)
[13;35;45_14.01.2021_logcat.txt](https://github.com/machiav3lli/oandbackupx/files/5820947/13.35.45_14.01.2021_logcat.txt)
![Screenshot_2021-01-14-15-08-23-296_com miui home](https://user-images.githubusercontent.com/39499729/104736956-f16fe680-5743-11eb-9390-ae1c46417ee0.jpg)
![Screenshot_2021-01-14-13-36-02-921_com android settings](https://user-images.githubusercontent.com/39499729/104736936-ec129c00-5743-11eb-8462-34d79e7b9395.jpg)
![Screenshot_2021-01-14-13-36-09-849_com machiav3lli backup](https://user-images.githubusercontent.com/39499729/104736943-ee74f600-5743-11eb-80fc-9871a83c0122.jpg)
![Screenshot_2021-01-14-13-35-05-715_io github muntashirakon AppManager](https://user-images.githubusercontent.com/39499729/104736919-e87f1500-5743-11eb-93df-1485862b812b.jpg)
![Screenshot_2021-01-14-13-35-46-252_com android settings](https://user-images.githubusercontent.com/39499729/104736928-ea48d880-5743-11eb-8ad3-0d9ef14b4bd1.jpg)
![Screenshot_2021-01-14-13-28-42-541_com machiav3lli backup](https://user-images.githubusercontent.com/39499729/104736889-e2893400-5743-11eb-8d51-286b86e3fc7a.jpg)
![Screenshot_2021-01-14-13-31-03-354_com machiav3lli backup](https://user-images.githubusercontent.com/39499729/104736905-e61cbb00-5743-11eb-8300-f98ac16a21f9.jpg)
btw
Thanks for this awesome foss tool, just annoying the issues i had with it, but except that, thanks

**Comment by machiav3lli** [comment]
All those errors with ...closed at 'X' before the 'Y' bytes... mean that the app is still running in the background. You can try to turn on the Stop-Cont option in advanced settings. If it still doesn't work, this means that such apps have priviliges to run non-stop. I see GSF under your failed backups, that's one of them. 

Otherwise, the probablty that the restore of system apps on different setups could cause a system break is high.

**Comment by machiav3lli** [comment]
Miui is causing a lot of problems for backup/restore processes, which is why you have to turn Miui optimizations off.

Where you find the backups, is where you've chosen your backup folder to be.

**Comment by KrischnaGabriel** [comment]
ok thanks.
