### ISSUE TITLE
Can't backup OsmAnd+ map files

### ISSUE THREAD

**Issue by linsui** [machiav3lli/oandbackupx#29]
There are some map files but only 13kb files are backuped. The old oandbackupx directory is as 10x large as the new OAndBackupX. I guess there are some other apps which are not backuped completely.

**Comment by machiav3lli** [comment]
Ah it's all saved in the external storage, ok, I'll add it and make it the default in the next release. Thanks

**Comment by linsui** [comment]
Thanks! Will all files in Android/data be backuped? Or maybe I should backup the data directory manully?

**Comment by machiav3lli** [comment]
I'll be giving the option to add'em up to normal backup process, so you can decide depending on your preference, cause there're mostly some huge files

**Comment by machiav3lli** [comment]
(Here)[https://send.firefox.com/download/b6541332cd46b7d8/#67aVp9xbTxZuRFSOhJMZCg]'s a test build adding external data backup und preferences for it and device protected data. The pass is >your name<OAndBackupX

**Comment by linsui** [comment]
Thanks! It works well! I tested it with pixiv for muzei 3 and all pictures in external storage is backuped. 👍

**Comment by linsui** [comment]
A problem. The files in external is backuped but not restored.

**Comment by machiav3lli** [comment]
Ok, there seems to be something's crashing, I'll have to debug it later.

**Comment by linsui** [comment]
I found that if I restore apk + data, no data is restored. But I can restore apk first and then restore data.

**Comment by linsui** [comment]
The test apk doesn't restore device protected data either. I install version 1.1.1 and restore external data manully and everything works well.

**Comment by machiav3lli** [comment]
Oh, I know then what's gone wrong. Huh

**Comment by machiav3lli** [comment]
[Here](https://send.firefox.com/download/5d53ef77756364de/#BtzA9UTTzdEIh2d5Z5NxtA)'s a new test build that hopefully fixes the backup/restore functions. Same pass as last one. Please test throughly

**Comment by linsui** [comment]
I test it against Axet's Book Reader.  Settings are stored in device protected data and books are stored in external storage. It works well! Thanks!

**Comment by rezad1393** [comment]
I have tested recently with osmand

and I have selected storage option as internally .

and I see no space used in obb and accessible folder for osmand.

and in osmand android  I see 1GB space used for user data.

but when I back up that app, it doesnt get bigger than 169MB. even if I chose to select all back up options like, media user data and even cache.

what is going on?

**Comment by tsiflimagas** [comment]
I don't quite get what you mean you have selected storage option as internally. In any case, as discussed above, you need to backup "External data" to include the maps.

**Comment by rezad1393** [comment]
> I don't quite get what you mean you have selected storage option as internally. In any case, as discussed above, you need to backup "External data" to include the maps.

I mean that in the app there is an option that says to store map and other data 
if I select internal app memeory then I cant back it up even when I select all the backup option.
and I see in app properties in android app management that user data is there (almost1.42GB)

![Screenshot_۲۰۲۳۰۹۰۷-۲۳۳۵۵۹_OsmAnd~](https://github.com/NeoApplications/Neo-Backup/assets/7523164/1ce91e2b-e17f-4118-b3a2-82cf31d849fd)

**Comment by tsiflimagas** [comment]
> I mean that in the app there is an option that says to store map and other data

Oh, I didn't think you meant OsmAnd+, now I see.

So, I tried the app myself and found out the reason you can't backup downloaded maps, is because it saves them in the no_backup directory. So, you have to enable the respective option in settings. Note that you may want to disable it after backing up OsmAnd+ since for the rest of your apps you would backup data which you probably don't need.

**Comment by rezad1393** [comment]
> no_backup

I think I enabled that too and still didn't get backup but I am not sure.

but thanks for the investigation.

truth to be told I don't really need to backup  the map that much, and the user option and changes are saved with only two (app,data) option get backuped.

I have disabled all the backup option now except two, data and app.

also thanks for the app.

btw, I randomly saw that I can backup the app itself?
can I restore the backup app from itself? when I tried it gave an error.

**Comment by tsiflimagas** [comment]
> I think I enabled that too and still didn't get backup but I am not sure.

I tried myself and it worked. Though, I use a build from current HEAD, which is some commits ahead of 8.3.2, but I think it should work on the published 8.3.2 build too. Note that you should enable both backup and restore of the no_backup files.

> can I restore the backup app from itself? when I tried it gave an error.

No, that doesn't work. There's a hidden backup and restore of preferences though. Long press on the title of the current page on the top left corner to open the hidden settings. From there tap `tools` and there you have save and loadPreferences.
