### ISSUE TITLE
Help with restoring backups

### ISSUE THREAD

**Issue by vtkhatri** [machiav3lli/oandbackupx#294]
I have created backups with v4.0.0 before switching roms.
After new rom was flashed and rooted, I tried to restore previously backed up apps, could not succeed.

Error - 
`{"logDate":"2021-01-25T13:59:01.006","deviceName":"sakura","sdkVersion":"REL","cpuArch":"arm64-v8a","logText":"a: Could not read the input file or write an output file due to IOException: java.io.IOException: Input is not in the .gz format"}`

What am I missing here?

**Comment by tsiflimagas** [comment]
It seems that your backup is encrypted and you haven't set your password. Also, v5.0.0 isn't compatible with v4.0.0 so you may want to restore your backup with v4.0.0 and make a new backup with v5.0.0

**Comment by vtkhatri** [comment]
Thanks @tsiflimagas
I was using v4.0.0 to restore but had completely forgotten to set my encryption key

Moving on will switch to v5
