### ISSUE TITLE
[Feature Request] Allow Oandbackupx to back up its own data

### ISSUE THREAD

**Issue by abliss** [machiav3lli/oandbackupx#296]
**Is your feature request related to a problem? Please describe.**
I'm switching to a new phone. I went through Oandbackupx's list of my apps and painstakingly chose which ones needed backup for the apk, the data, or both.. Now I want to restore everything on my new phone, *including that list*.
 
**Describe the primer solution**
Oandbackupx should itself appear in the app list.

**Describe alternative solutions**
Or if that's hard somehow, provide an export and import for my preferences.

- App's Version: 5.0.0 from fdroid

**Comment by hg42** [comment]
I agree...both variants

if settings are virgin, they might be restored from the backup directory (after choosing it and permissions are granted).

I think it's possible to backup OABX itself and I had this enabled experimentally,
but it seems to be a bit difficult, at least it should restart afterwards, otherwise it's in an inconsistent state

**Comment by 07416** [comment]
@abliss Please change the title to:

>[Feature Request] Allow Oandbackupx to back up its own data

**Comment by hg42** [comment]
the left bracket is missing :-)

**Comment by machiav3lli** [comment]
The next version will have an export/import option for the schedules. Preferences will be encrypted using KeyStore, rendering a plain backup of OABX useless. Is thre any specific preferences you'd like to import/export other than schedules?

**Comment by abliss** [comment]
Cool! I was mainly interested in schedules (and the app/data/app+data option).

**Comment by didierm** [comment]
For privacy issues, I am applying a Work profile (to contain all closed source apps).
For backup purposes, OABX is present in both the standard and Work profile : each instance has its own lists of apps to be backed up (It is useless to backup work profile apps in the standard profile, and vice versa).

Would it be possible to export/import the list of apps which are tagged for backup ?

**Comment by machiav3lli** [comment]
@didierm as mentioned in my last comment here: In the coming release, there's an option to export/import schedules if this is what you mean by "its own lists".

**Comment by didierm** [comment]
Probably, as a schedule facilitates filtering the apps which are backed up.

In my particular case, I´ll create two schedules : 
* one for the OABX instance in the standard  profile (with work profile apps being blacklisted) ;
* one for the OABX instance in the work profile (with work profile apps being explicitly selected).

I wonder whether it would be possible (with OABX having root permissions and such) for OABX to backup both standard and work profile apps+data without the need for two separate OABX instances (in both profiles) ...
