### ISSUE TITLE
[Bug] App list empty in Lineage OS 18.1

### ISSUE THREAD

**Issue by rradar** [machiav3lli/oandbackupx#309]
**Description**

Fresh install shows empty app lists for apps to backup as well as for restore (folder with backups present). Access to the restore folder works because the app was able to copy the apk of oandbackupx into the folder.

Filters default (Sort by: label, Filters: All apps, Backup Filter: All apps, Special Filters: All apps)

A little bubble is hovered and the lower part of the screen when doing a manual refresh (swiping down from top):
>The filtered list is empty

**Steps To Reproduce**

1. Install Lineage OS 18.1
2. Install latest Magisk for root
3. Install oandbackupx v5
4. Grand all permissions
5.  Nothing happens .... (even log is empty)

**Expected behavior**
I would like to see a list of apps (the ones I didn't backup yet as well as the one not install I could restore)

**Screenshots**
![image](https://user-images.githubusercontent.com/34582688/107688791-f3c05480-6c9f-11eb-8497-540f177b86d1.png)
Last screen is "View the log" under settings -> Tools
Also tried with non dark theme - same behauvior

**System Information(please complete the following information):**

- Device: Samsung Galaxy S7 edge (hero2lte)
- Android Version: 11
- ROM: Lineage OS 18.1
- App's Version: 5.0.0

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by machiav3lli** [comment]
Did you use your external storage's root directory as backup folder? It's not allowed on A10 and forward (SAF-browser points that out on A11).

**Comment by rradar** [comment]
> Did you use your external storage's root directory as backup folder?

I use the "normal" internal flash storage and it's not the root folder.

But indeed the source looks like this on android 11: `content:///com.android.externalstorage.documents/tree/primary%3AOABX`

I just created a new empty folder directly from the folder chooser with oandbackupx and now it works ( `content:///com.android.externalstorage.documents/tree/primary%3Atestbkp`. The list with apps is populated. But the restore list still doesn't have any apps (I copied single app backup folders to the new/working location).

Also interestingly, after closing oanbackupx and opening it again the Backup folder location changed to `content:///com.android.externalstorage.documents/tree/primary%3Atestbk/document/tree/primary%3Atestbkpp`.

**Comment by rradar** [comment]
Turn's out Version 5 of oandbackupx works best with backups created by version 5 :bulb: 

I copied old oandbackupx backups (v3) over to my new device by accident and not the new ones I created with v5.

Restoring the backups obviously works now :facepalm:
