### ISSUE TITLE
Some app can't restore

### ISSUE THREAD

**Issue by linsui** [machiav3lli/oandbackupx#31]
I backuped all my app on Android 9 and restored them on Android 10. Some apps doesn't work or can't restore settings:
- Muzei: Settings are not restored
- Termux: Doesn't work after restored. It seem that some bin are missing.
- ~Librera Reader: Setting are not restored~ Config files are stored in external storage.
- ~NClientV2: Can't recognize downloaded files~ Download path is changed. Android version related?
- RemoteFiles: Stuck

OAndBackupX crashes after every restoring. It works but just crash which is strange.

**Comment by machiav3lli** [comment]
I'll be fixing it as soon as I can(possibly in couple of days), for now please use the 1.1.1 version.

More about such a bug. The app still doesn't support Split-APK, this applies to all versions, this could be the reason that some apps doesn't get backup and can't be restored.

On Termux, as i recall it had to be installed with some specifi, like some libs. That's also fixable. For that try 1.1.0 please. And report back. Thanks

**Comment by linsui** [comment]
Apps above are tested against 1.1.1. All of them are get from f-droid so none of them is split apk.
There are many symlink in termux data directory. Termux complains that sh is not found which is a symlink so I guess it doesn't work because symlink is not backuped. I guess it's difficult?
Anyway, thanks a lot. It helps a lot when I swich between roms! 👍
