### ISSUE TITLE
[Bug] Restore Special backup "accounts" creates a bootloop

### ISSUE THREAD

**Issue by yennor** [machiav3lli/oandbackupx#318]
**Description**
I've tried to restore the accounts from an old mobile phone on a new one. It just didn't work And I tought, bad luck. But once I've restarted the mobile phone (two days later. Took me quite a while to figure out what the problem was) i've got into a boot loop. The mobile restarts directly again, once it tries to open launcher. As it seems the file /data/system_ce/0/accounts_ce.db has got the wrong owners.
The owners were: root:u0_a312_cache
I've changed them (guessing) to system:system that made it work again.

**Steps To Reproduce**

1. Restore special backup "accounts"
2. Reboot mobile phone
3. Enjoy the bootloop

**Expected behavior**
Accoutns beeing restored, WITHOUT bootloop

**System Information(please complete the following information):**

- Device: 
- Android Version: 10
- ROM: Resurrection remix
- App's Version: 5.0.0

**Comment by machiav3lli** [comment]
All special backups are unstable(not tested enough and resulting dramatic things from users' reports). Thanks for the report but be careful playing with those.

**Comment by yennor** [comment]
Then please show a HUGE warning message when somebody tries to restore one of those special backups...

**Comment by dl200010** [comment]
Investigating the SMS/MMS backup issue, I found that when restoring the special backups the DB file owner is wrong.

This is what it is before restore:
-rw-rw---- 1 system system  40K 2022-01-24 21:26 accounts_ce.db

This is what I saw after restore:
-rw-rw---- 1 u0_a134 u0_a134_cache  40K 2022-01-24 21:26 accounts_ce.db

**Comment by hg42** [comment]
I think this should be fixed with https://github.com/machiav3lli/oandbackupx/pull/493
in my tests the files were restored correctly, but this didn't restore all accounts, but that's another problem
