### ISSUE TITLE
[Bug] Cryptic error message when restoring with wrong password

### ISSUE THREAD

**Issue by iamkroot** [machiav3lli/oandbackupx#319]
**Description**
The app gives a very vague error `Input is not in the .gz format` when it fails to decrypt the backup while restoring, in case the user has specified the encryption password wrongly.

**Steps To Reproduce**

1. Enable encryption with some password
2. Backup
3. Change encryption password (in reality, the user reinstalled the app and forgot/misremembered the original pwd)
4. Try to restore
5. Fails with: `a: Could not read the input file or write an output file due to IOException: java.io.IOException: Input is not in the .gz format`

**Expected Behaviour**
It would be really helpful if the app can catch the last exception and hint at the possible cause. Something like `Could not decrypt file as it is not in .gz format. Double-check your encryption password.`

**Comment by machiav3lli** [comment]
Yeah, this among other messages will be catched and translated to better messages in future releases.

**Comment by MartinX3** [comment]
It would be nice if I get a dialog to input my password in case I forgot to set it in the settings.
