### ISSUE TITLE
Backup to external sd

### ISSUE THREAD

**Issue by pipoprods** [machiav3lli/oandbackupx#32]
I can't get OandBackupX to backup to external SD.
When selecting a folder on the external SD, I get an error (something like "Can't create...")

Is there any chance to get backup to external SD (probably through Storage Access Framework) ?

A workaround could be the ability to configure any folder, including ones outside user storage area (I've been using Oandbackup configured to backup to "/mnt/media_rw/..."). Can such a setting be configured ? (can be through adb commands if there's no other possibility)

**Comment by machiav3lli** [comment]
Implementing SAF support fully(needed also for Scope-Storage support) is planned for the summer, as unfortunatly I don't have much time for this huge rebasing job now.

**Comment by tslpre** [comment]
I noticed that when chosing the SD card, a column sing ":" is added after the card volume name, instead of a forward slash.
See attached screenshot... 
![Screenshot_20200627-104242_OAndBackupX](https://user-images.githubusercontent.com/7607325/85918546-13ffe800-b864-11ea-8321-2f34b151c006.png)

**Comment by machiav3lli** [comment]
@tslpre it's actually the other wayaround, this is how an external SD address is handled and having a stable entry to it is hard. Will see if this's hackable.

**Comment by Cyberavater** [comment]
Currently, I'm not using this app as my default back because of only this missing feature. So I'd be really nice if it gets implemented, as Titanium backup seems a dead project and it doesn't support split-apk.

**Comment by Cyberavater** [comment]
@machiav3lli if not using SAF, how about implementing root access to SD for the time being?

**Comment by machiav3lli** [comment]
The problem isn't the access, the handling of addresses is the problem in the current implementation. You just gotta have to wait.

**Comment by manfred3000** [comment]
First off thanx for continuing this great project.

As a workaround for external backups I created the folder '/storage/1234-5678/Android/data/com.machiav3lli.backup'.
Backup and restore is working so far.
Trying to backup to any other folder on my sdard fails.

I'm using Oabx version 3.0.0 on Android 9 LineageOS.

**Comment by marcdw1289** [comment]
Yep, that works. I mentioned that method awhile back in the oandbackup github. With OABX 3.0.0, using an app owned data directory does work, as mentioned above.
In my case, for both apps I use the media directory instead of data. Mostly because there's less to scroll through.
Screenshot because I'm too lazy to type the path.

![0001](https://user-images.githubusercontent.com/42319182/89520516-d52e4d80-d792-11ea-8698-8c84adadfcc4.jpg)

**Comment by gerroon** [comment]
`/storage/1234-5678/Android/data/com.machiav3lli.backup'` method throws an error during backup for me. See the image please

https://i.imgur.com/mcqfUzM.png

**Comment by Atrate** [comment]
@gerroon Related to https://github.com/machiav3lli/oandbackupx/issues/96
