### ISSUE TITLE
[Question] How to backup apps on android 7.1 and restore on android 11

### ISSUE THREAD

**Issue by rradar** [machiav3lli/oandbackupx#320]
**Is your feature request related to a problem? Please describe.**
I want to backup up my apps on a android 7.1.2 device and restore it on a android 11 device.

**Describe the primer solution**
Problem is that the last version works on 7.1.2 (nougat) is v3 of oanbackupx and the first supported by android 11 is v5 of oanbackupx. The versions don't share the same backup format and therefor can not be used for my use case.

**Describe alternative solutions**
None - looking for one here

**Comment by blombardo1976** [comment]
I find this report troubling; I would hope that all versions of this software would use identical file types to backup and restore; especially taking care to allow custom editing of those backups using your computer before restoring them to make minor changes as needed...

I'm exporting / importing from 4 different android emulators using 4.4.2 to 7.1 and also into various phones and tablets using every possible version of android...

I need a more universal solution as well for restoring to non identical android versions; specifically for ACCOUNTS.
