### ISSUE TITLE
stuck during contacts backup

### ISSUE THREAD

**Issue by R44D44** [machiav3lli/oandbackupx#321]
Android 11/crdroid/simple contacts. the regulär contacts APP is not allowed to see contacts.

**Comment by machiav3lli** [comment]
There's still no special backup concerned with the contacts, while you can backup the providers (for telephony, sms and contscts) this has been reported to work. But it'd be more secure if you use specialised app like [DecSync](https://f-droid.org/repo/org.decsync.cc).
