### ISSUE TITLE
[Bug] After app backup failures, corrupted backup(s) resides

### ISSUE THREAD

**Issue by dhammel** [machiav3lli/oandbackupx#339]
Hello,

I am running the latest version of oandbackupx (5.1.1) from f-droid, on a pixel 4 Android 11 and theres a small issue when it comes to failed backups.

When backups of any app fails it keeps the 'possibly corrupted' backup in its backup directory which waste space, and theres no automated method to clean this up, doesn't even appear to be a manual method in app to do it.

Reproducing it should be pretty easy, if you can intentially make a backup fail, maybe by cancelling it or force stopping app..then backup directory will contain that backup.

Oandbackupx should automatically delete it upon backup failure, or if app force stops/system crashes app then it should do a cleanup upon next launch.

I have revisions set to 1, and cleanup time to Before. So it should delete all backups of the app being backed up immediately and then perform backup, somehow it seems to delete the
1 good backup as it should, but leaving the other corrupted ones in there which it shouldn't. Then performs the backup.

This can just get unorganized pretty quickly, waste a lot of disk space if you backup apps with large data sizes such as osmand (if backing up external storage), and/or termux.

Thank you for a great app, looking forward to see why this is. :)

**Comment by machiav3lli** [comment]
Yup, this one is on my schedule for the next release.
