### ISSUE TITLE
External data of selected apps

### ISSUE THREAD

**Issue by mase76** [machiav3lli/oandbackupx#34]
Hi!
For some apps I would like to save the external data. For others like OSMand or Antennapod I don't want to save the external data, because it is too large. Maybe you could add something like a blacklist for apps, which external data is not to be saved.

**Comment by machiav3lli** [comment]
This should be possible, I'll see to it. Thanks for the suggestion

**Comment by Cyberavater** [comment]
Titanium Backup has a feature in settings, with which the user can select save the external data "Always" to "If it's smaller than a certain size", and another setting where the user can select the certain size (default is 25MB). Implementing something similar here should be useful.

**Comment by mase76** [comment]
@Cyberavater I confirm, this would fit all needs.

**Comment by bengalih** [comment]
I double down on a vote for this to be able to backup some external data.  To take it a step farther (and to think about while implementing), it would be great to be able to create application groups/labels like in TiBu where we can apply different settings to each group/label, this being one of them.

Also, I would be careful in choosing an option that just limits to a certain amount.  For instance, in my case I often want the external (OBB) data of games I have installed which may be 500MB each, but I could usually care less about external data for smaller apps.  So implementing a "backup only if < 100 MB" would actually be the antithesis of what would work for me.

**Comment by landry314** [comment]
i was about to create this same issue. i would love to see another column for external data in the batch backup section. apk, data, and ext (short for external data). there are only a few apps where i need to backup their external data. also, in the normal list of apps when you click on backup you could get apk, data, ext, all. this would be a great feature!

**Comment by mase76** [comment]
Adding the external data option to the schedules may be the simplest solution for this. Plus the option for the batch and the single backup. Maybe the same for special backups. That would give maximum flexibility, as many apps are different to backup. The user could group the schedules as he likes with the different backup options. The option in the main settings could then be removed.

**Comment by machiav3lli** [comment]
Adding other columns isn't an option, this would make the items unreadable (only little space for the main info).
