### ISSUE TITLE
Some  system apps missing in include list

### ISSUE THREAD

**Issue by mase76** [machiav3lli/oandbackupx#342]
Hi!
Some system apps, for example microg-services-core, are missing in the own list for scheduled backups. However they are present on the main page.

**Comment by machiav3lli** [comment]
I guess you have an old backup of the package?

As it's not visible to me on A11 (at all) -> PackageManager doesn't include it maybe.

How does your setup look like?

**Comment by mase76** [comment]
I did a fresh install of the app. com.google.gms is not visible in the include/exclude list, but in the main view. In the old oandbackup, it is present everywhere.

**Comment by machiav3lli** [comment]
It's not about the fresh install or not, do you have in your backup folder a backup of the package? And the more important question is: on what Android version are you?

**Comment by mase76** [comment]
I deleted all backups. This did not help. There is no backup of oabux,because the app isn't visible in any list. I am on lineage 16.1.

**Comment by machiav3lli** [comment]
Ok, now it's getting complicated. You said you can see the package in the Main view and now not. So I take this changed after removing the backups? If not then explain the whole course of the problem till now.

As already said, on my setup with A11, the app can't be seen anywhere, which means that the system filters it out of the packages list.

Main different between OAB and OABX in this matter is the targetSDK. Meaning for OAB the system doesn't use the latest API and though gets the unfilteted list.

This is for the most part theoretical, as I can't get my hands on the problem right now.

**Comment by mase76** [comment]
After I deleted all backups, there is no Oandbackupx and no MicroG-Services-Core in the mainview and in the include/exclude list. Other system apps like Fdroid and ROM stuff is there. It would make sense to backup MicroG to save the contact tracing data.

**Comment by machiav3lli** [comment]
Ok, so my hypothysis was right.

Yeah, OABX is hidden as it's running anyway, but can be backed up with the test version(neo) or vice-versa. Next version of OABX will have an option to export/import schedules for once. But backups of the app will render useless as most of the preferences will be encrypted with Android KeyStore.

On the MicroG's side of things, it's the system that's not providing the package and it's information. That's nothing that can be fully covered in OABX. A good thing is, that MicroG has an option to export the collected IDs and data.

**Comment by mase76** [comment]
So I think, we can close this issue then.
