### ISSUE TITLE
[Feature Request] About OBB files

### ISSUE THREAD

**Issue by WLongSAMA** [machiav3lli/oandbackupx#345]
备份OBB文件的时候，应该把它和APK程序放在而不是和数据一起。部分情况下，如果只备份APK程序并且不备份数据的话，会导致缺少OBB文件而无法正常启动APK程序。

The following is from machine translation: 
When backing up an OBB file, it should be placed with the APK program instead of with the data. In some cases, if only the APK program is backed up and the data is not backed up, the OBB file is missing and the APK program cannot be started normally.

**Comment by machiav3lli** [comment]
It's an optional thing and depends on the app and user's preferences. That's why there's options. In the coming version, there'll be more control over both.
