### ISSUE TITLE
[6.0.0] App is laggy not detecting apps

### ISSUE THREAD

**Issue by rancidfrog** [machiav3lli/oandbackupx#346]
Just updated to 6.0.0,
App starts to lag and does not show app list:

![](https://i.imgur.com/kGM6rZb.jpg)

![](https://i.imgur.com/FySNBq0.jpg)

Also it is flooding logcat with,
```
05-05 12:25:01.340 28603 15685 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15292 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15303 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15633 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15463 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15260 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15309 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15239 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15014 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15132 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 14937 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 12:25:01.340 28603 15634 I hiav3lli.backu: Waiting for a blocking GC Alloc

```

**Comment by machiav3lli** [comment]
As the name suggests, it's a new major version, so clean up the data and everything should be fine.

**Comment by rancidfrog** [comment]
I deleted data and cache and it works.
But each time app is opened it takes 1 minute to load and show apps.
Each time user exits app using back button and relaunches app it takes 1 minute or more to show list of apps

Also,
Settings, tools, Save app lists does not work,
It just shows popup app list still not fetched 
![](https://i.imgur.com/B8nBSpG.jpg)

**Comment by rancidfrog** [comment]
I also still have flood of logs;
```
05-05 22:31:55.388 11257 31542 I hiav3lli.backu: Clamp target GC heap from 265MB to 256MB
05-05 22:31:55.388 11257 31420 I hiav3lli.backu: WaitForGcToComplete blocked Alloc on HeapTrim for 1.344s
05-05 22:31:55.388 11257 31420 I hiav3lli.backu: Starting a blocking GC Alloc
05-05 22:31:55.395 11257 31408 I hiav3lli.backu: WaitForGcToComplete blocked Alloc on HeapTrim for 117.649ms
05-05 22:31:55.395 11257 31408 I hiav3lli.backu: Starting a blocking GC Alloc
05-05 22:31:55.395 11257 31685 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.396 11257 31635 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.397 11257 31421 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.402 11257 31645 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.402 11257 31632 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31765 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31686 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31558 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31631 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31737 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31689 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31637 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31559 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31727 I hiav3lli.backu: Waiting for a blocking GC Alloc
05-05 22:31:55.403 11257 31654 I hiav3lli.backu: Waiting for a blocking GC Alloc
```
 But, I believe the culprit is that the backup folder had old backups inside from previous version which caused oandbackup to lag.

App detected wrong format but still caused out of memory errors and lagging.
Shouldn't it just ignore the old backups and popup with notice to remove or delete old incompatible backups?
![](https://i.imgur.com/wDnnzlN.jpg)

**Comment by machiav3lli** [comment]
* How many backups do you have in your backup folder?
* what SoC does your device have?
* does the backup folder include other stuff than the backups?

On the tools side of things, it loads the apps/backups data, same as in main, so it should take the same amount of time. 1 minute is still an unrealistic time to wait for, either you have thousends of backups and an armv7(x32) or the backup directory is buggy e.g. has a lot of junk files (maybe old backups from pre-5.0.0?).

For a realistic example: SD855 with 150+ backups, 10 seconds.

* Why it's slow? Blame it on Android team or Google (read more on that in the FAQ.md).
