### ISSUE TITLE
error=13

### ISSUE THREAD

**Issue by mat-l** [machiav3lli/oandbackupx#35]
I am not able to backup apps or data. It shows error=13 as shown in the screenshot:
![Screenshot_20200616_202954_com machiav3lli backup](https://user-images.githubusercontent.com/5571947/84813751-b3291200-b010-11ea-9510-a08ba95f4ce6.jpg)

Best regards

**Comment by machiav3lli** [comment]
Did you gave the app root permission?and installed a compatible version?
