### ISSUE TITLE
[Bug] Backup freezes almost entire phone.

### ISSUE THREAD

**Issue by MartinX3** [machiav3lli/oandbackupx#353]
**Description**
I want to backup my user apps.
The option the freeze apps before backing up is used.
Every app is frozen directly.

**Steps To Reproduce**

1. Activate freeze apps.
2. Start backing up your user apps.
3. Every app is frozen at the same time.

**Expected behavior**
Only the app currently getting backed up should be frozen.

**Screenshots**
N/A

**System Information(please complete the following information):**

- Device: Sony Xperia XZ2
- Android Version: 10
- ROM: LineageOS
- App's Version: 6.0.0

**Comment by machiav3lli** [comment]
The same problem here as not being able to stop the specific services (that why we use pid >1000). Android's APIs/SDK doesn't provide a way to freeze other apps with the whole of its processes tree. Pid >1000 resembels (almost) all not-system processes.

**Comment by MartinX3** [comment]
Thank you for your response. :)
Do you know why I don't get this issue with titanium backup or migrate?
There only the currently backed-up app is frozen.
