### ISSUE TITLE
[Feature Request] TWRP Installer

### ISSUE THREAD

**Issue by MartinX3** [machiav3lli/oandbackupx#354]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a twrp installer solution like the app migrate provides.
So I could directly start restoring my stuff on a fresh wiped phone.

**Describe the primer solution**
Like the app migrate does it.

**Describe alternative solutions**
N/A

**Screenshots**
N/A

**System Information(please complete the following information):**

- Device: Sony Xperia XZ2
- Android Version: 10
- ROM: LineageOS
- App's Version: 6.0.0

**Comment by machiav3lli** [comment]
It's one of the features on the development list, but with one of the lowest priorities.
