### ISSUE TITLE
"No SAF manager" on de-googled device

### ISSUE THREAD

**Issue by Kaned1as** [machiav3lli/oandbackupx#357]
**Description**
"No SAF manager" dialog is shown while trying to use OABX on OnePlus OxygenOS with Google apps disabled.

**Steps To Reproduce**

1. Use OnePlus Oxygen OS
2. Disable all Google applications, including Play Store and Services
3. Don't disable bundled File Manager (`com.oneplus.filemanager`)
4. Try to use OABX - shows "No SAF manager" when trying to pick folder, and exits

**Expected behavior**
Expected it to pick up either bundled File Manager or user-installed Material Files (`me.zhanghai.android.files`)

**System Information(please complete the following information):**

- Device: OnePlus 6 (`enchilada`)
- Android Version: 10
- ROM: OxygenOS 10.3.10 (official)
- App's Version: 6.0.0

-----------------------------

**Additional Notes**: Phone does not have external SD card.

**Comment by machiav3lli** [comment]
Did you use a previous versions before? If yes, were you then able to pick the backup directory or did it crash?

**Comment by Kaned1as** [comment]
Yes, I have lots of backups in `/sdcard/OABX` folder. But that was on a very old version, long before SAF was introduced.

**Comment by machiav3lli** [comment]
Which versions exactly?

**Comment by Kaned1as** [comment]
* On 6.0.0 it says "No SAF manager"
* On 5.1.0 it crashes
* On 5.0.2 it crashes
* On 4.0.0 it crashes
* 3.2.0 works

**Comment by machiav3lli** [comment]
Do you use a modified version of OOS?

If not, could you please run those commands in Termux and provide what you get:
```bash
pm list packages | grep documentsui
pm dump com.android.documentsui | grep enable
```

**Comment by Kaned1as** [comment]
```
OnePlus6:/ $ pm list packages | grep documentsui
package:com.google.android.documentsui
OnePlus6:/ $ pm dump com.android.documentsui | grep enable
  enable|disable <option>
OnePlus6:/ $ 
```

**Comment by machiav3lli** [comment]
Ok, now try 
```bash
pm enable com.google.android.documentsui
```
And try to choose the backup directory after that

**Comment by Kaned1as** [comment]
I'm backing up on 3.2.0 now, will try after it's done. It's a Google service though, shame Oxygen OS doesn't have AOSP version of DocumentsUI. But I'm backing up to get rid of it anyway.

Thanks for guidance. I'll close the bug now, will ping here if it won't work.

**Comment by machiav3lli** [comment]
Yeah, all OEMs' ROMs has a form of GAPPS. The only way way to go google-free is to use gapps-less AOSP-based ROMs.

It's actually the google's version of AOSP's com.android.documentsui. the only package that can handle SAF.

**Comment by machiav3lli** [comment]
Yeah, feel free to write back. And be aware that all backups pre-5.0.0 aren't compatible with 6.0.0.

**Comment by Kaned1as** [comment]
WHAT :D

**Comment by Kaned1as** [comment]
Okay, I updated and can confirm that SAF picker now works as expected. Refreshing all backups.
Thanks again!

**Comment by machiav3lli** [comment]
You're welcome.

**Comment by ruralTom** [comment]
I'm having the same issue on  custom rom. I walked through the steps provided, but when I try to enable the documentsui I get an error saying pm can't find it..

Is there  work around ? I have a couple different file expolrers installed, the app just doesn't recognize them.

Do you want me to open a new issue?

**Comment by machiav3lli** [comment]
@ruralTom you seem to be missing the files manager from your ROM, this means there's no SAF manager (Only signed system file managers can fulfill this and no other files manager whatsoever can take its place). On that matter Files (com(.google).android.documentsui) has been an essential part of the system since marhshmellow and shouldn't be handled as bloat and get removed, whatever the reason.
Side note: through TG discussion it seems that the ROM is unofficial, unmaintained and lacking .documentsui from the first place, so a way should be found to reinstall a signed files manager…
