### ISSUE TITLE
[Bug] IO exception

### ISSUE THREAD

**Issue by TMS-Namespace** [machiav3lli/oandbackupx#359]
**Description**
Getting the error msg after requesting the backup.

(By the way, after pressing save button, where dose it supposed to be saved? I searched my device and did not found it.)

**Steps To Reproduce**

1. Instal "Happy Mod" apk (from https://www.happymod.com/)
2. Run it.
3. Close it.
4. Try to backup both apk and data (backuping only apk, worked fine, for other apps everything working fine).
5. You get below error message (copied it from log file).

**Screenshot**
![Screenshot_20210522-185729__01.jpg](https://user-images.githubusercontent.com/40037422/119233062-bbd67200-bb16-11eb-9263-7c10e2b37eb9.jpg)

- Device: OnePlus 7t
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...)  OOS 10.0.15
- App's Version: 5.1 and 6.0.0 producing same error.

-----------------------------

Error log:

{"logDate":"2021-05-22T18:38:35.304","deviceName":"OnePlus7T","sdkVersion":"10","cpuArch":"arm64-v8a","logText":"a: java.io.IOException occurred on data backup: java.io.IOException: Entry \u0027files/.envelope/z\u003d\u003d1.2.0\u0026\u00262.6.5_1616146990809_emNmZw\u003d\u003d\u0027 closed at \u00270\u0027 before the \u0027300\u0027 bytes specified in the header were written"}

**Comment by machiav3lli** [comment]
This means that the data of the app has been changed whils it's getting backed up. The app seems to have a system-near/hidden service running. Try to kill before backup

**Comment by TMS-Namespace** [comment]
@machiav3lli Yes I thought about that,  and indeed  killed the app,  but the error didn't change.

**Comment by machiav3lli** [comment]
Then it's a service running that's not really bound to the app. Such behavior has been noted also on MS's Swift Keyboard.

**Comment by TMS-Namespace** [comment]
@machiav3lli Ok,  but anyway shouldn't OAndbackup stop everything during the process?  Other backup apps like swift backup has no such issues with this app or another. 

BTW, I tried also to freeze it before backup (via icebox),  and still getting same error,  so I kinda doubt that there is a background service running.

**Comment by machiav3lli** [comment]
Yes, it stops all processes with pid >1000, which are basically all process but the system one(official APIs don't really cover some background and child processes). This is why I said, that it's using a process that's "system-near".
Other backup apps don't check the integrity of the created backup data as far as I know (we won't really know, as they're closed-source).

**Comment by megamorphg** [comment]
@machiav3lli it was just user apps. If I did a few (5-10) then it worked. But when I tried to backup all ~300 user apps it bombed out after like the 2nd one.
I ended up just not using oandbackupx or TB because the sdcard resetting was just too catastrophic.
I'm using Lighthouse for LGH918 (LG V20) which is on A11... which apparently requires some Magisk module to mount the SD Card differently (newer versions of android are requiring this) to write to SD when using Migrate. So I think this is the root of the issue. But that means I'll have to reset my SD for the 6th time again and re-mount. Doing nandroid for now.

**Comment by machiav3lli** [comment]
@megamorphg so maybe its this hack that you're using causing a malfunction by the backup/restore process or it's the storage that's getting overloaded.
Are any magisk modules (systemless apps) included in this list or used explicitly by the system e.g. magisk manager is installed as a user app?
