### ISSUE TITLE
Errors occured "No such file or directory" "Operation not permitted"

### ISSUE THREAD

**Issue by Chuunie** [machiav3lli/oandbackupx#36]
Running the version from f-droid, android 9, custom ROM, magisk root. Regular oandbackup works without errors but when I backup apps with oandbackupx I get these errors on some apps.
![signal-2020-06-16-223515](https://user-images.githubusercontent.com/25088719/84830710-d4462e80-b021-11ea-94a3-da3316a13105.jpeg)

**Comment by machiav3lli** [comment]
For the most part, the upper one only means that your app doesn't have cache to clean, I'll add a filter for this warning. Second one is "new". So it'd be nice if you provide the log

**Comment by machiav3lli** [comment]
According to reports in the development's group, this(second one) have to do with fact that this's a split apk, and as mentioned in the README this is still not supported you can follow updates on this matter in #8

**Comment by bettyvschmartz** [comment]
+1 I have the exact same issue. App backs up with the original OAndBackup fine but not this. If this is a fork why is that? 

-- BVS

**Comment by machiav3lli** [comment]
Technicaly,speaking right now it's more of a rewrite as a "just a" fork. 
Those and other errors are fixed in the latest test build. One which has to do with excluding cache from the backups(saving storage), the other one has to do with split Apks support, which is in test for now.
