### ISSUE TITLE
[[Android 11: Crash]]Crashes upon opening app.

### ISSUE THREAD

**Issue by druloloy** [machiav3lli/oandbackupx#361]
I am able to backup my files but then after I updated my custom ROM (Pixel Experience) to Android 11 (former Android 10), the app won't open and crashes all the time. 

![Screenshot_20210602-220436_Pixel_Launcher](https://user-images.githubusercontent.com/41189336/120494702-9edf5000-c3ee-11eb-9646-f67bb1f86122.png)

Device: Poco F1
Note: I have MagiskRoot but SafetyNet fails.

**Comment by machiav3lli** [comment]
Did you update from 5.x.x to 6.0.0? If yes, then just wipe the data of the app.

If else, then describe the process that lead to this more.
