### ISSUE TITLE
[Feature Request | UI]  Add a "backup all updated apps" button to Main screen

### ISSUE THREAD

**Issue by Atrate** [machiav3lli/oandbackupx#365]
Situation:
It is possible for OABX to backup all updated apps. To do so, the user needs to switch screens from the main one and sort through the various menus to find the option. This could be made easier in the case of this one special case.

Proposed solution:
When the user taps the red "X Updated Apps" button in the top left of the list on the Main screen, a button in the layout could be shown that would back-up the X updated apps en masse.

**Comment by machiav3lli** [comment]
Cool, a pretty nice idea
