### ISSUE TITLE
(probable) crypto vulnerability

### ISSUE THREAD

**Issue by trou** [machiav3lli/oandbackupx#368]
Hello,
thanks for maintaining this fork of oandbackup.

I considered switching to it but I wanted to check the crypto first to make sure
everything was OK and I realized that there's a vulnerability (most probably, I
haven't had the time to validate using the code itself):

You are using AES/GCM with a constant (all zeros) IV. This creates a
vulnerability were data can be manipulated by an attacker

As noted in the Java doc:

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/crypto/Cipher.html

Note that GCM mode has a uniqueness requirement on IVs used in encryption with a
given key. When IVs are repeated for GCM encryption, such usages are subject to
forgery attacks. Thus, after each encryption operation using GCM mode, callers
should re-initialize the cipher objects with GCM parameters which have a
different IV value.

IV must always be generated randomly. Although there's not need for
cryptographically-strong random numbers, uniqueness is important.

But anyway on Android, I'd use the recommended code
(https://developer.android.com/guide/topics/security/cryptography?hl=en#pbe-without-iv)

```kotlin
val iv = ByteArray(16)
SecureRandom().nextBytes(iv)
cipher.init(Cipher.ENCRYPT_MODE, key, IvParameterSpec(iv))
```

Also, some other nitpicks:

- 2020 iterations for PBKDF2 is definitely too low, I'd put it at 100.000
- I liked oandbackup ability to use external providers for public key crypto
(such as openkeychain). Using a GPG public key to encrypt the backups is the
most secure/practical thing to manage the backups outside of the system afterwards.

PS: I sent an email to report the vuln, but probably ended up in spam. As it's not that critical, I'm reporting it here.

**Comment by machiav3lli** [comment]
Hey @trou thanks for reporting, I actually did read your mail,but didn't have time to answer it.
Here's some points I'd like to make clear before following any AES/GCM requirements:
1. An IV that's random generated and not saved outside of the encrypted files, would result inability to decrypt them (correct me if am wrong). 
  * A solution that could come to mind is using Android's KeyStore (maybe with the some static values like the password), but this would kill backups portability, which is the main functional requirement of the app.
2. Using more iterations could result even slower operations, which hurts eventually the UX (some users already see the time as critical factor and were annoyed after the last time I increased the iterations count among other variables).
3. GPG is on my TODO list as the developer document states, but it's not one of the highest priorities right now (contribution on that matter is always welcome).

All in all: I see that from security perspective that those parameters aren't meeting some of the AES/GCM standards/practices, but the whole functionality of the app has to be thaught about together. Striking a good balance between security and functionality isn't that easy in this domain.

I chose to provide users with a simple non-standarized(and not GPG-based) encryption option, that I think is enough for the most users. GPG users are still a minority, even in this "power user"-ish domain.

**Comment by trou** [comment]
Hello,
thanks for your detailed feedback.

Regarding your comments:

1. The IV does not need to be secret. It can be stored without any problem in the encrypted file, in a header for example (See [here](https://github.com/openssl/openssl/blob/master/apps/enc.c#L449) for openssl `enc`).
2. I haven't checked exactly were the PBKDF2 derivation is done, but in theory, it can be done once and for all per application run, when first encrypting / decrypting data. So it shouldn't have a big performance impact. But anyway, it's not such a big deal, people can always put longer passwords. Maybe you could make it configurable? Ideally, the key derivation function should be based on scrypt or argon2, but it seems Android does not provide an API for that.
3. Sorry, I did not see the mention before. GPG support is definitely not easy, it was just a suggestion, I'm happy it's somewhat planned :)

Anyway, don't hesitate to reach me if you have questions related to security and/or crypto.
