### ISSUE TITLE
[Bug] [Android 11] Failed to read Android/data on my sdcard

### ISSUE THREAD

**Issue by MartinX3** [machiav3lli/oandbackupx#369]
**Description**
Since Android 11 I can't access my backups in Android/data on my sdcard.
I put them in the scoped storage of the syncthing application to sync the backups with my computer.
Or restore app data into it.

**Steps To Reproduce**

1. Access folders in Android/data
2. Empty folder if I want to choose the backup folder

**Expected behavior**
Being able to see subfolders of the scoped storages of the apps since oandbackupx uses root.

**Screenshots**
N/A

**System Information(please complete the following information):**

- Device: Sony Xperia XZ2
- Android Version: 11
- ROM: AOSP
- App's Version: 6.0.1

**Comment by machiav3lli** [comment]
OABX isn't a file manager. Further more, OABX uses SAF and though can't use Android/data, Downloads or storage main directory as backup directory

**Comment by MartinX3** [comment]
Yeah, it's an android 11 change. In 10 it did work.
So it will never work again until google changes it decision?

(I changed my directory to the root of my sdcard, luckily syncthing can now access this place again)

**Comment by machiav3lli** [comment]
This won't change (possibly never). Why would you want to use Android/data as a backup directory?

**Comment by MartinX3** [comment]
Until I moved to android 10 syncthing rootless wasn't able to use a folder outside of his own in Android/data, so I put everything I wanted to sync with my other devices into `Android/data/com.nutomic.syncthingandroid/files/`

But now with android 11 synthing is able to access my sdcard root.
Now I can moved my stuff outside of Android/data and it is working successfully.

Thank you for your support. :)

**Comment by machiav3lli** [comment]
@MartinX3 you're welcome. Hm.. that's awkward, it always worked fine for me.
