### ISSUE TITLE
[Feature Request] Add Filter for Global Blocklist

### ISSUE THREAD

**Issue by GodKratos** [machiav3lli/oandbackupx#378]
I haven't found any way to be able to view apps on the global blocklist, or to remove them from it.

Probably the easiest way to do that is just having a filter option to show the blocklist so you don't need an extra interface for that specifically.

Additionally when clicking a blocked app, the button to block it would then change to an un-block button to remove it from the global blocklist.

**Comment by machiav3lli** [comment]
There's already a block list shortcut in each tab in the current test version.
