### ISSUE TITLE
Add a disabled application filter

### ISSUE THREAD

**Issue by Salim9304** [machiav3lli/oandbackupx#380]
The user has disabled some applications, which ones he does not remember. To enable (unfreeze) any application, you need to output them. But there is no filter for disabled applications among the filters. In similar applications, such filters exist (for example, titanium backup).
I'm surprised.

**Comment by Salim9304** [comment]
there is already such a request: 
https://github.com/machiav3lli/oandbackupx/issues/334

**Comment by machiav3lli** [comment]
Yup, it's a duplicate
