### ISSUE TITLE
[Bug] remove an app from the blocklist

### ISSUE THREAD

**Issue by steinhmor** [machiav3lli/oandbackupx#383]
**Description**
I habe not found a way to remove an app from the global blocklist. Am I blind or is this feature missing?

**Steps To Reproduce**

1. select an app
2. add it to the blocklist

**System Information(please complete the following information):**

- Device: Fairphone FP2
- Android Version: 10
- ROM: Lineage
- App's Version: 6.0.1

**Comment by machiav3lli** [comment]
You just didn't read the latest closed issues #381 & #378.

**Comment by steinhmor** [comment]
OK thanks :-)

**Comment by exec228** [comment]
Could this action have a confirmation?
Icons are not self-explanatory, and the action is way too rapid.
I was forced to press all buttons one-by-one to understand what do they mean from confirmation text only.

**Comment by machiav3lli** [comment]
@exec228 long pressing buttons gets you their tooltip text
