### ISSUE TITLE
[Bug] Scheduled backups fail on uninstalled apps

### ISSUE THREAD

**Issue by GodKratos** [machiav3lli/oandbackupx#385]
**Description**
I have a scheduled backup configured that uses a blocklist only to backup all apps except specific ones. When the schedule runs there are multiple "BackupFailedException: Could not backup apk" messages for apps that have since been uninstalled since the schedule was created.

**Steps To Reproduce**

1. Create a backup schedule for all apps
2. uninstall an app
3. run the schedule
4. error occurs for uninstalled app

**Expected behavior**
The backup list should be generated on start of the scheduled backup not when the schedule was created.
I haven't tested, but I assume if the list is pre-generated that newly installed apps might not be included in the scheduled backup either.

**System Information:**

- Device: Nubia NX563J
- Android Version: 9
- ROM: Havoc
- App's Version: 6.0.1 (github build from 20th July 2021)

**Comment by machiav3lli** [comment]
The backup list is generated on the start of the scheduled backup, so maybe there's some missing connection between the two facts...

**Comment by GodKratos** [comment]
I've had several scheduled backups run since and they always generate failure messages for the same bunch of apps that have been uninstalled since the schedule was created.

**Comment by GodKratos** [comment]
This is definitely an issue, I just tested on the latest build in android studio.

1. Create a scheduled backup for all user apps and run backup
2. Uninstall an app
3. Run the scheduled backup again and an error is generated for the uninstalled app
