### ISSUE TITLE
Filed an issue to the F-Droid repository

### ISSUE THREAD

**Issue by TheEvilSkeleton** [machiav3lli/oandbackupx#4]
Hello, I have filed an issue in the F-Droid repository. Here is the link in case you are interested: https://gitlab.com/fdroid/rfp/-/issues/1316

**Comment by TheEvilSkeleton** [comment]
I just found out there is someone pulling a merge request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6562

**Comment by machiav3lli** [comment]
Yeah that's me. It'll possibly take some time for it to be approved. Thanks for opening the issue though.
