### ISSUE TITLE
[Bug] Unable to backup apps with ~ in their name

### ISSUE THREAD

**Issue by morfikov** [machiav3lli/oandbackupx#401]
**Description**
It looks like the oandbackupx app list is missing some apps in my system. One of them is OsmAnd+ installed from F-Droid. I don't know why it isn't listed, but the only thing that comes to my mind is the `~` character in it's name. 

**System Information(please complete the following information):**

- Device: Xiaomi Redmi 9
- Android Version: 11
- ROM: AOSP-based
- App's Version: 6.0.1 installed from F-Droid

**Comment by machiav3lli** [comment]
- [ ] # It's shown normally on my device and works all fine. Could you please provide more information like used filter etc.

**Comment by morfikov** [comment]
I basically wanted to backup all the apps and their data. So I went under scheduling and added new task with "All apps" in the filters, and backup mode set to APK, Data, Device Protected Data, External Data, OBB Data. I hit the "start now" button. When the backup was done, I noticed that the size was around 3GiB, which was a little bit too small, since the userdara partition is around 12GiB in size. I know oandbackupx compresses the backup data, but still it was really small (compared to TWRP). So I started to look for something that wasn't included, and I noticed there's no entry like OsmAnd+ (not sure if only this one was missing). 

The funniest thing is that when I opened the oandbackupx app today, the OsmAnd+ entry in the Mian tab was visible (I sorted the apps using the size filter). So I tried to do a full backup again, and when I refreshed the Main tab, the OsmAnd entry disappeared. When I search in the Main tab for "osm", it finds nothing. 

I was trying to clear cache, open/close the oandbackupx app, refresh the app list, and it sometimes shows the OsmAnd+ entry, but most of the time it doesn't. Sometimes I can see the entry just for a second after launching oandbackupx, but it disappears shortly after oandbackupx was launched.

**Comment by machiav3lli** [comment]
Hm... now this exotic. Maybe am repeating myself but I didn't have such problem and no similar error was reported till now. Could you try thelatest beta from the TG/Matrix group.

**Comment by morfikov** [comment]
I'll try.

**Comment by morfikov** [comment]
@machiav3lli , yes, it looks like the 7.0.0-beta2-neo version seems to have this issue fixed, i.e. the OsmAnd+ app is always on the list, and when I do the backup of all of the apps, OsmAnd+ files are also included.
