### ISSUE TITLE
[Bug] Deleting backups of not installed apps is not working

### ISSUE THREAD

**Issue by yennor** [machiav3lli/oandbackupx#402]
**Description**
When I  press "settings/tools/Delete backups?" which should delete backups which are not installed on the system, it always tells me: "App's list is still not fetched. wait ...."

**Steps To Reproduce**

1. Open oandbackupx
2. wait until it loaded all backups and populates the list
3. click on settings/tools/delete backups
4. "app's list is still not fetched" is shown. => nothing happens

**Expected behavior**
starting to delete the backups

**System Information(please complete the following information):**

- Device:  Poco x3
- Android Version: 11 
- ROM: arrowos
- App's Version: 6.0.1

**Comment by machiav3lli** [comment]
On 6.0.1 the list starts (re)loading when you get into the preferenves activity. On 7.0.0(still in beta, but will be released soon) this behavior is already fixed.
