### ISSUE TITLE
Scheduling doesn't work for me.

### ISSUE THREAD

**Issue by macerg** [machiav3lli/oandbackupx#403]
I'm running on a rooted OnePlus 6 
![Screenshot_20210919-124729](https://user-images.githubusercontent.com/4559048/133926374-10bcaece-3390-46b7-a8db-110a509b50f7.jpg)
Scheduling doesn't run. I've set battery optimization off.

**Comment by machiav3lli** [comment]
Duplicate of #199. It's still true that Google/Android doesn't provide a reliable API to schedule actions/services/jobs. Otherwise there's more restrictions of running app bound services depending on your ROM (thumb rule: OEM's are far worse than AOSP's).
