### ISSUE TITLE
Bug: App restarts if cache directory doesn't exist

### ISSUE THREAD

**Issue by neekless** [machiav3lli/oandbackupx#41]
**If 'Clear app's cache' is enabled**, if the cache directory doesn't exist (such as being cleared in a previous backup), oandbackupx will close and relaunch.
This is in the log:
`rm: /data/data/arun.com.chromer/cache/*: No such file or directory [Lynket]`

**Comment by machiav3lli** [comment]
Those are really to different bugs and both are fixed in the latest test builds. If everything goes fine, the next FDroid Release will include the fixes, this applies to #42 too.
