### ISSUE TITLE
[Help] Backed up data is encrypted even while encryption was off (empty password)

### ISSUE THREAD

**Issue by nulledone** [machiav3lli/oandbackupx#426]
So after 7 update it seems like encryption was turned on (maybe i mis-clicked or it turned on by itself), however I had not supplied any password. Is there a way to recover tar.gz.enc?

Additional info: 
I have backup of Oandbackup with TB, I can access previous "data/shared_prefs" folder.
Inside the XML 'string' "password" is empty.

**Comment by nulledone** [comment]
So, I've just found out that I really have set a password (even though I tried that password before opening this issue, failed to restore). You can close this issue now, but I have a question.

Would it be possible to restore data with only backup of "oandbackup" itself? Done with TB. Assuming that I really set no password (salting encryption is predefined I guess?)

**Comment by machiav3lli** [comment]
The encryption password is by itself kept encrypted in the shared_prefs using Android's key store, which makes it irrestorable.

**Comment by nulledone** [comment]
Okay thanks!
