### ISSUE TITLE
[Bug] app does not show under restore tab after uninstalling

### ISSUE THREAD

**Issue by Ahmedazim7804** [machiav3lli/oandbackupx#427]
I am using backing up apps to ftp using [Rcx app](https://github.com/x0b/rcx) , it works fine and i can backup and restore apps fine, but after uninstalling an app it longer shows it in restore tab and i cannot restore the app.
If i install the app again from playstore or somewhere else it start to show that app under restore tab again and i can restore data.

Although Everything works fine when i backup to phone's local storage.

Backup path
![Screenshot_20211112-200414685](https://user-images.githubusercontent.com/54241827/141484230-d3d42685-4da9-49ef-a6b9-a8ff30fd7d34.jpg)

Before Uninstalling app
![Screenshot_20211112-201046897](https://user-images.githubusercontent.com/54241827/141484711-37b87a13-b9a7-4596-b135-70b8996a6e3a.jpg)

After Uninstalling App
![Screenshot_20211112-200543034](https://user-images.githubusercontent.com/54241827/141485044-c5319497-dd2f-45e4-b07d-f2ce1c5670dc.jpg)
![Screenshot_20211112-201320272](https://user-images.githubusercontent.com/54241827/141485121-4dad0b86-ff7d-49d2-84e4-72354f7e707a.jpg)

Android Version : 10
Oandbackupx version : v7.0.0 (latest)
Rcx app version : v1.12.2 (latest)

**Comment by machiav3lli** [comment]
How does the filter/sort settings look like? And what about it in the main tab?

**Comment by machiav3lli** [comment]
Also the content of the folder "com.dv.adm" would be intrresting.

**Comment by Ahmedazim7804** [comment]
> How does the filter/sort settings look like? And what about it in the main tab?

Filter and sort settings are default

![Screenshot_20211125-134855995](https://user-images.githubusercontent.com/54241827/143404952-3c36db21-1f7a-4ae9-bada-2946d876caea.jpg)

Also in the main tab the app does not show.
Although if i remove the app from oandbackupx, it show as long as i dont refresh the app list.

![Screenshot_20211125-135301014](https://user-images.githubusercontent.com/54241827/143405347-848186b8-0fed-4eca-8e02-f829881fa061.jpg)

**Comment by Ahmedazim7804** [comment]
> Also the content of the folder "com.dv.adm" would be intrresting.

Contents of app folder are untouched by me, both folder contains apk and data tar.gz file.
![Screenshot_20211125-134923190](https://user-images.githubusercontent.com/54241827/143405528-7da07cd8-3bcc-436b-9006-b3f06e0217de.jpg)

**Comment by machiav3lli** [comment]
OK, so it seems you use a connected ftp server for the backups, what app/frameworks does this use?

**Comment by Ahmedazim7804** [comment]
> OK, so it seems you use a connected ftp server for the backups, what app/frameworks does this use?

Rcx app uses rclone.
and the ftp server is created by filezilla on pc, although that is not a problem i think because even on local remote or google drive remote the problem is same.

although it could be the problem with the app itself (https://github.com/x0b/rcx) as it is not actively maintaned, the last commit was on 9 july

**Comment by machiav3lli** [comment]
A lot of users has already reported problems using rcx at all (neither backup or restore works). This is the main difference I can see at your setup that may cause some issues.

Could you please try it using local storage directly.

**Comment by Ahmedazim7804** [comment]
> Could you please try it using local storage directly.

Do you mean local storage using rcx ?
Because without it, it works fine in local storage.

**Comment by machiav3lli** [comment]
With "directly" meant without rcx. But then this would mean that its definitely rcx causing this behaviour.

**Comment by Ahmedazim7804** [comment]
> With "directly" meant without rcx. But then this would mean that its definitely rcx causing this behaviour.

The problem is indeed with rcx.
i have tested oandbackupx with rclone-mount magisk module (https://github.com/AvinashReddy3108/rclone-mount-magisk), mounting the ftp remote on sdcard and apps shows after uninstalling.
