### ISSUE TITLE
Support legacy/old android versions 

### ISSUE THREAD

**Issue by c33s** [machiav3lli/oandbackupx#43]
as a backup app a possible usecase is to migrate data from an old phone to a new one. 

currently android 7 is required but old phones often have lower android versions, so it would be good to be able to install this app on lower android versions.

**Comment by machiav3lli** [comment]
Unfortunately this is not an option moving forward.

An alternative solution is to do the migration with OAndBackup(the old app) and then install and work with OAndBackupX.

Duplicate to #1
