### ISSUE TITLE
[Bug] "No Encryption" choice is not respected

### ISSUE THREAD

**Issue by quimup** [machiav3lli/oandbackupx#434]
**Description**

I choose to not use encryption. In the settings it is not checked and no password is entered. Every now and then (not every time) when I start the app it tells me I should encrypt my backups - and it does not take no for an answer (literally). It takes me straight to the relevant settings. It is a minor nuisance, but one that can easily be avoided. 

**Steps To Reproduce**

Do not enable encryption and start the app a couple of times.

**Expected behavior**

Offer encryption once. Allow 'no'. Respect that choice.

**System Information(please complete the following information):**

- Device: MOTO G5
- Android: 11
- ROM: LOS microg 
- App's Version: current

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by machiav3lli** [comment]
I understand your view, but encryption is the main source of security for backups and should be used as far as available in a standardized form. That's why this offensive for encryption won't stop.
