### ISSUE TITLE
[Bug] 6.0.1 > 7.0.0 settings migration fails

### ISSUE THREAD

**Issue by opusforlife2** [machiav3lli/oandbackupx#435]
**Description**

The app shows a toast saying "The filtered list is empty". This has happened in earlier upgrades as well, but I think you mentioned that app data needs to be reset in those cases. I read the changelog and didn't find any such instruction. It just says new backups will be incompatible with old releases.

**Steps To Reproduce**

1. Have 6.0.1 installed.
2. Update to 7.0.0.
3. Run the app after the update finishes.
4. The app opens, and then after trying to load the app list for a while, it shows the toast as mentioned.
5. Everything works after a data reset. It populates the list with the old backups as it should.

**Expected behavior**

The settings migration should work out of the box if it's not mentioned in the release notes that it will not.

If I had to guess, I think the bug happens because the sort and filter options from 6.0.1 don't cleanly translate to 7.0.0. If that is indeed the case, they should be removed automatically on first launch after the update.

**System Information(please complete the following information):**

- Device: Xiaomi Mi 5
- Android Version: 10
- ROM: LOS 17.1
- App's Version: 6.0.1, 7.0.0

**Comment by machiav3lli** [comment]
There's also the note that filter/sort system got reformed, which is exactly your issue. Sorry if this wasn't communicated enough

**Comment by opusforlife2** [comment]
@machiav3lli I see. As a user, it's not always obvious which change requires me to reset app data (like in this case). So a big bold alert at the top of the release notes would be great whenever this is the case. You've already done it for 2 items in 7.0.0. This was a 3rd item that should have been there, I think.
