### ISSUE TITLE
[Feature Request] Persistent notification for ongoing backup

### ISSUE THREAD

**Issue by opusforlife2** [machiav3lli/oandbackupx#436]
**Is your feature request related to a problem? Please describe.**

It's very easy to accidentally swipe away the ongoing backup notification along with the other batched notifications from completed backups, or a notification from another app. Then you can't know without opening the app whether a backup has completed or not.

**Describe the primer solution**

The ongoing backup notification should be made persistent/non-dismissable until the backup completes. After that it can be made dismissable.

**Comment by opusforlife2** [comment]
BTW, do you really need the Device info section in both the bug and FR issue templates? I think it can be removed from the FR template.

**Comment by hg42** [comment]
I think this should be fixed with #493
