### ISSUE TITLE
miui optimization 

### ISSUE THREAD

**Issue by skelletR** [machiav3lli/oandbackupx#445]
Hi, i have Xiaomi Poco X3 NFC MIUI EEA GLOBAL 12.0.8 stable android 10, i want to ask if this apps work properly with miui optimization enable, because now can't install split apps because of this feature is enabled, and I'm wondering if make a backup a split app with this app, after can restore and work normal? No broke phone or something like that?

**Comment by machiav3lli** [comment]
You have to disable miui optimizations, it's ruining installer functionality as reported by msny users

**Comment by skelletR** [comment]
> 

Oh, understand, thanks for answer, i hope in future updates of the app can with some way skip the miui optimizations even if it is enabled, and all work good
