### ISSUE TITLE
[Feature Request] Allow bypassing "Disable battery optimisation" at start screen

### ISSUE THREAD

**Issue by opusforlife2** [machiav3lli/oandbackupx#446]
**Is your feature request related to a problem? Please describe it.**

I don't use scheduled backups, so I have no need of this step.

**Describe the primary solution**

Going by the description of the step, it is needed only when the user enables scheduled backups. So, the app should disallow setting them up if battery optimisation is not disabled, and prompt the user.

**System Information (please complete the following information):**

- App Version: 7.0.0

**Comment by machiav3lli** [comment]
It's actually not only about schedules, eventuslly the app doesn't use wakelocks. Starting with A12 Android has a strict policy of running processes in the background, this permission is needed to allow reliable usage of OABX.

A12 seems to have even further restrictions even for apps with the permission, but it's clear that having the permission allows the app to be usable on A12 compared to without.

This was one of the developments I've foreseen and it seems it'll be just getting worse in A13 with a "credit system" for apps' background resources and though I would change nothing from my side.
