### ISSUE TITLE
Use OAndBackupX v.3 + v.7 to migrate from arm32 Android 7.1 to arm64 Android 11?

### ISSUE THREAD

**Issue by LeeBinder** [machiav3lli/oandbackupx#454]
Hi  machiav3lli and OAndBackupX community

I am aware the latest OAndBackupX running in Android 7 is [release 3.0.0](https://github.com/machiav3lli/oandbackupx/releases/tag/3.0.0) from Aug 04, 2020.

Would it be a sensible option at all to run OAndBackupX v.3.0.0 on my old Samsung with (rooted) 32bit ARMeabi-v7a (v7l) Android 7, move the backup over to my new phone with LineageOS 18.1 (rooted arm64 Android 11), and restore the backup there with the latest OAndBackupX 7.0.0?

Or would I run into issues most likely, and should rather use another backup/ restore & phone migration app like Swift Backup, the latest version of which runs in both of my Android versions, 7 and 11 (in contrast to the abandoned Titanium Backup)?

What's the smoothest way for the migration I need to perform?

Thanks for insights.

**Comment by machiav3lli** [comment]
Like the faq/changelogs state, OABX had at v3 & v4 big changes and newer versions aren't backward compatible. Backups with v3 aren't that reliable, but must be restored by the same version. After restoring you may update OABX to v7 (or v8 alpha, as with this new version we have some new breaking changes - at least for now)

**Comment by LeeBinder** [comment]
thanks @machiav3lli  - I had scrolled through the FAQ before I posted my question but obviously missed that part. Maybe it was too late at nite already ..

So here's what I'll do:
- create backups with both, OAndBackupX v.3 and latest Swift Backup
- on new phone, restore with latest Swift Backup
- test every app, and only in case of an app not having all its data/ settings, restore with OAndBackupX v.3

With what you shared, that seems like the most sensible workflow I'd say :)

**Comment by machiav3lli** [comment]
@LeeBinder Yeah it makes sense, but I guess v3 wouldn't be able to restore apps that may not get restored  on swift backup. Just be careful of your apps that use Android's KeyStore

**Comment by LeeBinder** [comment]
I appreciate your evaluation. Oh yes, the darn software-based keystore issue ..  I wish there was a root app that could import the keys from a keystore folder (/data/misc/keystore/user_0) backup created as root into the current keystore.
