### ISSUE TITLE
[Bug] Returns to top of app list after manual backup instead of returning to previous position in list

### ISSUE THREAD

**Issue by JohnCGH** [machiav3lli/oandbackupx#457]
After performing a manual backup, I am incorrectly returned to the top of the main app list instead of back at the same location I was at before backing up an app.

This is annoying because if I am exploring the backup details of apps one by one and making manual backups, I have to keep re-scrolling the main list to where I previously was before the jump to the top.

**Steps To Reproduce**

1. Scroll down to the middle of the main app listing
2. Select an app
3. Perform a backup of that app
4. Tap the android "back" button (or tap the \\/ button in the top right of the screen)
5. You are now at the top of the main app listing instead of the middle location that you were at before selecting the app

**Expected behavior**
After exiting the app's backup details, I would expect to be back at the same position in the main list as I was before.

Running Stock A10 on Pixel 4a (Magisk)

**Comment by ferraript** [comment]
voting for this, it's annoying like hell
and it's valid for manual restorations too

**Comment by machiav3lli** [comment]
#466 more comprehensive
