### ISSUE TITLE
[Bug] Search bar white text color produces low contrast with light colored accent colors

### ISSUE THREAD

**Issue by JohnCGH** [machiav3lli/oandbackupx#464]
**Description**
Selecting "bright" accent color in settings, results in poor contrast with white letters in search bar - making it difficult to see text entered.

**Steps To Reproduce**

1. Click the gear button in bottom right corner of main tab
2. Select "Accent Color" of "Turquoise"
3. Click the search magnifying glass icon in top right
4. Type some text

**Expected behavior**
To be able to clearly see the search text typed.

Instead, the default text color of white offers little contrast with the Turquoise background color.

NOTE: The above description is when using the "Dark Theme" of the app. If you use the "Light Theme", then the opposite happens (the search text is now black and produces good contrast text, but then the bottom icons like the Home icon now have poor contrast)

However you will notice that the line color for the "Home" tab on the main screen is black color, so there is very good contrast with the Turquoise color.

So, for light colored accents, please change search text color (and the color of the search magnifier icon) to black so there is good contrast for the text and icon.

**Comment by machiav3lli** [comment]
Some colors generally don't work out good together. For now nothing will change as there's already enough color options to avoid this. Later on using Material You/Monet engine, should allow easier theming
