### ISSUE TITLE
[Feature Request] Display suggestion to enable Encryption just once, not every 4-5 times the app is ran

### ISSUE THREAD

**Issue by JohnCGH** [machiav3lli/oandbackupx#467]
**Is your feature request related to a problem? Please describe it.**
When I launch the app, it will often display a suggestion to enable encryption. And it displays this suggestion every 4-5 times I run the app.

But I don't want to enable encryption, so these pop-up warnings are not wanted.

**Describe the primary solution**
Please modify suggestion so it will just pop-up once.

**Comment by machiav3lli** [comment]
Nope!

**Comment by JohnCGH** [comment]
I think we might be thinking two different things...

Are you saying that even if a user does not want to turn on encryption, you still want to keep bugging the user to turn on encryption every 4-5 refreshes of the app list - and do this forever?

**Comment by machiav3lli** [comment]
First of all it's each 10 launches. Otherwise maybe I'll add an option to disable this repeatative notification. But I won't reduce it to only the first launch.

**Comment by JohnCGH** [comment]
Excellent!
