### ISSUE TITLE
[Bug] "View the Log" displays blank log screen

### ISSUE THREAD

**Issue by JohnCGH** [machiav3lli/oandbackupx#468]
**Description**
If I go into the settings tab and select the wrench icon, the bottom option is "View the log", but if I click on that selection, no log entries are displayed.

**System Information(please complete the following information):**

- Device:  Pixel 4a
- Android Version:  10
- ROM: stock 
- App's Version: 7.0.0

**Comment by machiav3lli** [comment]
Only logs that you specificely choose to kept and saved, and will be found there.
