### ISSUE TITLE
[Feature request] Multiple backups of the same app

### ISSUE THREAD

**Issue by SleeplessSloth** [machiav3lli/oandbackupx#47]
Right now, as far as I can see, it's only possible to have one single backup at one time. The file structure is like so

```
OAndBackupX/app/app.zip
OAndBackupX/app/app.log
```

What if we just created numbered directories that contain the backups, something like this

```
OAndBackupX/app/1/app.zip
OAndBackupX/app/1/app.log
OAndBackupX/app/2/app.zip
OAndBackupX/app/2/app.log
...
OAndBackupX/app/99/app.zip
OAndBackupX/app/99/app.log
```

To make it easier to see which backup is which we could show the date the backup was created in the UI (like it already does but show them as a list instead) or even add an optional "Description" field to the log file.

To keep the app backwards compatible, we could check if the numbered directories exist, and if they don't, move the content of `app/` to `app/1/`

What do you think?

P.S. Why are the files .log if they just contain json data? Why not .json?

**Comment by machiav3lli** [comment]
Good Idea, I'll consider it in the coming rebasing. Otherwise it'll be a hell of chaos and time consuming to implement it.

On the P.S. I still didn't work that much on the topic of the log, leaving it as-is for the meanwhile isn't problematic. But this'll change later, when the added functions are already stable and the migration topic is disclosed.

**Comment by opusforlife2** [comment]
From #75:
> It would be super helpful if new attempts at backing up an app would not touch the previous backup files, but make new backups instead. At least on version 1.2.0 (F-Droid), the app is still very buggy and crashes often when making backups. This can lead to a single corrupt backup which can no longer be used to restore the app in case anything goes wrong. Along with that, the option to delete previous backups could be there, though that can be done manually through a file explorer, so it's not that big of a problem.
