### ISSUE TITLE
[Bug] Installing new app does not trigger "new" popup notification

### ISSUE THREAD

**Issue by JohnCGH** [machiav3lli/oandbackupx#473]
**Description**
If I have the sort and filter set to "Launchable Apps" and if I upgrade an *existing* app, OABX will then properly pop-up a notification to remind me that a newer version of one of more apps has been installed, but there is NO backup currently for it - which is a good thing so I'll know to create a backup for it.

However, if I install a new app (that was never before installed on this device, so there are no existing backups for it), OABX will NOT pop-up any notification reminding me that a new app has been installed and there is NO backup for it.

**Steps To Reproduce**
1. Set "sort and filter" to select "Launchable Apps"
2. Install an update to an existing app - you will see a "new" pop-up notification.
3. install a new app - you will NOT see a pop-up notification.

**Expected behavior**
I would expect the app to display the "New" notification so it will remind me (just like it does for an upgraded app) that a new app has been installed and there currently is no backup of it.

**Comment by machiav3lli** [comment]
Cause this would be too redundant if applied to all apps not having backup and just bloat the screen. You can use the filter new & updated to catch those.
