### ISSUE TITLE
[Bug] It can't be installed on Lineage OS 14.1

### ISSUE THREAD

**Issue by gerroon** [machiav3lli/oandbackupx#491]
**Description**
I tried to install v7 and v6 on Lineage OS 14.1 Arm and it crashes right away.

**System Information(please complete the following information):**

- Device: Samnsung Note
- Android Version: 14.1
- ROM: Lineage OS
- App's Version:  7.0

**Comment by tsiflimagas** [comment]
That's not a bug, actually. The minimum supported SDK is 28 (Android 8) since v3.1.0.

**Comment by gerroon** [comment]
Is there any reason why the API version can't  be lowered?

**Comment by machiav3lli** [comment]
@gerroon maintainability, as supporting A8 which ToyBox's version doesn't support the essential functions we use. OAB had a submodule written to compensate that and became unmaintainable.
