### ISSUE TITLE
[Bug] App crash while opening

### ISSUE THREAD

**Issue by Mannshoch** [machiav3lli/oandbackupx#498]
**Description**
Fresh installed Lineage OS19 / Android 12
After Installing OAndBackupX the App imediately close after starting the app.

**Steps To Reproduce**

1. Install
2. Open
3. Crash

**Expected behavior**
The Application Open

**System Information(please complete the following information):**

- Device: SM-G930F
- Android Version: 12
- ROM: [LineageOS 19 ](https://forum.xda-developers.com/t/lineageos-19-0-android-12l-signature-spoofing-ota-updates-for-s7-exynos.4368995/)  
- App's Version: 7

**Comment by machiav3lli** [comment]
Do you have Magisk and gave OABX the root permission?

**Comment by Mannshoch** [comment]
Yes. Like always. 
For the record I do not anymore use LOS 19 I whiped again and installed [LOS 18](https://forum.xda-developers.com/t/rom-stable-signature-spoofing-microg-support-ota-updates-lineageos-18-1-for-s7-exynos.4172749/). That work.
