### ISSUE TITLE
oab-utils should not follows symlinks

### ISSUE THREAD

**Issue by gamax92** [machiav3lli/oandbackupx#5]
oab-utils will follow symlinks which can break some applications on restore. For example: if the application data has a lib symlink, it will follow it which leads to broken ownership and permissions for /data/app/(package)-1/lib/(arch), which may cause the application to malfunction or be considered not installed.

**Comment by gamax92** [comment]
Uhh, is this fixed? I don't see any code changes to oab-utils

**Comment by machiav3lli** [comment]
I removed following symlinks altogeather from the app. Doing the clean up in oab-utils will follow later, along with some other changes thought for the utils.
