### ISSUE TITLE
Cannot restore due to INSTALL_FAILED_VERIFICATION_FAILURE

### ISSUE THREAD

**Issue by Tiefkuehlpizze** [machiav3lli/oandbackupx#52]
As discussed in the Telegram group, restore of Spotify does not work.
I've added some log statements to see what's going on and I found this.

```D/OAndBackupX.CommandHandler: command: toybox cp "/storage/emulated/0/OAndBackupX/com.spotify.music/base.apk" "/data/local/tmp/1592832328710.apk"
D/OAndBackupX.CommandHandler: command: pm install -r /data/local/tmp/1592832328710.apk
D/OAndBackupX.CommandHandler: command: toybox rm -r /data/local/tmp/1592832328710.apk
W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8960.so from current namespace instead of sphal namespace.
D/OAndBackupX.CommandHandler: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]
I/OAndBackupX.BackupRestoreHelper: com.spotify.music backup contains split apks
D/OAndBackupX.CommandHandler: command: toybox cp "/storage/emulated/0/OAndBackupX/com.spotify.music/split_config.arm64_v8a.apk" "/data/local/tmp/1592832338402.apk"
D/OAndBackupX.CommandHandler: command: pm install -p com.spotify.music -r /data/local/tmp/1592832338402.apk
D/OAndBackupX.CommandHandler: command: toybox rm -r /data/local/tmp/1592832338402.apk
D/OAndBackupX.CommandHandler: Failure [INSTALL_FAILED_INVALID_APK: Missing existing base package for com.spotify.music]
D/OAndBackupX.CommandHandler: command: toybox cp "/storage/emulated/0/OAndBackupX/com.spotify.music/split_config.de.apk" "/data/local/tmp/1592832344321.apk"
D/OAndBackupX.CommandHandler: command: pm install -p com.spotify.music -r /data/local/tmp/1592832344321.apk
D/OAndBackupX.CommandHandler: command: toybox rm -r /data/local/tmp/1592832344321.apk
I/zygote: Background concurrent copying GC freed 24144(1369KB) AllocSpace objects, 7(140KB) LOS objects, 49% free, 3MB/6MB, paused 91us total 157.363ms
D/OAndBackupX.CommandHandler: Failure [INSTALL_FAILED_INVALID_APK: Missing existing base package for com.spotify.music]
D/OAndBackupX.CommandHandler: command: toybox cp "/storage/emulated/0/OAndBackupX/com.spotify.music/split_config.xxhdpi.apk" "/data/local/tmp/1592832346291.apk"
D/OAndBackupX.CommandHandler: command: pm install -p com.spotify.music -r /data/local/tmp/1592832346291.apk
D/OAndBackupX.CommandHandler: command: toybox rm -r /data/local/tmp/1592832346291.apk
D/OAndBackupX.CommandHandler: Failure [INSTALL_FAILED_INVALID_APK: Missing existing base package for com.spotify.music]
I/OAndBackupX.ShellCommands: restoring: Spotify
```

It might be related to the `verifier_verify_adb_installs` setting. I cannot execute the needed `pm install` command via adb until I switch it off.
```
$ settings get global verifier_verify_adb_installs
0
```

Command to switch it off.
```
$ settings put global verifier_verify_adb_installs 0
```

**Comment by Tiefkuehlpizze** [comment]
Seems like there is a switch that must be **turned off** in order to restore apps! 

![image](https://user-images.githubusercontent.com/5569743/85304083-9e82c900-b4ab-11ea-8f11-61ede81d4ca7.png)

**Comment by Tiefkuehlpizze** [comment]
Another update: It might have to do with the verification intent. See (here)[http://irq5.io/2014/12/01/android-internals-package-verifiers/].
It seems to check the APK. Usually this is done by `com.android.vending`.
I cannot tell at the moment if it is really verifying something, if the APK is somehow suspicious to the verification service or one of these functions go a unexpected route: [PackageVerificationState.java](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/pm/PackageVerificationState.java#83), [PackageManagerService.java](https://android.googlesource.com/platform/frameworks/base/+/e639da7/services/java/com/android/server/pm/PackageManagerService.java#747).

```
$ dumpsys
…
Verifiers:
  Required: com.android.vending (uid=10017)
…
```

For now I would suggest to check if the the verification is set to off.
Option A would be, that oandbackupx tells the user to change the setting, to do restores.
Option B would be, that oandbackupx offers the user to change the setting.
Option C would be, t hat oandbackupx offers the user an option to change the value when needed and change it back, when done.

I would never change this setting without the user's permission. It's a device security relevant setting. It would always need a second grant (adb authorization or root permission to move an apk file to `/data/user/tmp` where the package manager can read it), but the user should be aware.

My personal preference would be option C. It is least annoying for the user and only offers attack surface during the time, the app is restoring.

**Comment by machiav3lli** [comment]
I'd prefer c also.

**Comment by yelworc** [comment]
Had the same issue with Youtube and Street View. Would have never thought of the "Verify apps over USB" setting without searching for the error message in the repo, and ending up here.

**Comment by Smojo** [comment]
Is this still an issue? At least Spotify restore works fine for me. (v3.2.0, A9/LOS16)

In addition it was mentioned (in the Telegram) that it fixed some issues, when not just turning of "Verify apps over USB", but also enable "USB debugging".
