### ISSUE TITLE
[Feature Request] Tags for Batch action

### ISSUE THREAD

**Issue by Cyberavater** [machiav3lli/oandbackupx#54]
Mark and Tags are very useful for batch action,

**Comment by machiav3lli** [comment]
Can you please elaborate more?

**Comment by Cyberavater** [comment]
Mark- Ability to select multiple apps. 
[Would be visible via a tick mark or blocked as selected can be triggered via holding an app]

Tags- A set that's already marked based on their nature and type.
[Tags names will be displayed will be displayed in a colour box on an app if it's under any]

Additional info on tags;
1. Some tags are auto-generated and labeled
-System (System Apps)
-User (User Apps)
-Recently updated (If an app has been updated in last 3 days)
-Updated Data (If an already backed-up app has updated data)
-New Data (if the app data was wiped and the user didn't restore it before using it)

2. Some tags are manually labeled
-Ignore default setting ( It'll ignore default setting and follow it's own settings (which will be configurable via setting) when committing any actions, i.e. default settings for all apps are to backup with external data but if an app is under this tag it would follow its own rule and may not backup external data depending on it's won settings)

3. One app can be under many tags (But not under conflicting tags).

4. Different tags will be in different colors.

5. In batch commands, one can both include and exclude different tags.

6. Some tags will be automatically added to excluded (i.e. "New Data", this would help the user to not replace his actual with new empty data). (this is mostly the case when the user installs a new rom and backups apps from google backup at first launch).
-Tho the user can manually remove it from the excluded list.

7. All information & elaboration about tags (such as this one) will be available in the help menu. (Which will be prompted on the first run to check out).

P.S. I'll add more info and update the comment if I find any new idea.

P.P.S. If you have any questions about the automatic detection/labeling method you can ask me and I might be able to help you with that. (in ENGLISH WORDS! as I'm no coder).

**Comment by machiav3lli** [comment]
Mark is already there and Tags can be seen as a filter, which is also already there. The only new thing could be a custom tag creation. 

Tags clutter the simple UI and can be more disturbing than helping in this sense. There's already UI indicators implemented for each app (packagename text color for system/user/uninstalled, backup's mode or if it's updated) and as said above the filters are there to work in the same logic. I don't see the positives overweighing the effort(and the negatives) in anyway.

Other way to look at it is as a suggestion to restructure the filters' system. Which is already done in the latest 1.3.0 test builds (can be downloaded from TG & Riot groups). Please take a look there and reflect on the changes.

**Comment by Cyberavater** [comment]
First of all, sorry that I didn't properly check before reporting the issue, Mark is already available.

2nd, I downloaded 1.3.0 rc3 from telegram. And, sadly it doesn't fill the requirements, as if it was tags, the user could include multiple of them and excludes some apps that fit under another tag (common app).

3rd, I agree that tags might clutter the simple UI but I believe it will be more useful for most users. So, possible solutions are;
1. Shortening tag name in the UI for visual ease (as 'sys' for the system apps (User can check, all information & elaboration about tags in the help menu)
2. A toggler so the user can see the tags.

Lastly, not all auto tags I suggested is available as filter.

**Comment by machiav3lli** [comment]
On the last point on auto tags. Comparing the stored data to figure out if the app has "new data" or "updated data" is no viable option, considering performance and logic. While updated is already there, "recently
Updated" doesn't make sense, while when it's about knowing about old backups there's already such an Option which is configurable.

Otherwise I'll reconsider how the filters' system is structured and if it fits in the performance profile I'll switch to tags-like filters.

**Comment by Cyberavater** [comment]
Okay, I guess that will do, since those auto-tags are unfeasible. But plz consider switching to tag-like filter.

**Comment by Cyberavater** [comment]
In Titanium Backup there was a batch task to, "Redo backup for modified data", it would skip apps which data wasn't modified. So, an auto tag for that (Modified data) should be preferable here.

P.S. Don't get me wrong I just can't properly report cuz I don't use it because of it's missing SD support. But I _am_ keeping an eye on it for that update (as Titanium Buckup is outdated too).

**Comment by machiav3lli** [comment]
As mentioned in the last comment recently updated doesn't make any sense to me. 

Apps and their data are more active today than as TB was developed. For instance, whenever you open an app today the cache change. meaning generally that only apps that you didn't open since last time and don't do anything in the background have "static" data.

**Comment by Cyberavater** [comment]
If opening an app modifies the data then be it.
Well, take it for a game, two games actually, moke some progress for both games, then backup, the next day you didn't play the 2nd game only the first game, So for next schedule cloud update it would only make and upload data for the 1st one (and skip the 2nd on its own). Which is preferable considering time, phone charge, and data bandwidth.

I know TB is old but it's not that outdated, Last update was 24 Nov 2019, The only reason I'm not happy with it because of it's missing split-apk support other than that it's the best backup tool you can get even now!
