### ISSUE TITLE
Unnecessary errors logged when clearing already-empty cache

### ISSUE THREAD

**Issue by roertel** [machiav3lli/oandbackupx#57]
While performing a backup of all apps, if the backup fails, there are lots of errors in the displayed log about "AnySoftKeyboard: rm: /data/data/com.menny.android.anysoftkeyboard/cache/*: No such file or directory".

** Solution could be to add '-f' (force) flag to "rm -r " in src/main/java/com/machiav3lli/backup/handler/ShellCommands.java for all rm commands so that it performs an "rm -rf" instead.

**Comment by Tiefkuehlpizze** [comment]
When changing to libsu in #55, I've optimized the shell command to check, if there is something to delete. 
If not, it won't produce an error. :smiley: 

I'm hunting these error messages at the moment.

**Comment by machiav3lli** [comment]
Please use the latest 1.3.0(IzzyOnDroid and GH Releases) to avoid those errors. This release possibly won't be pushed to FDroid.

**Comment by 5c0tt-b0t** [comment]
whilst I use Izzy's repo, may I ask... why no F-droid release?
Are you now including non-free components?  trackers? ads? bug collection?

**Comment by machiav3lli** [comment]
No, just this release, as PR to update the app takes sometimes weeks to be merged, while starting from the next release (will be in less time) auto updating from FDroid will be possible and so, it's just saving some time for the guys there, as current manual building is kinda painful (needs rust to build oab-utils).
