### ISSUE TITLE
[BUG] Issue when selecting SDCard for backup folder

### ISSUE THREAD

**Issue by MikuDroid** [machiav3lli/oandbackupx#60]
![Screenshot_20200630-023526_OAndBackupX](https://user-images.githubusercontent.com/22476406/86048367-9d890300-ba7a-11ea-99e6-0e0ba16271bd.png)
![Screenshot_20200630-023700_OAndBackupX](https://user-images.githubusercontent.com/22476406/86048370-9f52c680-ba7a-11ea-928d-74a004295f6c.png)

As the title said, it's borken here. Tried to select the folders instead of root of sdcard, same issue. Iirc OG oandbackup is able to backup to sdcard. [Here's the log.](https://del.dog/Oandbackupx)

**Comment by machiav3lli** [comment]
Duplicate #32
