### ISSUE TITLE
"Granted rights" message covers functional buttons

### ISSUE THREAD

**Issue by mahdi1234** [machiav3lli/oandbackupx#61]
It would be good to move functional buttons in the app from bottom because those are blocked by root popups (and there's really many of them) which renders app unusable for some time.

![granted](https://user-images.githubusercontent.com/1097047/86497652-0241a780-bd72-11ea-8332-bbd5f50c6681.png)

**Comment by machiav3lli** [comment]
This is already fixed in the 2.0.0 test builds. Release will be already this weekend(today or tommorow)
