### ISSUE TITLE
[Fix] Set default OBB/external data backups as off. [Feature] Sort by App/Data size

### ISSUE THREAD

**Issue by Madis0** [machiav3lli/oandbackupx#63]
While having selected APK+data backup and starting to back up apps, users may notice longer backups on apps with bigger data (games, browsers). For those, the app could add a button to skip app data and just back up the APK if it has taken long enough (10 seconds+).

**Comment by machiav3lli** [comment]
Thanks for suggestion. Actually this is for the most part not possible, as the copy process is queue-like so providing a cancel button is a nightmare when counting everything that can go wrong. 

There's always the options in the settings to not do external/obb data backups(which are for the most part, where the huge data is stored).

**Comment by Madis0** [comment]
In that case maybe indicate the external/OBB data icons in the list somehow?

**Comment by machiav3lli** [comment]
If you mean the batch list, I'd prefer not to clutter it with more info. If it's about the Main one, the AppSheet already has info about how big are those files(Data & Cache sizes).

On other topic. Thanks for the MR.

**Comment by Madis0** [comment]
How about sorting by app, data or both sizes?

**Comment by Tiefkuehlpizze** [comment]
I've noticed the issue as well. My recommendation would be, to disable the backup of external data. 
The data is doesn't seem to be too important (some games store some gigabytes of resources on the SD card and download them on the first run), my dictionary app stores it's offline dictionary there, Spotify seems to have a cache there.
Really nothing, you need to backup. Most of the things can either be copied from sdcard to sdcard or redownloaded. If I know, that I'm going to flash a new ROM, I'm usually using doing my TWRP backup, App backup and then copy the whole storage with `adb-sync` to my computer. In reverse.

I would also prefer to select per app, what I want. Similarly to how AFWall is handling rules for different networks. But it's a bit contradicting with the current design of the app. But I would definitely like to see a more advanced UI in the future.


![AFWall Screenshot](https://lh3.googleusercontent.com/W2fTgB1Ho52F5iK7GYWknd1B-mCCLeEHJYK4xviWxQSo63haZmYoWehJ8kbwwMyi3a4=w1440-h2406)

**Comment by machiav3lli** [comment]
As soon as this semester is over, I'll be rethinking the UX and functionality. For now I think there could be a solution to support SD. But I'll be waitig your MR and see how it eventually looks with the exams and private time.

**Comment by machiav3lli** [comment]
@Madis0 this's doable
