### ISSUE TITLE
If the app is running in the background it doesn't force close the app in question

### ISSUE THREAD

**Issue by Cyberavater** [machiav3lli/oandbackupx#65]
https://github.com/jensstein/oandbackup/issues/280

TB prompts to close the app (which is being restored) on the background.

**Comment by machiav3lli** [comment]
It's designed so, as I take - looking at the performance the devices we have today - when using the app to backup or even in background, the chances for groundbreaking changes in the data to happen are very thin

**Comment by Cyberavater** [comment]
Well, I tested it, when you open the app from the minimize bar it's stuck, then you need to close it and open it anyway.

**Comment by Cyberavater** [comment]
Irrelevant feature.
