### ISSUE TITLE
Restore doesn't work for some apps

### ISSUE THREAD

**Issue by Cyberavater** [machiav3lli/oandbackupx#66]
Eg: imo

**Comment by Tiefkuehlpizze** [comment]
Can you give some more detailed information? Is it com.imo.android.imoim (Imo for Videocalls)?
What version are you using, is there any error displayed? Anything from adb?

**Comment by Cyberavater** [comment]
> Can you give some more detailed information?

A. Sure

>Is it com.imo.android.imoim

A. Yes.

>What version are you using,

A. Latest, just download from Gplay

>is there any error displayed?

A. No, it says imo restored. while in reality, it isn't

>Anything from adb?

A. I'm a general user, might need help to get that.

**Comment by Cyberavater** [comment]
Note, it seems to be a Split-Apk. That's why TB doesn't support it as well.

**Comment by Tiefkuehlpizze** [comment]
Okay next round: What version of OABX are you using? The most recent development version (probably the alpha distributed via Telegram Channel) successfully restores the app.

As workaround for SplitAPKs, you can either rely on OABX to restore the apks and Titanium Backup to restore the data, if you don't want to download the apps from Play store manually.

**Comment by Cyberavater** [comment]
>Okay next round: What version of OABX are you using? The most recent development version (probably the alpha distributed via Telegram Channel) successfully restores the app.

A. Latest from F-droid. I'll switch to alpha now. Thanks!

PS. I'm keeping this open till the next stable update, just close it after that.
