### ISSUE TITLE
[Bug] You need to restart oandbackupx in order to restore the app you just backed up.

### ISSUE THREAD

**Issue by Cyberavater** [machiav3lli/oandbackupx#68]

**Comment by Cyberavater** [comment]
So, was it intended?

**Comment by machiav3lli** [comment]
Didn't provide any info, while I couldn't reproduce it.

**Comment by Cyberavater** [comment]
No info needed the title is long enough to explain it. You sure you couldn't reproduce it?

**Comment by machiav3lli** [comment]
Yes, I can backup-uninstall-restore from within the app no problem. Can you reproduce it then report it with more info.
