### ISSUE TITLE
[FEATURE REQUEST] Add compatibility with Work profiles

### ISSUE THREAD

**Issue by TheEvilSkeleton** [machiav3lli/oandbackupx#69]
~~May you add compatibility with [Work profiles](https://developer.android.com/work/managed-profiles.html)?~~

May you add a feature that lets the user backup and restore apps in and to (respectively) a [Work profile](https://developer.android.com/work/managed-profiles.html) while being on the main profile? By that, I mean: you use OandBackupX on your main profile to backup apps that are *in* your Work profile, and restore apps *to* your Work profile

**Comment by Tiefkuehlpizze** [comment]
Doesn't the work profile act as user on the phone?

This could be hard to implement otherwise, because a dev would need a device with a work profile. 
May I ask about your use case? Having your business phone rooted is a security nightmare for your company.

**Comment by TheEvilSkeleton** [comment]
I only root as a hobby. I often use Work profiles for privacy purposes and I often clean flash custom ROMs. I don't *need* the feature, but I do admit that I would really want it.

Since you said it's going to be hard to implement, I do not mind dropping it. It was a just a feature request but I value your time more

**Comment by Cyberavater** [comment]
It should support automatically given your work profile can grant the necessary permission. (I tried it once with a different backup app long ago). You can use Island (https://play.google.com/store/apps/details?id=com.oasisfeng.island) to set things up for you easily.

**Comment by Tiefkuehlpizze** [comment]
It's not like I wouldn't want to implement this feature. I just don't know, how to get the technical details and testing environment for Work profiles. I tried to find something about Work profiles, but all I found were some companies offering this service and how to disable the work profile for vacation…

**Comment by Cyberavater** [comment]
You should be able use Island to setup work profiles easily.

**Comment by Tiefkuehlpizze** [comment]
Ahh I misunderstood the idea of the app. It seems to work. It seems to be as assumed: The work profile is a separate directory:
```serranolte:/ # ls -l /data/user                                                                                                                                                                                                                              
total 8
lrwxrwxrwx   1 root   root     10 2020-07-08 23:41 0 -> /data/data
drwxrwx--x 152 system system 8192 2020-07-13 10:20 10
```
If it's possible to figure out which users have which apps installed, it might be easy on the backend. On the Frontend, it needs some concepts, when and how it asks about the user.

So I would summarize it as improved multiuser support.

**Comment by TheEvilSkeleton** [comment]
> It should support automatically given your work profile can grant the necessary permission. (I tried it once with a different backup app long ago). You can use Island (https://play.google.com/store/apps/details?id=com.oasisfeng.island) to set things up for you easily.

I use [Insular](https://gitlab.com/secure-system/Insular) (de-blobbed Island) to set my work profile up, and I've been using that a while now

**Comment by TheEvilSkeleton** [comment]
> It's not like I wouldn't want to implement this feature. I just don't know, how to get the technical details and testing environment for Work profiles. I tried to find something about Work profiles, but all I found were some companies offering this service and how to disable the work profile for vacation…

LMAO. I think this should help you: https://developer.android.com/work

**Comment by TheEvilSkeleton** [comment]
> You should be able to use Island to setup work profiles easily.

That is what I use (https://github.com/machiav3lli/oandbackupx/issues/69#issuecomment-657699872). My question was if there could be a feature that allow the user to backup and restore apps from Work profiles

The only workaround I've found was to install OAndBackupX in the Work Profile, and you can backup and restore from there, but the problem is that once the Work profile gets wiped, all the backups are gone.

**Comment by Cyberavater** [comment]
You can create symlink on Island to a permanent directory. So, the problem is to support symlink, _I think_.

**Comment by TheEvilSkeleton** [comment]
Shall I open this issue? I'm assuming it's going to be worked on

**Comment by Iey4iej3** [comment]
> The only workaround I've found was to install OAndBackupX in the Work Profile, and you can backup and restore from there, but the problem is that once the Work profile gets wiped, all the backups are gone.

If your main profile gets wiped, all the backups are gone as well. I think that separate profiles are isolated. The apps of one should not access the resource of the other in general.

**Comment by 07416** [comment]
Is restoring (and backing up) the work profile currently supported? I would love a clear separation between the profiles, like when [disabling apps](https://github.com/machiav3lli/oandbackupx/issues/97).

**Comment by poelzi** [comment]
I don't think the work profile support is working as it could be.
Visible tags in which profile it is installed. Restore of backup into a specific profile. Sort & Filter support.
I can not even install neo-backup in my work profile and restore a app. It complains of root required.
