### ISSUE TITLE
Restored backups are installed to Work Profile as well [Shelter]

### ISSUE THREAD

**Issue by kartikynwa** [machiav3lli/oandbackupx#7]
When an app is restored from a backup, it is installed to the Work Profile even if the app wasn't originally installed to the Work Profile.

I am using an app called Shelter to make use of the Work Profile feature in case you would like to test this behaviour.

For reference, Titanium Backup doesn't do this.

**Comment by machiav3lli** [comment]
Thanks for reporting it, I'll see into it. Meanwhile,
could you try test this with different settings of Shelter.

**Comment by kartikynwa** [comment]
Shelter doesn't have any setting that would help with this.

**Comment by talk2g** [comment]
I m on island and instead of restoring the backup on my primary profile ,it is doing it in work profile only..
Are u getting it restored on work only or in both the profiles?

**Comment by kartikynwa** [comment]
Both.

**Comment by talk2g** [comment]
In my case , its installing only in work profile..tried using both shelter and island
