### ISSUE TITLE
[Bug] Doesn't backup with .odex changes AND activity changes

### ISSUE THREAD

**Issue by Cyberavater** [machiav3lli/oandbackupx#70]
More info: https://www.luckypatchers.com/faq/ [F3>'17. What Does ODEX In Lucky Patcher Mean?']

While you're at it also add a feature to support backing up with 'Disabled Activity' [Useful if you disabled ads activity and want to backup the ad-free version]

**Comment by Tiefkuehlpizze** [comment]
It's by nature of the backup. OABX copies the apk files Android stores (seem to be the original files) and for restore, it asks the package manager to install the app again.
If I get it right, the odex can be found in the `oat` directory next to the apk.

I'm not sure how much change of the system these files can stand, but I guess it could be offered as an option to backup these as part of the app backup and restore them after the package manager is done installing an apk.
The use case should be similar to the permissions stuff and would offer a all in one round restore for everyone who flashes ROMs more frequently.

```serranolte:/ # ls -l /data/app/cc.dict.dictcc-jL-lj8ZQ6D5rVUaw1T9AXg\=\=/oat/arm/
total 3540
-rw-r----- 1 system all_a129   86016 2020-07-10 11:09 base.art
-rw-r----- 1 system all_a129  228680 2020-07-09 08:50 base.odex
-rw-r----- 1 system all_a129 3308240 2020-07-10 11:09 base.vdex
```

Don't take this as promise, I'm just analyzing a bit, and I'm currently taking a break from developing. But keep on going with these ideas, I think it's good to know, what contents would make sense in a backup. At the end we could assemble a roadmap.

**Comment by Cyberavater** [comment]
.odex changes _makes_ a big difference.  It can make a free app paid app, It can make ad-infested app ads-free and many modifications to an app. (Someone who has experience with Luckypatcher knows all these).

TB automatically backs-up with .odex changes without even telling anything about it to the user (as it should be!)

**Comment by Cyberavater** [comment]
This is actually 2 issues.

**Comment by bengalih** [comment]
I'm not sure if this is required/priority.  LP allows you to repackage the apk with changes integrated, which is in almost all respects superior to simply patching the ODEX.  Why not just repackage the APKs you modify and save them either out of band or have OABX back those up instead?  Odex changes are lost on version upgrades anyway, so if you are modifying an app you are going to have to ensure you are running on the same version (i.e. prevent upgrades) anyway.

**Comment by Cyberavater** [comment]
Bad idea, I've tried a full restore and it seems the app recreates odex ignoring the existing odex.
