### ISSUE TITLE
[BUG] Restore apps list is always empty.

### ISSUE THREAD

**Issue by githammerer** [machiav3lli/oandbackupx#73]
ROM: Xiaomi.eu 11.0.7.0 PCOCNXM
Device: Redmi Note 8 (ginkgo)

Reproduction steps:
1. Backup an app
2. See that in the App List backup is available with date 1 Jan 1970 07:30:00
3. Go to Restore App screen
4. App list in empty as picture related.
![Screenshot_2020-07-20-13-26-42-080_com machiav3lli backup](https://user-images.githubusercontent.com/67651196/87903009-a07d7f00-ca8d-11ea-84ce-283d881eb5fa.png)

**Comment by machiav3lli** [comment]
Is this app-agnostic? As it seems the app isn't getting backed up or something is going wrong in this step. How does your root(magisk) setup look like?

**Comment by machiav3lli** [comment]
And from what version you're reporting?

**Comment by githammerer** [comment]
version 2.0

The app does get backed up.

Magisk is just normal install, aside of KEEPVERITY=false.

**Comment by machiav3lli** [comment]
Was it updated from a previous version or installed anew? What magisk modules do you have? Do you know if MIUI(.EU) has toybox removed? 

And no the backup isn't fully functional if the backup date is saved as 1 Jan 1970.

**Comment by githammerer** [comment]
No, I regularly use toybox getfattr and toybox setfattr.

I suspect if this is reproducible with a stray dot folder, example if you use Syncthing, it does put .stfolder in each synced folder, which I use to offload my backups to my PC.

**Comment by machiav3lli** [comment]
I use syncthing for my backup folder same as you and considering how many times I change my ROM and with that clean the storage(I don't disable encrypted storage) re-creating backup folder and .stfolder it has nothing to do with dot files.

**Comment by machiav3lli** [comment]
Could you please test the behavior on an AOSP-ROM?

**Comment by githammerer** [comment]
Unfortunately I don't expect myself to test the behaviour on an AOSP-based ROM as this will take a significant chuck of my time.

I'm closing this due to bug/issue tracking non-commital on my part.

Thank you very much for responding.

**Comment by machiav3lli** [comment]
Sorry for that, I'll reopen it in the future if this get reported again with more information. otherwise I'll try in the future to ease the reporting process with the full informations.
