### ISSUE TITLE
Not being able to select Data backup only

### ISSUE THREAD

**Issue by gcoimbra** [machiav3lli/oandbackupx#78]
If I try to select only Data backup in the scheduling option, it stays APK + Data.

**Comment by machiav3lli** [comment]
On which version are you? Thanks

**Comment by gcoimbra** [comment]
Sorry for the delay. 
I'm on 1.2.0-universal.

Thank you. First developer who was polite and patient while addressing issues.

**Comment by machiav3lli** [comment]
This is actually fixed since 2.0.0. The latest version 3.0.0 got already merged on FDroid, it'll be on the next repo update. You're welcome.

**Comment by gcoimbra** [comment]
Strange. Even after a successful repo update, fdroid still shows 1.2.0 as  the latest.
Even on their site https://f-droid.org/en/packages/com.machiav3lli.backup/

**Comment by machiav3lli** [comment]
The repo is still not updated. It doesn't get updated on daily basis, sometimes it take days. Last update was on 04.August so it'll be approximately in two days.
