### ISSUE TITLE
Feature: split APKs support

### ISSUE THREAD

**Issue by talk2g** [machiav3lli/oandbackupx#8]
Since some split apks can't be restored by the app..I personally redownload them from the source ,however the option to restore only data isn't there..
This is my first time time in github,so point me if I m wrong somewhere..
Thx

**Comment by scrubjay55** [comment]
it would even be better if split apks could be restored with oandbackupx.

**Comment by machiav3lli** [comment]
Could you give me an example of an app with split apks, so I can some testing while working on it. Otherwise, if you don't get errors while doing backup for both, you be able to restore apk alone as long as the app is installed.

**Comment by talk2g** [comment]
Some examples of split apks-
Camscanner, clash of clans, truecaller, wordweb.
Also - please look into restore "data only" otion if possible, since it is helpful sometimes if due to some error restoring of an app(not limited to split apks) isnt possible.

**Comment by machiav3lli** [comment]
Could you please try the latest version, backuping the data alone then restoring it later(after deleting & reinstalling the app). As that could be connected to following symlinks.

**Comment by soredake** [comment]
@aekium off-topic question, do you plan to put fsync and fs{hack,bypass} to staging?

**Comment by talk2g** [comment]
Ok, i tested the above method and it works on The latest version..

However the only issue is i have to backup "data" only and not "apk+data" to restore only data..
Is it possible to backup both "apk+data" and while restoring choose whether u want to backup only"data" "apk" or both "data+ apk"
I m not talking about split apks, since i know they aren't supported just yet..
I m talking about the regular apks

**Comment by talk2g** [comment]
K

**Comment by talk2g** [comment]
reopened since its an enchancement .

**Comment by tsiflimagas** [comment]
In my opinion, the most crucial new feature to be added, might is split apk support, since more and more apps in playstore(and maybe not only there) adopt this format. Some further apps which come with this format are some Google apps like Chrome and Gmail.

**Comment by machiav3lli** [comment]
Unfortunatly this will have to wait for sometime. My #1 priority for the app is to reach what I'd call new stable state then comes the encryption support. So realisticly I can't work on split support before July if eberything works fine. That's why every help concepating or even sketching a solution are welcome.

**Comment by tsiflimagas** [comment]
Sadly I have no coding knowledge to contribute ☹️ Though I think that for split app support you can get the code from other apps which already support it, like Aurora/yalp store, smartpack apk manager, Aptoide too I think. Of course, I agree reaching a stable state is the most important. I'm very happy that this project came up, oandbackup has been my favorite one for a very long time. Keep it up!

**Comment by scrubjay55** [comment]
There is an open source app called SAI(split APKs installer). Maybe you can check it out if you would like to have an idea? i dont know. I just hope that you can implement it soon since most of the apps are now distributed as split apks and it is a cruical feature.

**Comment by machiav3lli** [comment]
Thanks, I know of it but as said first stable & clean then I'd start adding extra features.

On my end, I didn't have any problems doing backups or restoring
(P.S. only three of my apps are closed source and so less SA. one of them is Whatsapp which is SA, still had no problem). 
If there's some concrete situations or apps that are making problems, you can report them so I can test them. Otherwise there's a priority list which am working with (next step: SAF)

**Comment by scrubjay55** [comment]
well, spotify has split apks and when i try to restore the backup with oandbackupx, it doesnt restore and dont even throw an error.
