### ISSUE TITLE
[Feature Request] Show app version(s) in the listings

### ISSUE THREAD

**Issue by manfred3000** [machiav3lli/oandbackupx#80]
It would be nice to be able to see at a glance the app version of installed apps, and if updated, the new version as well, without having to tap on the apps first in order to get the extended info.

**Comment by machiav3lli** [comment]
Such info was in my early drafts of the design but decided against it, as the only benefit it brings for the workflow of the app is as a pointer that the version of the app is higher than the one backed up. This will be reflected in the UI changes later this summer.

So sorry, but showing a "dry" app version means only more clutering.

**Comment by manfred3000** [comment]
I see, thanx. I found the display of app versions useful in the original oandbackup app, e.g. in the event I had updated an app and the update broke something which was only fixed several updates later. So I always knew at a glance which version I'm dealing with.

As far as cluttering goes, I personally don't need to know at first glance the date of an backup.

Anyway, keep up the great work and thanx again.
