### ISSUE TITLE
[feature request] an option to delete all backups

### ISSUE THREAD

**Issue by 07416** [machiav3lli/oandbackupx#81]
My batch-backup failed, perhaps the Busybox wasn't detected. I don't see any option to delete all backups or select all apps in the list view. If I wipe the app backup folder this may not be reflected in OandbackupX and can require reinstalling.

**Comment by machiav3lli** [comment]
Wiping the app folder should be reflected directly on the app.

Please provide more information of your setup (android version, app version, the ROM ...) and provide info if this "this may not" is a result of testing or just a hypothesis.

**Comment by 07416** [comment]
> Wiping the app folder should be reflected directly on the app.
> 
> Please provide more information of your setup (android version, app version, the ROM ...) and provide info if this "this may not" is a result of testing or just a hypothesis.

This was only a hypothesis and I was unconsciously running v1.2.0 from F-Droid. I can confirm that Oandbackupx checks the state of the backup folders.

I apologize for all inconvenience.
