### ISSUE TITLE
Low resolution / No logo on F-droid

### ISSUE THREAD

**Issue by aha999** [machiav3lli/oandbackupx#82]
On F-droid, there's a very low resolution logo of the OAndBackupX.

Please update the logo so it will be a higher resolution.

**Comment by machiav3lli** [comment]
You see, the icon I provided in Fastlane folder has a resolution as high as the ones from other apps, still it's not showing at all in FDroid on my side.

**Comment by machiav3lli** [comment]
If someone with enough can step in to clear it up, it'd appreciated. Thanks

**Comment by aha999** [comment]
This is a comment from another project where i posted the same issue before...
"This is because the asset used for the app icon doesn't have alternate sizes available depending on the screen density. I had the same issue in another app and fixed it by generating all five alternates."
https://github.com/bitwarden/mobile/issues/731#issuecomment-589964327

**Comment by machiav3lli** [comment]
So basicly icon.png in Fastlane has nothing to do with it, while in mimap PNGs have to be provided beside the .xml.

**Comment by machiav3lli** [comment]
And yes, it's seemingly an issue on the F-Droid side
