### ISSUE TITLE
(BUG) Copy error on sdcard

### ISSUE THREAD

**Issue by tokenmath** [machiav3lli/oandbackupx#83]
The backup on the memory card is not working. Even giving access correctly 

![Apk Backup Error](https://i.imgur.com/dCASFx0.png)

![Data Backup Error](https://i.imgur.com/h0FhAGa.png)

**Comment by machiav3lli** [comment]
Duplicate of #32. If you're on the latestlversion please always read the open issues before opening a new one. Thanks
