### ISSUE TITLE
discussion about Busybox

### ISSUE THREAD

**Issue by 07416** [machiav3lli/oandbackupx#85]
Will the application rely on Busybox in the future? Are there any alternatives to Busybox/Toybox currently and what's the minimum required version?

Busybox isn't mentioned in the readme, but [of the original app it is](https://github.com/jensstein/oandbackup#busybox--toybox--oab-utils).

**Comment by Atrate** [comment]
Why not Busybox though?

**Comment by 07416** [comment]
> Why not Busybox though?

It would at least be more convenient for new users if Busybox was bundled with the app.

**Comment by machiav3lli** [comment]
Actually the app is mostly over busybox since 0.9.0. Relaying on android's built-in toybox at first and now libsu(-io).

**Comment by 07416** [comment]
> Actually the app is mostly over busybox since 0.9.0. Relying on android's built-in toybox at first and now libsu(-io).

Is that so? Should running on LineageOS be possible without a Busybox installation? I got errors (which I didn't write down sadly) when running on LO 16 without Busybox, resolved by installing https://github.com/Magisk-Modules-Repo/busybox-ndk

**Comment by machiav3lli** [comment]
On what version? 
Full toybox installation is present in android since android O(on M and N it wasn't).
When you change the preference in the settings, this could break defaults. If you updated from FDroid's 1.2.0 straight to 3.0.0 I'd suggest you read the notices attached(changelogs)

**Comment by 07416** [comment]
I'm now on Android 10 (LineageOS 17), I was in the process of updating -- I'll create an issue if the problem persists.

I performed a clean installation for 3.0.0, as was suggested.
