### ISSUE TITLE
[Feature Request] Create a folder with the current time (year/month)

### ISSUE THREAD

**Issue by pythonius21** [machiav3lli/oandbackupx#850]
I hope the title explains a little bit.

So what I would like to see is, when your making a backup, it should automatically create a folder for the backup from which year and in it the month of today.

If it already exist, sorry for the duplicate, but I was unable to find that.
If not, would be nice to have for better management

Thanks in advanced!

**Comment by hg42** [comment]
it's sorted the other way
`package.name/date`

**Comment by hg42** [comment]
btw. you can easily use search in file managers to get the selection you want
