### ISSUE TITLE
[Bug] Laggy display

### ISSUE THREAD

**Issue by lapineige** [machiav3lli/oandbackupx#87]
In my case the app seems to work correctly, but the display is very laggy and freezes often.
For instance : 
- When I open the app, it takes minutes to show itself, while I'm still seeing the previous screen (but can't interact with it, as it's the app screen in fact).
- If I jump to the view where you see the opened apps, 
- For any action, I have to wait several (tens) seconds before the screen actually updates and shows something else.

After >10min with the app open, it seems that this problem is reduced to some micro-lags (<1s).

I'm using OmniROm 9.

**Comment by Atrate** [comment]
Could you provide specific device info as well as what version of the app you're using? I've not seen such behavior myself.

**Comment by lapineige** [comment]
Oh yeah, sorry about forgetting that :
- XZ2 Compact (dual sim, if it matters)
- 1.2.0-universal, from f-droid (the changelog says 3.0.0 :thinking:)
- OmniROM 9

**Comment by Atrate** [comment]
Try grabbing v3.0.0 and see if it works

**Comment by lapineige** [comment]
But it's not (yet) on f-droid, isn't it ?

**Comment by Atrate** [comment]
The latest version I see on F-Droid is v3.0.0

Direct link: https://f-droid.org/repo/com.machiav3lli.backup_3000.apk

**Comment by lapineige** [comment]
Oh great, what a big version bump ^^
So it's now available on f-droid, great :) (since august 10)

**Comment by Atrate** [comment]
Grant OABX superuser rights from Magisk Manager and see if the issue persists.

Apps often ask for su rights in the main thread/block until su rights are acquired so this may be the cause of the long startup time.

**Comment by lapineige** [comment]
The thing is, it's not shown in Magisk Manager :sweat_smile:

**Comment by Atrate** [comment]
Try setting the su request timeout to 60 seconds in Magisk.

If that does not work there is a veeery dirty workaround to force an app to ask for su permissions

**Comment by lapineige** [comment]
Still fails, long before the 60 seconds :(

Setting Magisk options to automatically allow superuser rights doesn't work either :/

**Comment by Atrate** [comment]
> Setting Magisk options to automatically allow superuser rights doesn't work either :/

That would probably rule it out, I can still give you the dirtiest workaround if you want, but first  can you get a logcat of the app when it tries to launch?

**Comment by lapineige** [comment]
Here is the logcat: https://pastebin.com/Cp19VfHT

I see this that seems strange:
> SurfaceFlinger: duplicate layer name: changing Surface(name=c8faa2f com.machiav3lli.backup/com.machiav3lli.backup.activities.IntroActivity)/@0x85dcc7d - animation-leash to Surface(name=c8faa2f com.machiav3lli.backup/com.machiav3lli.backup.activities.IntroActivity)/@0x85dcc7d - animation-leash#1
 LauncherTransition: Failed to animate, surface got destroyed.
 

Apparently nothing about the superuser rights.

**Comment by Atrate** [comment]
Does disabling animations help?

**Comment by lapineige** [comment]
It doesn't :(

**Comment by Atrate** [comment]
I'm out of suggestions so far. @machiav3lli might have some insights

**Comment by machiav3lli** [comment]
Is there any battery saving's magisk mods or some super battery saving custom kernel in the play?

**Comment by lapineige** [comment]
None that I'm aware of…
No Magisk Module, and I believe there is nothing like that in the kernel - but I don't know how to check that.

**Comment by machiav3lli** [comment]
If it's really how you describe it, it's a performance bottleneck which wasn't reported on other setups suggesting it has to do with the ROM, the kernel or some of your apps that run in the background may be eating away all of the cp cycles/RACPU

**Comment by lapineige** [comment]
Ok, I'll investigate about that potential kernel issue.

I'm pretty sure it's not an issue with any app, the system is fully responsive and I don't notice any slowdown of any kind.
And the previous OandBackup app doesn't have that issue.

**Comment by machiav3lli** [comment]
@lapineige Did that change?

**Comment by lapineige** [comment]
It was a Magisk issue: I upgraded from Magisk 18.x to 20.x, now it works 👍 
Thanks for your help :)
