### ISSUE TITLE
[Bug] Backup always stops at "Android System"

### ISSUE THREAD

**Issue by DamienCassou** [machiav3lli/oandbackupx#88]
**Description**

**Steps To Reproduce**
1. Start a backup of every app + their data
2. Wait a few hours
3. Backup is stuck at "Android System"

Except for the first backup I did which worked well, I can systematically reproduce. This means I can't backup "Android System".

**Expected behavior**

I expect either:

1. being able to select "Android System" and get my system fully backed up, or
2. not seeing "Android System" in the list of applications I can backup.

**System Information(please complete the following information):**
 - Device: OnePlus 1 (bacon)
 - Android Version: 9
 - ROM: LineageOS (July 23rd)
 - App's Version: 3.0.0 from f-droid

**Comment by DamienCassou** [comment]
I also tried to only backup "Android System" and the result is the same: one hour later, oandbackup still tries to backup it.

**Comment by Tiefkuehlpizze** [comment]
The Android System package (package name is just "android") is a very special one.
It's apk is `/system/framework/framework-res.apk` and its data dir is `/data/system`.

There are lots of sweet things inside like `appops.xml`, but also dangerous stuff like the stored lockscreen pattern or password and the `packagelist.xml`. I don't know, how Android behaves, if these files are just updated.

I wouldn't recommend to backup Android System and go for the special backups instead. These are limited, but can be implemented easily.

```generic_x86:/data/system # ls -l
total 764                            
-rw------- 1 system system        11220 2020-08-15 14:17 appops.xml
-rw------- 1 system system         1689 2020-08-13 23:28 batterystats-daily.xml
-rw------- 1 system system       132116 2020-08-15 14:16 batterystats.bin
-rw------- 1 system system          540 2020-08-13 23:28 cachequota.xml
-rw------- 1 system system          311 2020-08-03 19:06 device_policies.xml
-rw------- 1 system system          110 2020-08-06 20:26 deviceidle.xml
-rw------- 1 system system          334 2020-08-03 19:06 display-manager-state.xml
drwx------ 2 system system         8192 2020-08-15 14:16 dropbox
-rw------- 1 system system          512 2020-08-15 14:16 entropy.dat
drwx------ 6 system system         4096 2020-08-15 14:10 graphicsstats
drwx------ 2 system system         4096 2020-08-03 19:06 heapdump
drwx------ 2 system system         4096 2020-08-03 19:06 ifw
drwx------ 2 system system         4096 2020-08-13 23:28 inputmethod
drwx------ 2 system system         4096 2020-08-03 19:06 install_sessions
-rw------- 1 system system           70 2020-08-15 14:16 install_sessions.xml
drwx------ 2 system system         4096 2020-08-14 17:18 job
-rw------- 1 system system            0 2020-08-13 23:28 last-fstrim
-rw------- 1 system system          321 2020-08-13 23:28 last-header.txt
-rw-rw---- 1 system system        20480 2020-08-03 19:06 locksettings.db
-rw------- 1 system system         4029 2020-08-13 23:29 log-files.xml
srwxrwxrwx 1 system system            0 2020-08-13 23:28 ndebugsocket
-rw------- 1 system system          472 2020-08-13 23:28 netpolicy.xml
drwx------ 2 system system         4096 2020-08-14 17:24 netstats
-rw-rw---- 1 system system        32768 2020-08-15 14:21 notification_log.db
-rw-rw---- 1 system system            0 2020-08-15 14:21 notification_log.db-journal
-rw------- 1 system system        15229 2020-08-15 14:22 notification_policy.xml
-rw------- 1 system system          333 2020-08-13 23:28 overlays.xml
-rw------- 1 system system         3781 2020-08-14 10:42 package-dex-usage.list
drwx------ 3 system system         4096 2020-08-03 19:06 package_cache
-rw-r----- 1 system package_info  11190 2020-08-15 14:16 packages.list
-rw-rw---- 1 system system       420378 2020-08-15 14:16 packages.xml
drwx------ 2 system system         4096 2020-08-15 14:16 procstats
-rw------- 1 system system           12 2020-08-15 14:17 screen_on_time
drwx------ 2 system system         4096 2020-08-03 19:06 sensor_service
-rw------- 1 system system          114 2020-08-13 23:28 shortcut_service.xml
-rw------- 1 system system          235 2020-08-13 23:28 storage.xml
drwx------ 2 system system         4096 2020-08-14 17:28 sync
drwx------ 2 system system         4096 2020-08-14 17:18 syncmanager-log
-rwxrwxr-- 1 system system         2225 2020-08-03 19:06 uiderrors.txt
drwx------ 3 system system         4096 2020-08-03 19:06 usagestats
drwxrwxr-x 3 system system         4096 2020-08-13 23:28 users
```

**Comment by machiav3lli** [comment]
Doing a backup of all of the system implies not only problem with android framework resources, there's a heck of a long list of apks that shouldn't be restored(replaced) while system is on.

Any intersection(criss-crossing) of changes between them results generaly a bootloop(in some situations non-recoverable). This is why for example a lot of common system packages from different AOSP ROMs don't work together and breaks the system. As @Tiefkuehlpizze said, it's explicitly not recommended to do system backups on apk basis. For such a thing, TWRP backups handles it far better and safer.

**Comment by DamienCassou** [comment]
@Tiefkuehlpizze said:
> I wouldn't recommend to backup Android System

If "Android System" shouldn't be backed up, could it be hidden (at least by default)?

> and go for the special backups instead.

I saw a special backups checkbox in the settings but I have no clue what this is. Can you please tell me? Or, even better, add the description of this checkbox to the application itself.

> Doing a backup of all of the system implies not only problem with android framework resources, there's a heck of a long list of apks that shouldn't be restored(replaced) while system is on.

Could the UI be simplified to prevent basic users from doing such mistakes?

**Comment by Tiefkuehlpizze** [comment]
> If "Android System" shouldn't be backed up, could it be hidden (at least by default)?
Sure. I would consider it as one of the pesky smaller issues. 

> I saw a special backups checkbox in the settings but I have no clue what this is. Can you please tell me? Or, even better, add the description of this checkbox to the application itself.

Special Backups are hardcoded objects in the list of apps in the app. They have a list of files to backup instead of going for the data directory. The wifi networks are stored in `/data/misc/wifi/WifiConfigStore.xml` so the Wifi backup is backing up and restoring this single file.
 
> Could the UI be simplified to prevent basic users from doing such mistakes?
Sure. I'm focused on the processing. But I also think, that the UI needs a lot more to give the user a very good experience. There are many small things, the user must be made aware of and ask for something. Sometimes it's a matter of setting the right defaults.

I'm personally not backing up system stuff. Most apps don't even have data and their apk is useless and might lead to system instability. But there is no reliable way to figure our, which app is useful and which not. Maybe it would make sense to hide system apps by default and enable them on the user's will with the additional option to run checks, if the app has stored possibly valuable data…

**Comment by DamienCassou** [comment]
Thank you for your answers. I think we can now close the issue.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
