### ISSUE TITLE
[Feature Request] Select all but a few applications when scheduling

### ISSUE THREAD

**Issue by DamienCassou** [machiav3lli/oandbackupx#89]
Because of #88, I would like to schedule a backup that saves all applications and their data but "Android System". The only way I found to do that is to select "Custom list" while creating a new schedule and to check every app, one at a time, but "Android System".

**Describe the primer solution**

I would like to be able to select all applications and then uncheck "Android System" (or, even better, for #88 to be fixed :-))

When making a single backup (as opposed to a scheduled one), I can select "All" and then uncheck: I would like to do the same while scheduling.

**System Information(please complete the following information):**
-    Device: OnePlus 1 (bacon)
-    Android Version: 9
-    ROM: LineageOS (July 23rd)
-    App's Version: 3.0.0 from f-droid

**Comment by machiav3lli** [comment]
It's already there, see your black list please. Thanks

**Comment by DamienCassou** [comment]
@machiav3lli said:

> see your black list please


what is my black list? I can't find any mention of a black list mechanism in the README or in the preferences of the application or in any other screen.

**Comment by Atrate** [comment]
The blacklist can be applied to scheduled backups

**Comment by DamienCassou** [comment]
Atrate <notifications@github.com> writes:
> The blacklist can be applied to scheduled backups

thank you, I now have found it!

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
