### ISSUE TITLE
[Bug] Tool bars are hard to understand

### ISSUE THREAD

**Issue by DamienCassou** [machiav3lli/oandbackupx#90]
Hi,

I appreciate all the work you do to bring oandbackup to the present. I think you are doing a great job, thank you!

I'm not sure about the use of tool bars though. Because they are small, you don't put texts in them. This makes it hard to understand what each button is supposed to do. Here are the 3 toolbars I found and the problems each one causes in my opinion.

## Main view

![oandbackupx-main](https://user-images.githubusercontent.com/217543/90330679-f8d16f00-dfae-11ea-8207-55916a49d0fb.png)

- The cog, calendar and sort buttons are quite clear; :+1: 
- I though the third button was showing a clock so I guessed it was supposed to schedule backups but it instead is meant for restoring; I only understood later that the arrow was going anti-clockwise and should probably mean restore :-).
- I think the second button isn't saying anything about the backup feature it implements.

Maybe the backup and restore buttons should be symmetric: such as download and upload symbols:

![2020-08-16-105151](https://user-images.githubusercontent.com/217543/90330626-8cef0680-dfae-11ea-8a5f-d54527404e87.png)
![2020-08-16-105201](https://user-images.githubusercontent.com/217543/90330627-8d879d00-dfae-11ea-9110-cf853d59f277.png)

I think a menu that one can drag from the sides of the screen would be clearer:
- it would be the same UX as most other apps (at least the ones I have tried)
- It would give you some more space to have a label next to the icon

What about an arrow going to a safe for backup and an arrow going out of a saf for restore?

## Schedules
![oandbackupx-schedules](https://user-images.githubusercontent.com/217543/90330682-fcfd8c80-dfae-11ea-8f48-0c7b93cfc1e3.png)

The icon here means "Copy" to me. It's only because @Atrate told me that I understood it meant blacklist. Because I didn't need to copy, I would never have clicked this icon.

## One scheduled backup

![oandbackupx-schedule](https://user-images.githubusercontent.com/217543/90330688-01c24080-dfaf-11ea-82a2-f387fdc908f4.png)

I think this is the screen where the toolbar shows its limitations the most:
- It's now obvious for me that "Interval in days" meant "between backups" but it wasn't at the beginning. I think having a full sentence (e.g., "Number of days between 2 backups") would be clearer. Moreover, a dynamic sentence updating after changes would improve user experience: e.g., "Will backup everyday", "Will backup every 3 days"
- I was lucky to see that the backup mode was longer than the width of the window. I guess that with a slightly narrower screen, I would have completely missed it.

I think a settings screen (the same kind you have for the application) would make more sense here.

**Comment by machiav3lli** [comment]
Long pressing any of the icons gives back its function(tooltip). I agree that the symbolic of the icons isn't that perfect and am already working on a new app design idea.
P.S. third icon in Main is "restore" in Material resources.
