### ISSUE TITLE
GMS issue fixed? 

### ISSUE THREAD

**Issue by hagaygo** [machiav3lli/oandbackupx#94]
Had a problem, mainly with WhatsApp after restoring with original oab app.

After restoring, push notifications did not work while phone was sleeping/screen off.

More info here https://www.xda-developers.com/broken-push-notifications-fix/amp/

Has been fixed/adressed in oandbackupx?

**Comment by Tiefkuehlpizze** [comment]
I cannot tell you this. Technically apps are restored by using the package installer service. If the registration happens during the installation, it should work.

**Comment by hagaygo** [comment]
If nothing changed since original oandbackup then this issue still exists.

Migrate works just fine with WhatsApp , it mentions it deletes GMS files after restore.

Found XDA thread which mentions a solution

https://forum.xda-developers.com/showpost.php?p=80430039&postcount=857

**Comment by machiav3lli** [comment]
Would you handle it while building the new backup logic @Tiefkuehlpizze? Maybe just another filter to exclude the files from the backup, they seem to have a clear scheme.

**Comment by Tiefkuehlpizze** [comment]
Shouldn't be a big deal to exclude more directories or files from the backup. If it's really just that, it can be added.

**Comment by hg42** [comment]
OABX uses pm install, which should be the same as installing from Play Store.
I think this is equivalent to the solution told in the first article, if we restore data first.
If we restore data after pm install, it would overwrite the FCM token (of the app) with the old one and probably not trigger a negotiation again.

**Comment by machiav3lli** [comment]
Could someone please test this on the latest 5.0.0 and report back. Thanks.

**Comment by PaPa1ya** [comment]
In version 6.0.1 and 7.0.0 beta 4 restored apps are not registered in GCM and push messages do not come. 
In general, I found that to manually re-register the app, I need to delete the file com.google.android.gms.appid.xml from /data/data/application_name/shared_prefs/, stop the app forcibly and start again. When restoring a backup, this file (com.google.android.gms.appid.xml) is also restored for some reason. With all this, there is a folder NO_BACKUP where the file com.google.android.gms.appid-no-backup is located. what is the purpose of this folder? why does oandbackupX back up files that should not be backed up?
